    const translations = {
      ar: {
        exportXlsx: "تصدير إكسل",
        exportBtn: "تصدير",
        caseFileTitle: "ملف القضية",
        caseFileEmpty: "لا عناصر تحت هذه القضية بعد.",
        secSessions: "الجلسات",
        secRulings: "الأحكام",
        secExecutions: "طلبات التنفيذ",
        secViolations: "المخالفات",
        secTasks: "المهام",
        secDocuments: "المستندات",
        fieldCourt: "المحكمة",
        fieldStage: "المرحلة",
        openCaseFile: "ملف القضية",
        appName: "TheTracker",
        exportCsv: "تصدير CSV",
        title: "لوحة التحكم",
        loading: "جاري التحميل...",
        serviceUnavailableTitle: "الخدمة قيد التجهيز",
        serviceUnavailableText: "نعمل حاليا على تجهيز الخدمة، حاول مرة أخرى لاحقا.",
        noOrg: "لا توجد شركة محددة، أنشئ شركتك أولا.",
        planLimitItems: "وصلت إلى الحد الأقصى لعدد العناصر في باقتك الحالية، رق باقتك لإضافة المزيد.",
        planLimitMembers: "وصلت إلى الحد الأقصى لعدد الأعضاء في باقتك الحالية، رق باقتك لإضافة المزيد.",
        planLimitLink: "عرض الباقات والأسعار",
        genericError: "حدث خطأ، حاول مرة أخرى.",
        errorLoad: "تعذر تحميل البيانات، حاول مرة أخرى.",
        saved: "تم الحفظ.",
        deleted: "تم الحذف.",
        companyLabel: "الشركة:",
        switchOrg: "التبديل بين الشركات",
        newOrgBtn: "+ شركة جديدة",
        renameOrgBtn: "تعديل الاسم",
        deleteOrgBtn: "حذف الشركة",
        orgRenamed: "تم تعديل اسم الشركة.",
        deleteOrgConfirm: "ستحذف الشركة «{name}» وكل عناصرها وسجلاتها نهائيا. هل تتابع؟",
        newOrgPlaceholder: "اسم الجهة",
        selfNamePlaceholder: "اسمك الكامل",
        newOrgSubmit: "إنشاء",
        cancel: "إلغاء",
        createOrgTitle: "ابدأ حسابك",
        createOrgIntro: "اختر نوع الحساب: شركة أو مؤسسة أو وثيقة عمل حر، أو شخصا يريد ترتيب أوراقه.",
        packPickLine: "اختر الواجهة التي تناسب تخصصك.",
        packChoose: "اختيار",
        orgCreated: "تم إنشاء الشركة.",
        orgNameRequired: "أدخل اسم الشركة.",
        linkImport: "استيراد ملف",
        linkTeam: "الفريق",
        linkSettings: "الإعدادات",
        linkAdmin: "إدارة المنصة",
        signOut: "تسجيل الخروج",
        statOpen: "عناصر مفتوحة",
        statDue7: "مستحقة خلال 7 أيام",
        statOverdue: "متأخرة",
        statDone: "مكتملة",
        tabList: "القائمة",
        timelineTitle: "إنجازاتك",
        tlNow: "الان",
        tlPrev: "المعلم السابق",
        tlNext: "المعلم التالي",
        tlEventOf: "الحدث {i} من {n}",
        timelineEmpty: "لا نشاط بعد — ابدأ باستيراد ملف أو إضافة موعد.",
        tlCreated: "أضيف عنصر",
        tlDone: "أنجز",
        tlImport: "استيراد ملف",
        tlAttachment: "رفع ملف",
        tlMember: "انضم عضو",
        tlPlan: "اشتراك",
        tlToday: "اليوم",
        tlYesterday: "أمس",
        tlDaysAgo: "قبل {n} يوما",
        achDoneMonth: "أنجز هذا الشهر",
        achItems: "إجمالي العناصر",
        achFiles: "الملفات",
        achImports: "عمليات الاستيراد",
        colVNumber: "رقم المخالفة",
        colCaseNumber: "رقم الدعوى",
        caseBundleTitle: "ملف الدعوى {n}",
        caseBundleEmpty: "لا توجد عناصر مرتبطة بهذا الرقم.",
        colVDate: "تاريخ المخالفة",
        colClient: "الشركة",
        colIssuer: "جهة الإصدار",
        colAmount: "المبلغ",
        colVType: "نوع المخالفة",
        colObjection: "حالة التظلم",
        colPayDue: "موعد السداد",
        allClients: "كل الشركات",
        totalCount: "عدد المخالفات",
        totalAmount: "إجمالي المبالغ",
        totalUnpaid: "غير المسددة",
        totalOverdue: "تجاوزت موعد السداد",
        attachTitle: "المرفقات",
        attachDrive: "اختيار من Google Drive",
        attachUpload: "رفع ملف (PDF أو Word)",
        attachLinkPlaceholder: "أو الصق رابط جوجل درايف",
        attachLinkBtn: "إضافة الرابط",
        attachEmpty: "لا مرفقات لهذا العنصر.",
        attachUploading: "جاري الرفع...",
        attachDone: "تمت الإضافة.",
        attachFailed: "تعذر رفع الملف.",
        attachLimit: "تجاوزت مساحة التخزين المسموحة في باقتك.",
        attachDeleteConfirm: "حذف المرفق نهائيا؟",
        attachLinkLabel: "رابط خارجي",
        delete: "حذف",
        chartTitle: "المؤشر (جدول المخالفات)",
        indicatorsTitle: "المؤشرات الحالية للمخالفات والجلسات",
        courtsTitle: "إجمالي القضايا {n} (حسب المحكمة)",
        cancelledAmount: "مبلغ المخالفات التي تم إلغاؤها",
        noCourtData: "لا توجد بيانات محاكم بعد.",
        chartTotal: "إجمالي المخالفات",
        chartObjected: "تم التظلم فيها",
        chartCourt: "مرفوعة للمحكمة",
        chartRepeated: "المخالفات المتكررة",
        casesIndicatorsTitle: "المؤشرات الحالية للقضايا",
        casesChartTitle: "المؤشر (جدول القضايا)",
        caseTotal: "إجمالي القضايا",
        caseOpen: "قضايا جارية",
        caseOverdue: "متأخرة عن موعدها",
        caseDone: "قضايا منتهية",
        clientsTitle: "العملاء {n} (حسب العميل)",
        noClientData: "لا توجد بيانات عملاء بعد.",
        caseAmount: "إجمالي مبالغ القضايا",
        caseDoneAmount: "مبالغ القضايا المنتهية",
        viewCases: "لوحة القضايا",
        viewExpenses: "مصاريف التشغيل",
        colExpDate: "التاريخ",
        colExpCat: "البند",
        colExpDesc: "البيان",
        colExpVendor: "الجهة",
        colExpMethod: "طريقة الدفع",
        allCats: "كل البنود",
        allYears: "كل السنوات",
        expCount: "عدد المصاريف",
        expTotal: "إجمالي المصروف",
        expPaid: "المدفوع",
        expDue: "المستحق",
        expOverdue: "متأخر السداد",
        expAvgMonth: "متوسط الشهر",
        expIndicatorsTitle: "مؤشرات المصاريف",
        expMonthlyTitle: "المصروف شهريا ({y})",
        expByCatTitle: "حسب البند ({n})",
        noExpenseData: "لا توجد مبالغ مسجلة بعد",
        expNoCat: "بلا بند",
        expStatusPaid: "مدفوع",
        expActionPay: "تعليم كمدفوع",
        fieldAmount: "المبلغ",
        fieldClient: "الجهة أو العميل",
        fieldClientEn: "الجهة أو العميل بالإنجليزية",
        appealDeadline: "مهلة الاستئناف",
        appealTitle: "مهلة استئناف — {case}",
        appealCategory: "مهلة استئناف",
        nextSession: "الجلسة القادمة",
        nextSessionTitle: "جلسة — {case}",
        sessionCategory: "جلسة",
        weekTitle: "ملخص الأسبوع",
        weekDone: "أُنجز هذا الأسبوع",
        weekAdded: "أُضيف هذا الأسبوع",
        weekLate: "تأخر هذا الأسبوع",
        weekSame: "مثل الأسبوع الماضي",
        weekVsLast: "عن الأسبوع الماضي",
        colNumber: "الرقم",
        fieldRemind: "ذكرني قبل",
        remindDefault: "حسب قاعدة السجل",
        remindDay: "بيوم",
        remind3Days: "بثلاثة أيام",
        remindWeek: "بأسبوع",
        remind2Weeks: "بأسبوعين",
        remindMonth: "بشهر",
        fieldCaseNumber: "رقم الملف",
        viewViolations: "لوحة المخالفات",
        servicesTitle: "الخدمات",
        calendarCardTitle: "التقويم والمواعيد",
        startService: "بدء الخدمة",
        svcImportTitle: "استيراد من إكسل",
        svcImportText: "حول جدول مواعيدك وعقودك إلى عناصر متابعة في دقيقة.",
        svcAddTitle: "إضافة موعد",
        svcAddText: "سجل جلسة أو موعد استحقاق جديدا يدويا.",
        svcTeamTitle: "دعوة زميل",
        svcTeamText: "أضف زملاءك وأسند إليهم المواعيد والمهام.",
        svcTelegramTitle: "ربط تيليغرام",
        svcTelegramText: "استقبل تنبيه كل موعد على تيليغرام قبل حلوله.",
        svcCalendarTitle: "ربط التقويم",
        svcCalendarText: "اربط مواعيدك بتقويم جوجل أو آبل أو أوتلوك بنقرة.",
        tabCalendar: "التقويم",
        filterAllTrackers: "كل السجلات",
        filterAllStatuses: "كل الحالات",
        searchPlaceholder: "بحث في العناوين",
        statusOpen: "مفتوح",
        statusDone: "مكتمل",
        statusCancelled: "ملغى",
        statusOverdue: "متأخر",
        colTitle: "العنوان",
        colTracker: "السجل",
        colDue: "موعد الاستحقاق",
        colAssignee: "المسؤول",
        colStatus: "الحالة",
        colActions: "الإجراءات",
        noItems: "لا توجد عناصر مطابقة.",
        noDue: "بدون موعد",
        noAssignee: "غير محدد",
        actionDone: "إنجاز",
        actionReopen: "إعادة فتح",
        actionEdit: "تعديل",
        actionDelete: "حذف",
        confirmDelete: "هل تريد حذف هذا العنصر؟ لا يمكن التراجع عن الحذف.",
        editTitle: "تعديل العنصر",
        addItemBtn: "+ عنصر",
        addItemTitle: "عنصر جديد",
        fieldTitle: "العنوان",
        fieldTracker: "السجل",
        fieldDue: "موعد الاستحقاق",
        fieldCategory: "التصنيف",
        fieldAssignee: "المسؤول",
        fieldStatus: "الحالة",
        titlePlaceholder: "عنوان العنصر",
        categoryPlaceholder: "التصنيف (اختياري)",
        chooseTracker: "اختر السجل",
        save: "حفظ",
        add: "إضافة",
        titleRequired: "أدخل عنوان العنصر.",
        trackerRequired: "اختر سجلا أولا.",
        newTrackerBtn: "+ سجل جديد",
        newTrackerPlaceholder: "اسم السجل",
        trackerCreated: "تم إنشاء السجل.",
        trackerNameRequired: "أدخل اسم السجل.",
        noTrackersHint: "لا توجد سجلات بعد، أنشئ سجلا أولا لتتمكن من إضافة العناصر.",
        calPrev: "الشهر السابق",
        calNext: "الشهر التالي",
        calToday: "اليوم",
        calFilterAll: "الكل", calFilterCases: "قضايا", calFilterViolations: "مخالفات", calFilterTasks: "مهام", calFilterDocs: "أوراق",
        calGregorian: "ميلادي",
        calHijri: "هجري",
        daySun: "الأحد",
        dayMon: "الاثنين",
        dayTue: "الثلاثاء",
        dayWed: "الأربعاء",
        dayThu: "الخميس",
        dayFri: "الجمعة",
        daySat: "السبت",
        month1: "يناير",
        month2: "فبراير",
        month3: "مارس",
        month4: "أبريل",
        month5: "مايو",
        month6: "يونيو",
        month7: "يوليو",
        month8: "أغسطس",
        month9: "سبتمبر",
        month10: "أكتوبر",
        month11: "نوفمبر",
        month12: "ديسمبر",
        moreItems: "{n} عناصر أخرى",
        icsTitle: "رابط التقويم (ICS)",
        icsHint: "أضف هذا الرابط إلى تقويم Apple أو Google أو Outlook بوصفه اشتراكا في تقويم عبر الرابط، لتظهر مواعيد عناصرك تلقائيا وتتحدث دوريا.",
        copy: "نسخ الرابط",
        copied: "تم نسخ الرابط.",
        regenerate: "إعادة توليد الرابط",
        confirmRegenerate: "سيتوقف الرابط الحالي عن العمل وسيلزمك إضافة الرابط الجديد إلى تقويمك. هل تريد المتابعة؟",
        regenerated: "تم توليد رابط جديد.",
        icsSecret: "هذا الرابط خاص بك، لا تشاركه مع الآخرين.",
        itemDone: "تم إنجاز العنصر.",
        itemReopened: "أعيد فتح العنصر.",
        itemAdded: "تمت إضافة العنصر.",
        copyrightLine2: "جميع الحقوق محفوظة",
        aboutLink: "من نحن",
        termsLink: "شروط الاستخدام",
        pricingLink: "الباقات والأسعار",
        privacyLink: "سياسة الخصوصية",
        loginLink: "تسجيل الدخول",
        dashboardLink: "لوحة التحكم",
        contactLink: "تواصل معنا",
        language: "اللغة",
        appearance: "المظهر",
        light: "فاتح",
        dark: "داكن"
      },
      en: {
        exportXlsx: "Export Excel",
        exportBtn: "Export",
        caseFileTitle: "Case file",
        caseFileEmpty: "Nothing filed under this case yet.",
        secSessions: "Hearings",
        secRulings: "Rulings",
        secExecutions: "Execution requests",
        secViolations: "Violations",
        secTasks: "Tasks",
        secDocuments: "Documents",
        fieldCourt: "Court",
        fieldStage: "Stage",
        openCaseFile: "Case file",
        appName: "TheTracker",
        exportCsv: "Export CSV",
        title: "Dashboard",
        loading: "Loading...",
        serviceUnavailableTitle: "Service is being prepared",
        serviceUnavailableText: "We are setting up the service. Please try again later.",
        noOrg: "No company selected. Create your company first.",
        planLimitItems: "You have reached the item limit of your current plan. Upgrade to add more.",
        planLimitMembers: "You have reached the member limit of your current plan. Upgrade to add more.",
        planLimitLink: "View plans & pricing",
        genericError: "Something went wrong. Please try again.",
        errorLoad: "Could not load data. Please try again.",
        saved: "Saved.",
        deleted: "Deleted.",
        companyLabel: "Company:",
        switchOrg: "Switch company",
        newOrgBtn: "+ New company",
        renameOrgBtn: "Rename",
        deleteOrgBtn: "Delete company",
        orgRenamed: "Company name updated.",
        deleteOrgConfirm: "«{name}» and all of its items and trackers will be permanently deleted. Continue?",
        newOrgPlaceholder: "Entity name",
        selfNamePlaceholder: "Your full name",
        newOrgSubmit: "Create",
        cancel: "Cancel",
        createOrgTitle: "Start your account",
        createOrgIntro: "Choose the account type: a company, an establishment, a freelance permit, or an individual organising their own papers.",
        packPickLine: "Choose the interface that fits your work.",
        packChoose: "Choose",
        orgCreated: "Company created.",
        orgNameRequired: "Enter the company name.",
        linkImport: "Import file",
        linkTeam: "Team",
        linkSettings: "Settings",
        linkAdmin: "Platform admin",
        signOut: "Sign out",
        statOpen: "Open items",
        statDue7: "Due within 7 days",
        statOverdue: "Overdue",
        statDone: "Done",
        tabList: "List",
        timelineTitle: "Your progress",
        tlNow: "NOW",
        tlPrev: "Previous milestone",
        tlNext: "Next milestone",
        tlEventOf: "Event {i} of {n}",
        timelineEmpty: "No activity yet — import a file or add an appointment.",
        tlCreated: "Item added",
        tlDone: "Completed",
        tlImport: "File imported",
        tlAttachment: "File uploaded",
        tlMember: "Member joined",
        tlPlan: "Subscription",
        tlToday: "Today",
        tlYesterday: "Yesterday",
        tlDaysAgo: "{n} days ago",
        achDoneMonth: "Completed this month",
        achItems: "Total items",
        achFiles: "Files",
        achImports: "Imports",
        colVNumber: "Violation no.",
        colCaseNumber: "Case no.",
        caseBundleTitle: "Case file {n}",
        caseBundleEmpty: "Nothing linked to this number.",
        colVDate: "Violation date",
        colClient: "Client",
        colIssuer: "Issuer",
        colAmount: "Amount",
        colVType: "Violation type",
        colObjection: "Appeal status",
        colPayDue: "Payment due",
        allClients: "All clients",
        totalCount: "Violations",
        totalAmount: "Total amount",
        totalUnpaid: "Unpaid",
        totalOverdue: "Past due",
        attachTitle: "Attachments",
        attachDrive: "Pick from Google Drive",
        attachUpload: "Upload a file (PDF or Word)",
        attachLinkPlaceholder: "Or paste a Google Drive link",
        attachLinkBtn: "Add link",
        attachEmpty: "No attachments for this item.",
        attachUploading: "Uploading...",
        attachDone: "Added.",
        attachFailed: "Could not upload the file.",
        attachLimit: "Your plan storage limit is exhausted.",
        attachDeleteConfirm: "Delete this attachment permanently?",
        attachLinkLabel: "external link",
        delete: "Delete",
        chartTitle: "Violations indicator",
        indicatorsTitle: "Current violation and hearing indicators",
        courtsTitle: "Cases {n} (by court)",
        cancelledAmount: "Cancelled fines amount",
        noCourtData: "No court data yet.",
        chartTotal: "Total violations",
        chartObjected: "Appealed",
        chartCourt: "Referred to court",
        chartRepeated: "Repeated violations",
        casesIndicatorsTitle: "Current case indicators",
        casesChartTitle: "Cases indicator",
        caseTotal: "Total cases",
        caseOpen: "Open cases",
        caseOverdue: "Overdue",
        caseDone: "Closed cases",
        clientsTitle: "Clients {n} (by client)",
        noClientData: "No client data yet.",
        caseAmount: "Total case amounts",
        caseDoneAmount: "Closed case amounts",
        viewCases: "Cases dashboard",
        viewExpenses: "Operating expenses",
        colExpDate: "Date",
        colExpCat: "Category",
        colExpDesc: "Description",
        colExpVendor: "Payee",
        colExpMethod: "Payment method",
        allCats: "All categories",
        allYears: "All years",
        expCount: "Expenses",
        expTotal: "Total spent",
        expPaid: "Paid",
        expDue: "Outstanding",
        expOverdue: "Overdue",
        expAvgMonth: "Monthly average",
        expIndicatorsTitle: "Expense indicators",
        expMonthlyTitle: "Monthly spend ({y})",
        expByCatTitle: "By category ({n})",
        noExpenseData: "No amounts recorded yet",
        expNoCat: "Uncategorised",
        expStatusPaid: "Paid",
        expActionPay: "Mark as paid",
        fieldAmount: "Amount",
        fieldClient: "Party or client",
        fieldClientEn: "Party or client in English",
        appealDeadline: "Appeal deadline",
        appealTitle: "Appeal deadline — {case}",
        appealCategory: "Appeal deadline",
        nextSession: "Next hearing",
        nextSessionTitle: "Hearing — {case}",
        sessionCategory: "Hearing",
        weekTitle: "This week",
        weekDone: "Finished this week",
        weekAdded: "Added this week",
        weekLate: "Late this week",
        weekSame: "Same as last week",
        weekVsLast: "vs last week",
        colNumber: "Number",
        fieldRemind: "Remind me before",
        remindDefault: "As the tracker's rule says",
        remindDay: "One day",
        remind3Days: "Three days",
        remindWeek: "One week",
        remind2Weeks: "Two weeks",
        remindMonth: "One month",
        fieldCaseNumber: "File number",
        viewViolations: "Violations dashboard",
        servicesTitle: "Services",
        calendarCardTitle: "Calendar & hearings",
        startService: "Start service",
        svcImportTitle: "Import from Excel",
        svcImportText: "Turn your schedule or contracts into tracked items in a minute.",
        svcAddTitle: "Add an appointment",
        svcAddText: "Log a hearing or a due date by hand.",
        svcTeamTitle: "Invite a colleague",
        svcTeamText: "Add colleagues and assign dates and tasks to them.",
        svcTelegramTitle: "Connect Telegram",
        svcTelegramText: "Get every reminder on Telegram before it is due.",
        svcCalendarTitle: "Connect your calendar",
        svcCalendarText: "Link your dates to Google, Apple or Outlook in one click.",
        tabCalendar: "Calendar",
        filterAllTrackers: "All trackers",
        filterAllStatuses: "All statuses",
        searchPlaceholder: "Search titles",
        statusOpen: "Open",
        statusDone: "Done",
        statusCancelled: "Cancelled",
        statusOverdue: "Overdue",
        colTitle: "Title",
        colTracker: "Tracker",
        colDue: "Due date",
        colAssignee: "Assignee",
        colStatus: "Status",
        colActions: "Actions",
        noItems: "No matching items.",
        noDue: "No due date",
        noAssignee: "Unassigned",
        actionDone: "Mark done",
        actionReopen: "Reopen",
        actionEdit: "Edit",
        actionDelete: "Delete",
        confirmDelete: "Delete this item? This cannot be undone.",
        editTitle: "Edit item",
        addItemBtn: "+ Item",
        addItemTitle: "New item",
        fieldTitle: "Title",
        fieldTracker: "Tracker",
        fieldDue: "Due date & time",
        fieldCategory: "Category",
        fieldAssignee: "Assignee",
        fieldStatus: "Status",
        titlePlaceholder: "Item title",
        categoryPlaceholder: "Category (optional)",
        chooseTracker: "Choose a tracker",
        save: "Save",
        add: "Add",
        titleRequired: "Enter the item title.",
        trackerRequired: "Choose a tracker first.",
        newTrackerBtn: "+ New tracker",
        newTrackerPlaceholder: "Tracker name",
        trackerCreated: "Tracker created.",
        trackerNameRequired: "Enter the tracker name.",
        noTrackersHint: "No trackers yet. Create a tracker first to add items.",
        calPrev: "Previous month",
        calNext: "Next month",
        calToday: "Today",
        calFilterAll: "All", calFilterCases: "Cases", calFilterViolations: "Violations", calFilterTasks: "Tasks", calFilterDocs: "Papers",
        calGregorian: "Gregorian",
        calHijri: "Hijri",
        daySun: "Sun",
        dayMon: "Mon",
        dayTue: "Tue",
        dayWed: "Wed",
        dayThu: "Thu",
        dayFri: "Fri",
        daySat: "Sat",
        month1: "January",
        month2: "February",
        month3: "March",
        month4: "April",
        month5: "May",
        month6: "June",
        month7: "July",
        month8: "August",
        month9: "September",
        month10: "October",
        month11: "November",
        month12: "December",
        moreItems: "{n} more items",
        icsTitle: "Calendar link (ICS)",
        icsHint: "Add this link to Apple Calendar, Google Calendar or Outlook as a calendar subscription (by URL) so your item due dates appear automatically and stay up to date.",
        copy: "Copy link",
        copied: "Link copied.",
        regenerate: "Regenerate link",
        confirmRegenerate: "The current link will stop working and you will need to add the new link to your calendar. Continue?",
        regenerated: "A new link was generated.",
        icsSecret: "This link is personal. Do not share it with others.",
        itemDone: "Item marked as done.",
        itemReopened: "Item reopened.",
        itemAdded: "Item added.",
        copyrightLine2: "All rights reserved",
        aboutLink: "About Us",
        termsLink: "Terms of Use",
        pricingLink: "Plans & Pricing",
        privacyLink: "Privacy Policy",
        loginLink: "Sign in",
        dashboardLink: "Dashboard",
        contactLink: "Contact Us",
        language: "Language",
        appearance: "Appearance",
        light: "Light",
        dark: "Dark"
      },
      fr: {
        exportXlsx: "Exporter Excel",
        exportBtn: "Exporter",
        caseFileTitle: "Dossier",
        caseFileEmpty: "Rien encore rattaché à cette affaire.",
        secSessions: "Audiences",
        secRulings: "Jugements",
        secExecutions: "Demandes d'exécution",
        secViolations: "Infractions",
        secTasks: "Tâches",
        secDocuments: "Documents",
        fieldCourt: "Tribunal",
        fieldStage: "Étape",
        openCaseFile: "Dossier",
        appName: "TheTracker",
        exportCsv: "Exporter CSV",
        title: "Tableau de bord",
        loading: "Chargement...",
        serviceUnavailableTitle: "Service en cours de préparation",
        serviceUnavailableText: "Nous préparons le service. Veuillez réessayer plus tard.",
        noOrg: "Aucune entreprise sélectionnée. Créez d'abord votre entreprise.",
        planLimitItems: "Vous avez atteint la limite d'éléments de votre forfait actuel. Passez à un forfait supérieur pour en ajouter.",
        planLimitMembers: "Vous avez atteint la limite de membres de votre forfait actuel. Passez à un forfait supérieur pour en ajouter.",
        planLimitLink: "Voir les forfaits et tarifs",
        genericError: "Une erreur est survenue. Veuillez réessayer.",
        errorLoad: "Impossible de charger les données. Veuillez réessayer.",
        saved: "Enregistré.",
        deleted: "Supprimé.",
        companyLabel: "Entreprise :",
        switchOrg: "Changer d'entreprise",
        newOrgBtn: "+ Nouvelle entreprise",
        renameOrgBtn: "Renommer",
        deleteOrgBtn: "Supprimer l'entreprise",
        orgRenamed: "Nom de l'entreprise mis à jour.",
        deleteOrgConfirm: "«{name}» et tous ses éléments seront supprimés définitivement. Continuer ?",
        newOrgPlaceholder: "Nom de l'entité",
        selfNamePlaceholder: "Votre nom complet",
        newOrgSubmit: "Créer",
        cancel: "Annuler",
        createOrgTitle: "Ouvrez votre compte",
        createOrgIntro: "Choisissez le type de compte : société, établissement, travail indépendant ou particulier qui organise ses papiers.",
        packPickLine: "Choisissez l'interface qui correspond a votre activite.",
        packChoose: "Choisir",
        orgCreated: "Entreprise créée.",
        orgNameRequired: "Saisissez le nom de l'entreprise.",
        linkImport: "Importer un fichier",
        linkTeam: "Équipe",
        linkSettings: "Paramètres",
        linkAdmin: "Administration",
        signOut: "Se déconnecter",
        statOpen: "Éléments ouverts",
        statDue7: "À échéance sous 7 jours",
        statOverdue: "En retard",
        statDone: "Terminés",
        tabList: "Liste",
        timelineTitle: "Vos réalisations",
        tlNow: "MAINTENANT",
        tlPrev: "Jalon précédent",
        tlNext: "Jalon suivant",
        tlEventOf: "Événement {i} sur {n}",
        timelineEmpty: "Aucune activité — importez un fichier ou ajoutez un rendez-vous.",
        tlCreated: "Élément ajouté",
        tlDone: "Terminé",
        tlImport: "Fichier importé",
        tlAttachment: "Fichier téléversé",
        tlMember: "Membre ajouté",
        tlPlan: "Abonnement",
        tlToday: "Aujourd'hui",
        tlYesterday: "Hier",
        tlDaysAgo: "il y a {n} jours",
        achDoneMonth: "Terminés ce mois",
        achItems: "Éléments",
        achFiles: "Fichiers",
        achImports: "Imports",
        colVNumber: "N° d'infraction",
        colCaseNumber: "N° de dossier",
        caseBundleTitle: "Dossier {n}",
        caseBundleEmpty: "Rien de lié à ce numéro.",
        colVDate: "Date de l'infraction",
        colClient: "Client",
        colIssuer: "Émetteur",
        colAmount: "Montant",
        colVType: "Type d'infraction",
        colObjection: "Statut du recours",
        colPayDue: "Échéance de paiement",
        allClients: "Tous les clients",
        totalCount: "Infractions",
        totalAmount: "Montant total",
        totalUnpaid: "Impayées",
        totalOverdue: "En retard",
        attachTitle: "Pièces jointes",
        attachDrive: "Choisir dans Google Drive",
        attachUpload: "Téléverser un fichier (PDF ou Word)",
        attachLinkPlaceholder: "Ou collez un lien Google Drive",
        attachLinkBtn: "Ajouter le lien",
        attachEmpty: "Aucune pièce jointe.",
        attachUploading: "Téléversement...",
        attachDone: "Ajouté.",
        attachFailed: "Échec du téléversement.",
        attachLimit: "Stockage de votre forfait épuisé.",
        attachDeleteConfirm: "Supprimer définitivement ?",
        attachLinkLabel: "lien externe",
        delete: "Supprimer",
        chartTitle: "Indicateur des infractions",
        indicatorsTitle: "Indicateurs des infractions et audiences",
        courtsTitle: "Affaires {n} (par tribunal)",
        cancelledAmount: "Montant des amendes annulées",
        noCourtData: "Aucune donnée de tribunal.",
        chartTotal: "Total des infractions",
        chartObjected: "Contestées",
        chartCourt: "Portées en justice",
        chartRepeated: "Infractions répétées",
        casesIndicatorsTitle: "Indicateurs des affaires",
        casesChartTitle: "Indicateur des affaires",
        caseTotal: "Total des affaires",
        caseOpen: "Affaires en cours",
        caseOverdue: "En retard",
        caseDone: "Affaires clôturées",
        clientsTitle: "Clients {n} (par client)",
        noClientData: "Aucune donnée client.",
        caseAmount: "Montant total des affaires",
        caseDoneAmount: "Montant des affaires clôturées",
        viewCases: "Tableau des affaires",
        viewExpenses: "Charges d'exploitation",
        colExpDate: "Date",
        colExpCat: "Poste",
        colExpDesc: "Libellé",
        colExpVendor: "Bénéficiaire",
        colExpMethod: "Mode de paiement",
        allCats: "Tous les postes",
        allYears: "Toutes les années",
        expCount: "Dépenses",
        expTotal: "Total dépensé",
        expPaid: "Payé",
        expDue: "Restant dû",
        expOverdue: "En retard",
        expAvgMonth: "Moyenne mensuelle",
        expIndicatorsTitle: "Indicateurs des charges",
        expMonthlyTitle: "Dépenses mensuelles ({y})",
        expByCatTitle: "Par poste ({n})",
        noExpenseData: "Aucun montant enregistré",
        expNoCat: "Sans poste",
        expStatusPaid: "Payé",
        expActionPay: "Marquer payé",
        fieldAmount: "Montant",
        fieldClient: "Partie ou client",
        fieldClientEn: "Partie ou client en anglais",
        appealDeadline: "Délai d'appel",
        appealTitle: "Délai d'appel — {case}",
        appealCategory: "Délai d'appel",
        nextSession: "Prochaine audience",
        nextSessionTitle: "Audience — {case}",
        sessionCategory: "Audience",
        weekTitle: "Cette semaine",
        weekDone: "Terminé cette semaine",
        weekAdded: "Ajouté cette semaine",
        weekLate: "En retard cette semaine",
        weekSame: "Comme la semaine dernière",
        weekVsLast: "vs semaine dernière",
        colNumber: "Numéro",
        fieldRemind: "Me rappeler avant",
        remindDefault: "Selon la règle du registre",
        remindDay: "Un jour",
        remind3Days: "Trois jours",
        remindWeek: "Une semaine",
        remind2Weeks: "Deux semaines",
        remindMonth: "Un mois",
        fieldCaseNumber: "Numéro de dossier",
        viewViolations: "Tableau des infractions",
        servicesTitle: "Services",
        calendarCardTitle: "Agenda et audiences",
        startService: "Démarrer le service",
        svcImportTitle: "Importer depuis Excel",
        svcImportText: "Transformez votre agenda ou vos contrats en éléments suivis en une minute.",
        svcAddTitle: "Ajouter un rendez-vous",
        svcAddText: "Enregistrez une audience ou une échéance manuellement.",
        svcTeamTitle: "Inviter un collègue",
        svcTeamText: "Ajoutez vos collègues et attribuez-leur dates et tâches.",
        svcTelegramTitle: "Connecter Telegram",
        svcTelegramText: "Recevez chaque rappel sur Telegram avant l'échéance.",
        svcCalendarTitle: "Connecter l'agenda",
        svcCalendarText: "Reliez vos dates à Google, Apple ou Outlook en un clic.",
        tabCalendar: "Calendrier",
        filterAllTrackers: "Tous les suivis",
        filterAllStatuses: "Tous les statuts",
        searchPlaceholder: "Rechercher dans les titres",
        statusOpen: "Ouvert",
        statusDone: "Terminé",
        statusCancelled: "Annulé",
        statusOverdue: "En retard",
        colTitle: "Titre",
        colTracker: "Suivi",
        colDue: "Échéance",
        colAssignee: "Responsable",
        colStatus: "Statut",
        colActions: "Actions",
        noItems: "Aucun élément correspondant.",
        noDue: "Sans échéance",
        noAssignee: "Non attribué",
        actionDone: "Terminer",
        actionReopen: "Rouvrir",
        actionEdit: "Modifier",
        actionDelete: "Supprimer",
        confirmDelete: "Supprimer cet élément ? Cette action est irréversible.",
        editTitle: "Modifier l'élément",
        addItemBtn: "+ Élément",
        addItemTitle: "Nouvel élément",
        fieldTitle: "Titre",
        fieldTracker: "Suivi",
        fieldDue: "Date et heure d'échéance",
        fieldCategory: "Catégorie",
        fieldAssignee: "Responsable",
        fieldStatus: "Statut",
        titlePlaceholder: "Titre de l'élément",
        categoryPlaceholder: "Catégorie (facultatif)",
        chooseTracker: "Choisir un suivi",
        save: "Enregistrer",
        add: "Ajouter",
        titleRequired: "Saisissez le titre de l'élément.",
        trackerRequired: "Choisissez d'abord un suivi.",
        newTrackerBtn: "+ Nouveau suivi",
        newTrackerPlaceholder: "Nom du suivi",
        trackerCreated: "Suivi créé.",
        trackerNameRequired: "Saisissez le nom du suivi.",
        noTrackersHint: "Aucun suivi pour le moment. Créez d'abord un suivi pour ajouter des éléments.",
        calPrev: "Mois précédent",
        calNext: "Mois suivant",
        calToday: "Aujourd'hui",
        calFilterAll: "Tout", calFilterCases: "Affaires", calFilterViolations: "Infractions", calFilterTasks: "Taches", calFilterDocs: "Documents",
        calGregorian: "Grégorien",
        calHijri: "Hégirien",
        daySun: "Dim",
        dayMon: "Lun",
        dayTue: "Mar",
        dayWed: "Mer",
        dayThu: "Jeu",
        dayFri: "Ven",
        daySat: "Sam",
        month1: "Janvier",
        month2: "Février",
        month3: "Mars",
        month4: "Avril",
        month5: "Mai",
        month6: "Juin",
        month7: "Juillet",
        month8: "Août",
        month9: "Septembre",
        month10: "Octobre",
        month11: "Novembre",
        month12: "Décembre",
        moreItems: "{n} autres éléments",
        icsTitle: "Lien du calendrier (ICS)",
        icsHint: "Ajoutez ce lien à Apple Calendar, Google Agenda ou Outlook comme abonnement à un calendrier (par URL) pour que les échéances de vos éléments apparaissent automatiquement et restent à jour.",
        copy: "Copier le lien",
        copied: "Lien copié.",
        regenerate: "Régénérer le lien",
        confirmRegenerate: "Le lien actuel cessera de fonctionner et vous devrez ajouter le nouveau lien à votre calendrier. Continuer ?",
        regenerated: "Un nouveau lien a été généré.",
        icsSecret: "Ce lien est personnel. Ne le partagez pas.",
        itemDone: "Élément marqué comme terminé.",
        itemReopened: "Élément rouvert.",
        itemAdded: "Élément ajouté.",
        copyrightLine2: "Tous droits réservés",
        aboutLink: "À propos",
        termsLink: "Conditions d'utilisation",
        pricingLink: "Forfaits et tarifs",
        privacyLink: "Politique de confidentialité",
        loginLink: "Connexion",
        dashboardLink: "Tableau de bord",
        contactLink: "Contactez-nous",
        language: "Langue",
        appearance: "Apparence",
        light: "Clair",
        dark: "Sombre"
      },
      ur: {
        exportXlsx: "ایکسل ایکسپورٹ",
        exportBtn: "ایکسپورٹ",
        caseFileTitle: "مقدمے کی فائل",
        caseFileEmpty: "اس مقدمے کے تحت ابھی کچھ نہیں۔",
        secSessions: "سماعتیں",
        secRulings: "فیصلے",
        secExecutions: "نفاذ کی درخواستیں",
        secViolations: "خلاف ورزیاں",
        secTasks: "کام",
        secDocuments: "دستاویزات",
        fieldCourt: "عدالت",
        fieldStage: "مرحلہ",
        openCaseFile: "مقدمے کی فائل",
        appName: "TheTracker",
        exportCsv: "CSV برآمد",
        title: "ڈیش بورڈ",
        loading: "لوڈ ہو رہا ہے...",
        serviceUnavailableTitle: "سروس تیار کی جا رہی ہے",
        serviceUnavailableText: "ہم سروس تیار کر رہے ہیں، براہ کرم بعد میں دوبارہ کوشش کریں۔",
        noOrg: "کوئی کمپنی منتخب نہیں، پہلے اپنی کمپنی بنائیں۔",
        planLimitItems: "آپ اپنے موجودہ پلان میں آئٹمز کی حد تک پہنچ چکے ہیں، مزید شامل کرنے کے لیے پلان اپ گریڈ کریں۔",
        planLimitMembers: "آپ اپنے موجودہ پلان میں اراکین کی حد تک پہنچ چکے ہیں، مزید شامل کرنے کے لیے پلان اپ گریڈ کریں۔",
        planLimitLink: "پلانز اور قیمتیں دیکھیں",
        genericError: "کچھ غلط ہو گیا، براہ کرم دوبارہ کوشش کریں۔",
        errorLoad: "ڈیٹا لوڈ نہیں ہو سکا، براہ کرم دوبارہ کوشش کریں۔",
        saved: "محفوظ ہو گیا۔",
        deleted: "حذف ہو گیا۔",
        companyLabel: "کمپنی:",
        switchOrg: "کمپنی تبدیل کریں",
        newOrgBtn: "+ نئی کمپنی",
        renameOrgBtn: "نام بدلیں",
        deleteOrgBtn: "کمپنی حذف کریں",
        orgRenamed: "کمپنی کا نام تبدیل ہو گیا۔",
        deleteOrgConfirm: "«{name}» اور اس کے تمام آئٹمز مستقل طور پر حذف ہو جائیں گے۔ جاری رکھیں؟",
        newOrgPlaceholder: "ادارے کا نام",
        selfNamePlaceholder: "آپ کا پورا نام",
        newOrgSubmit: "بنائیں",
        cancel: "منسوخ کریں",
        createOrgTitle: "اپنا اکاؤنٹ شروع کریں",
        createOrgIntro: "اکاؤنٹ کی قسم منتخب کریں: کمپنی، ادارہ، فری لانس اجازت، یا ذاتی کاغذات ترتیب دینے والا فرد۔",
        packPickLine: "اپنے کام کے مطابق انٹرفیس منتخب کریں۔",
        packChoose: "منتخب کریں",
        orgCreated: "کمپنی بن گئی۔",
        orgNameRequired: "کمپنی کا نام درج کریں۔",
        linkImport: "فائل امپورٹ کریں",
        linkTeam: "ٹیم",
        linkSettings: "ترتیبات",
        linkAdmin: "پلیٹ فارم انتظامیہ",
        signOut: "سائن آؤٹ",
        statOpen: "کھلے آئٹمز",
        statDue7: "7 دنوں میں واجب",
        statOverdue: "تاخیر شدہ",
        statDone: "مکمل",
        tabList: "فہرست",
        timelineTitle: "آپ کی کارکردگی",
        tlNow: "اب",
        tlPrev: "پچھلا سنگ میل",
        tlNext: "اگلا سنگ میل",
        tlEventOf: "واقعہ {i} از {n}",
        timelineEmpty: "ابھی کوئی سرگرمی نہیں — فائل درآمد کریں یا وقت شامل کریں۔",
        tlCreated: "آئٹم شامل",
        tlDone: "مکمل",
        tlImport: "فائل درآمد",
        tlAttachment: "فائل اپ لوڈ",
        tlMember: "رکن شامل",
        tlPlan: "سبسکرپشن",
        tlToday: "آج",
        tlYesterday: "کل",
        tlDaysAgo: "{n} دن پہلے",
        achDoneMonth: "اس مہینے مکمل",
        achItems: "کل آئٹمز",
        achFiles: "فائلیں",
        achImports: "درآمدات",
        colVNumber: "خلاف ورزی نمبر",
        colCaseNumber: "مقدمہ نمبر",
        caseBundleTitle: "مقدمہ فائل {n}",
        caseBundleEmpty: "اس نمبر سے کچھ منسلک نہیں۔",
        colVDate: "خلاف ورزی کی تاریخ",
        colClient: "کمپنی",
        colIssuer: "جاری کنندہ",
        colAmount: "رقم",
        colVType: "قسم",
        colObjection: "اعتراض کی حالت",
        colPayDue: "ادائیگی کی تاریخ",
        allClients: "تمام کمپنیاں",
        totalCount: "خلاف ورزیاں",
        totalAmount: "کل رقم",
        totalUnpaid: "غیر ادا شدہ",
        totalOverdue: "مدت گزر گئی",
        attachTitle: "منسلکات",
        attachDrive: "گوگل ڈرائیو سے چنیں",
        attachUpload: "فائل اپ لوڈ کریں (PDF یا Word)",
        attachLinkPlaceholder: "یا گوگل ڈرائیو لنک چسپاں کریں",
        attachLinkBtn: "لنک شامل کریں",
        attachEmpty: "اس آئٹم کے لیے کوئی منسلک نہیں۔",
        attachUploading: "اپ لوڈ ہو رہا ہے...",
        attachDone: "شامل ہو گیا۔",
        attachFailed: "فائل اپ لوڈ نہیں ہو سکی۔",
        attachLimit: "آپ کے پیکج کی اسٹوریج ختم ہو گئی۔",
        attachDeleteConfirm: "منسلک مستقل حذف کریں؟",
        attachLinkLabel: "بیرونی لنک",
        delete: "حذف",
        chartTitle: "خلاف ورزیوں کا اشاریہ",
        indicatorsTitle: "خلاف ورزیوں اور سماعتوں کے اشاریے",
        courtsTitle: "مقدمات {n} (عدالت کے مطابق)",
        cancelledAmount: "منسوخ جرمانوں کی رقم",
        noCourtData: "عدالت کا ڈیٹا موجود نہیں۔",
        chartTotal: "کل خلاف ورزیاں",
        chartObjected: "اعتراض شدہ",
        chartCourt: "عدالت میں",
        chartRepeated: "بار بار کی خلاف ورزیاں",
        casesIndicatorsTitle: "مقدمات کے موجودہ اشاریے",
        casesChartTitle: "مقدمات کا اشاریہ",
        caseTotal: "کل مقدمات",
        caseOpen: "جاری مقدمات",
        caseOverdue: "تاخیر شدہ",
        caseDone: "مکمل مقدمات",
        clientsTitle: "کلائنٹس {n} (کلائنٹ کے مطابق)",
        noClientData: "کلائنٹ کا ڈیٹا موجود نہیں۔",
        caseAmount: "مقدمات کی کل رقم",
        caseDoneAmount: "مکمل مقدمات کی رقم",
        viewCases: "مقدمات ڈیش بورڈ",
        viewExpenses: "آپریٹنگ اخراجات",
        colExpDate: "تاریخ",
        colExpCat: "مد",
        colExpDesc: "تفصیل",
        colExpVendor: "وصول کنندہ",
        colExpMethod: "ادائیگی کا طریقہ",
        allCats: "تمام مدات",
        allYears: "تمام سال",
        expCount: "اخراجات",
        expTotal: "کل خرچ",
        expPaid: "ادا شدہ",
        expDue: "واجب الادا",
        expOverdue: "تاخیر شدہ",
        expAvgMonth: "ماہانہ اوسط",
        expIndicatorsTitle: "اخراجات کے اشاریے",
        expMonthlyTitle: "ماہانہ خرچ ({y})",
        expByCatTitle: "مد کے حساب سے ({n})",
        noExpenseData: "ابھی کوئی رقم درج نہیں",
        expNoCat: "بغیر مد",
        expStatusPaid: "ادا شدہ",
        expActionPay: "ادا شدہ نشان زد کریں",
        fieldAmount: "رقم",
        fieldClient: "فریق یا کلائنٹ",
        fieldClientEn: "فریق یا کلائنٹ انگریزی میں",
        appealDeadline: "اپیل کی مہلت",
        appealTitle: "اپیل کی مہلت — {case}",
        appealCategory: "اپیل کی مہلت",
        nextSession: "اگلی سماعت",
        nextSessionTitle: "سماعت — {case}",
        sessionCategory: "سماعت",
        weekTitle: "اس ہفتے کا خلاصہ",
        weekDone: "اس ہفتے مکمل",
        weekAdded: "اس ہفتے شامل",
        weekLate: "اس ہفتے تاخیر",
        weekSame: "پچھلے ہفتے جیسا",
        weekVsLast: "پچھلے ہفتے کے مقابلے",
        colNumber: "نمبر",
        fieldRemind: "پہلے یاد دلائیں",
        remindDefault: "رجسٹر کے قاعدے کے مطابق",
        remindDay: "ایک دن",
        remind3Days: "تین دن",
        remindWeek: "ایک ہفتہ",
        remind2Weeks: "دو ہفتے",
        remindMonth: "ایک مہینہ",
        fieldCaseNumber: "فائل نمبر",
        viewViolations: "خلاف ورزیاں ڈیش بورڈ",
        servicesTitle: "خدمات",
        calendarCardTitle: "کیلنڈر اور سماعتیں",
        startService: "خدمت شروع کریں",
        svcImportTitle: "ایکسل سے درآمد",
        svcImportText: "اپنے شیڈول یا معاہدوں کو منٹ میں ٹریک شدہ آئٹمز میں بدلیں۔",
        svcAddTitle: "نیا وقت شامل کریں",
        svcAddText: "سماعت یا مقررہ تاریخ خود درج کریں۔",
        svcTeamTitle: "ساتھی کو مدعو کریں",
        svcTeamText: "ساتھیوں کو شامل کریں اور تاریخیں و کام تفویض کریں۔",
        svcTelegramTitle: "ٹیلیگرام جوڑیں",
        svcTelegramText: "ہر یاد دہانی وقت سے پہلے ٹیلیگرام پر پائیں۔",
        svcCalendarTitle: "کیلنڈر جوڑیں",
        svcCalendarText: "اپنی تاریخیں ایک کلک میں گوگل، ایپل یا آؤٹ لک سے جوڑیں۔",
        tabCalendar: "کیلنڈر",
        filterAllTrackers: "تمام ٹریکرز",
        filterAllStatuses: "تمام حالتیں",
        searchPlaceholder: "عنوانات میں تلاش کریں",
        statusOpen: "کھلا",
        statusDone: "مکمل",
        statusCancelled: "منسوخ",
        statusOverdue: "تاخیر شدہ",
        colTitle: "عنوان",
        colTracker: "ٹریکر",
        colDue: "آخری تاریخ",
        colAssignee: "ذمہ دار",
        colStatus: "حالت",
        colActions: "کارروائیاں",
        noItems: "کوئی مطابقت رکھنے والا آئٹم نہیں۔",
        noDue: "بغیر تاریخ",
        noAssignee: "غیر متعین",
        actionDone: "مکمل کریں",
        actionReopen: "دوبارہ کھولیں",
        actionEdit: "ترمیم",
        actionDelete: "حذف کریں",
        confirmDelete: "کیا آپ یہ آئٹم حذف کرنا چاہتے ہیں؟ اسے واپس نہیں کیا جا سکتا۔",
        editTitle: "آئٹم میں ترمیم",
        addItemBtn: "+ آئٹم",
        addItemTitle: "نیا آئٹم",
        fieldTitle: "عنوان",
        fieldTracker: "ٹریکر",
        fieldDue: "آخری تاریخ اور وقت",
        fieldCategory: "زمرہ",
        fieldAssignee: "ذمہ دار",
        fieldStatus: "حالت",
        titlePlaceholder: "آئٹم کا عنوان",
        categoryPlaceholder: "زمرہ (اختیاری)",
        chooseTracker: "ٹریکر منتخب کریں",
        save: "محفوظ کریں",
        add: "شامل کریں",
        titleRequired: "آئٹم کا عنوان درج کریں۔",
        trackerRequired: "پہلے ٹریکر منتخب کریں۔",
        newTrackerBtn: "+ نیا ٹریکر",
        newTrackerPlaceholder: "ٹریکر کا نام",
        trackerCreated: "ٹریکر بن گیا۔",
        trackerNameRequired: "ٹریکر کا نام درج کریں۔",
        noTrackersHint: "ابھی کوئی ٹریکر نہیں، آئٹمز شامل کرنے کے لیے پہلے ٹریکر بنائیں۔",
        calPrev: "پچھلا مہینہ",
        calNext: "اگلا مہینہ",
        calToday: "آج",
        calFilterAll: "سب", calFilterCases: "مقدمات", calFilterViolations: "خلاف ورزیاں", calFilterTasks: "کام", calFilterDocs: "دستاویزات",
        calGregorian: "عیسوی",
        calHijri: "ہجری",
        daySun: "اتوار",
        dayMon: "پیر",
        dayTue: "منگل",
        dayWed: "بدھ",
        dayThu: "جمعرات",
        dayFri: "جمعہ",
        daySat: "ہفتہ",
        month1: "جنوری",
        month2: "فروری",
        month3: "مارچ",
        month4: "اپریل",
        month5: "مئی",
        month6: "جون",
        month7: "جولائی",
        month8: "اگست",
        month9: "ستمبر",
        month10: "اکتوبر",
        month11: "نومبر",
        month12: "دسمبر",
        moreItems: "{n} مزید آئٹمز",
        icsTitle: "کیلنڈر لنک (ICS)",
        icsHint: "اس لنک کو Apple، Google یا Outlook کیلنڈر میں سبسکرپشن (URL کے ذریعے) کے طور پر شامل کریں تاکہ آپ کے آئٹمز کی تاریخیں خود بخود ظاہر ہوں اور اپ ڈیٹ رہیں۔",
        copy: "لنک کاپی کریں",
        copied: "لنک کاپی ہو گیا۔",
        regenerate: "نیا لنک بنائیں",
        confirmRegenerate: "موجودہ لنک کام کرنا بند کر دے گا اور آپ کو نیا لنک اپنے کیلنڈر میں شامل کرنا ہوگا۔ جاری رکھیں؟",
        regenerated: "نیا لنک بن گیا۔",
        icsSecret: "یہ لنک ذاتی ہے، اسے دوسروں کے ساتھ شیئر نہ کریں۔",
        itemDone: "آئٹم مکمل کر دیا گیا۔",
        itemReopened: "آئٹم دوبارہ کھول دیا گیا۔",
        itemAdded: "آئٹم شامل کر دیا گیا۔",
        copyrightLine2: "جملہ حقوق محفوظ ہیں",
        aboutLink: "ہمارے بارے میں",
        termsLink: "استعمال کی شرائط",
        pricingLink: "پلانز اور قیمتیں",
        privacyLink: "رازداری کی پالیسی",
        loginLink: "سائن ان",
        dashboardLink: "ڈیش بورڈ",
        contactLink: "ہم سے رابطہ کریں",
        language: "زبان",
        appearance: "ظہور",
        light: "روشن",
        dark: "اندھیرا"
      }
    };

