    const translations = {
      ar: {
        exportXlsx: "إكسل",
        colLikelihood: "الاحتمال",
        colImpact: "الأثر",
        colResLikelihood: "الاحتمال بعد المعالجة",
        colResImpact: "الأثر بعد المعالجة",
        fCase: "القضية",
        title: "إدارة المخاطر",
        regTitle: "سجل المخاطر",
        heatTitle: "خريطة المخاطر",
        regIntro: "ما الذي قد يضر عملاءك وقضاياك؟ سجل الخطر، قدر احتماله وأثره قبل المعالجة وبعدها، وحدد الإجراءات وستتابعها التنبيهات.",
        newRisk: "＋ خطر جديد",
        exportCsv: "CSV",
        exportBtn: "تصدير",
        inherent: "قبل المعالجة",
        residual: "بعد المعالجة",
        clearCell: "إلغاء التحديد",
        likelihood: "الاحتمال",
        impact: "الأثر",
        colCode: "الرمز",
        colTitle: "الخطر",
        colCategory: "التصنيف",
        colClient: "العميل",
        colCase: "الدعوى",
        colOwner: "المسؤول",
        colInherent: "قبل المعالجة",
        colResidual: "بعد المعالجة",
        colStrategy: "الاستراتيجية",
        colStatus: "الحالة",
        colReview: "المراجعة",
        regEmpty: "لا مخاطر مسجلة بعد.",
        editorNew: "خطر جديد",
        editorEdit: "تعديل الخطر",
        fTitle: "عنوان الخطر",
        fCategory: "التصنيف",
        fClient: "العميل / الشركة",
        fProcess: "الإجراء المرتبط",
        fOwner: "المسؤول",
        fIdentified: "تاريخ الرصد",
        fReview: "تاريخ المراجعة",
        fDescription: "الوصف",
        fRootCause: "السبب الجذري",
        fConsequences: "العواقب",
        fControls: "الضوابط الحالية",
        assessTitle: "التقييم",
        fLikelihood: "الاحتمال قبل المعالجة",
        fImpact: "الأثر قبل المعالجة",
        fResLikelihood: "الاحتمال بعد المعالجة",
        fResImpact: "الأثر بعد المعالجة",
        fStrategy: "الاستراتيجية",
        fStatus: "الحالة",
        planTitle: "خطة المعالجة",
        addAction: "＋ إجراء معالجة",
        planHint: "كل إجراء له تاريخ استحقاق يضاف تلقائيا للمتابعة والتنبيهات عند الحفظ.",
        actionTitle: "الإجراء",
        done: "منجز",
        riskActionCategory: "معالجة خطر",
        kpiTotal: "إجمالي المخاطر",
        kpiOpen: "مفتوحة",
        kpiCritical: "حرجة",
        kpiReviewOverdue: "تجاوزت المراجعة",
        kpiActions: "إجراءات معلقة",
        notScored: "غير مقيم",
        choose: "اختر",
        none: "—",
        band_low: "منخفض",
        band_moderate: "متوسط",
        band_high: "مرتفع",
        band_critical: "حرج",
        L1: "نادر",
        L2: "غير محتمل",
        L3: "ممكن",
        L4: "محتمل",
        L5: "شبه مؤكد",
        I1: "طفيف",
        I2: "محدود",
        I3: "ملموس",
        I4: "كبير",
        I5: "كارثي",
        cat_legal: "قانوني",
        cat_procedural: "إجرائي (مواعيد وآجال)",
        cat_financial: "مالي (غرامات ومبالغ)",
        cat_compliance: "امتثال وتراخيص",
        cat_reputation: "سمعة",
        cat_operational: "تشغيلي",
        strat_mitigate: "تخفيف",
        strat_accept: "قبول",
        strat_transfer: "نقل",
        strat_avoid: "تجنب",
        rstatus_open: "مفتوح",
        rstatus_in_progress: "قيد المعالجة",
        rstatus_monitoring: "تحت المراقبة",
        rstatus_closed: "مغلق",
        allStatuses: "كل الحالات",
        edit: "تعديل",
        save: "حفظ",
        cancel: "إلغاء",
        saveFailed: "تعذر الحفظ.",
        deleteConfirm: "حذف هذا الخطر نهائيا؟",
        docAddTitle: "إضافة مستند",
        docAddIntro: "ارفع السجل التجاري أو الشهادة الضريبية أو الرخصة أو صحيفة الدعوى أو أي مستند (PDF أو صورة)، وسيقرأه النظام ويستخرج نوعه ورقمه وتاريخ انتهائه ويضيفه للمتابعة والتنبيه تلقائيا.",
        docDropHint: "اسحب المستند هنا أو اختر ملفا",
        docChoose: "اختيار ملف",
        docKind: "نوع المستند",
        docTitleField: "العنوان",
        docNumber: "رقم المستند",
        docIssuer: "الجهة المصدرة",
        docParty: "الشركة / صاحب المستند",
        docIssueDate: "تاريخ الإصدار",
        docExpiry: "تاريخ الانتهاء / الاستحقاق",
        docAmount: "المبلغ (<span class=\"sar-symbol\" aria-label=\"ريال سعودي\"></span>)",
        docCase: "رقم الدعوى",
        docCourt: "المحكمة",
        docSave: "حفظ وإضافة للمتابعة",
        docListTitle: "مستندات الشركة",
        docLeft: "المتبقي",
        docFiles: "الملفات",
        docsEmpty: "لا مستندات بعد.",
        docReading: "جاري قراءة المستند...",
        docOcr: "المستند صورة، جاري قراءته بالذكاء الاصطناعي...",
        docReady: "قرأت المستند — راجع الحقول ثم احفظ.",
        docFailed: "تعذر قراءة المستند، جرب ملفا أوضح.",
        docSaving: "جاري الحفظ...",
        docSaved: "حفظ المستند وأضيف للمتابعة والتنبيه.",
        docFileFailed: "حفظت البيانات لكن تعذر رفع الملف.",
        docStorageLimit: "حفظت البيانات لكن مساحة التخزين في باقتك ممتلئة.",
        docExpired: "منته",
        docDays: "يوما",
        docDeleteConfirm: "حذف المستند وملفاته نهائيا؟",
        allKinds: "كل الأنواع",
        search: "بحث",
        actions: "الإجراءات",
        delete: "حذف",
        unavailable: "الخدمة غير متاحة الآن.",
        kind_commercial_register: "سجل تجاري",
        kind_vat_certificate: "شهادة ضريبية",
        kind_license: "رخصة",
        kind_contract: "عقد",
        kind_case_filing: "صحيفة دعوى / مرفوعات",
        kind_court_ruling: "حكم قضائي",
        kind_hearing_notice: "إشعار جلسة",
        kind_violation: "مخالفة",
        kind_invoice: "فاتورة",
        kind_power_of_attorney: "وكالة",
        kind_id_document: "هوية / إقامة",
        kind_other: "مستند آخر",
        intro: "أضف أعضاء فريقك وحدد أدوارهم، وتابع الدعوات المعلقة.",
        backBtn: "العودة إلى لوحة التحكم",
        serviceUnavailableTitle: "الخدمة قيد التجهيز",
        serviceUnavailableText: "نعمل حاليا على تجهيز الخدمة، حاول مرة أخرى لاحقا.",
        noOrg: "لا توجد شركة محددة، أنشئ شركتك أولا.",
        noOrgHint: "انتقل إلى لوحة التحكم لإنشاء شركتك ثم عد إلى هذه الصفحة.",
        loading: "جاري التحميل...",
        loadError: "تعذر تحميل بيانات الفريق، حاول مرة أخرى.",
        membersTitle: "أعضاء الفريق",
        membersEmpty: "لا يوجد أعضاء بعد.",
        readOnlyNote: "يمكن للمالك والمشرفين فقط إدارة الأعضاء والدعوات.",
        capacityLimited: "الأعضاء: {used} من {limit}",
        capacityUnlimited: "الأعضاء: {used} (بلا حد)",
        capacityPending: "الدعوات المعلقة: {n}",
        capacityFull: "وصلت إلى الحد الأقصى لعدد الأعضاء في باقتك الحالية.",
        upgradeLink: "ترقية الباقة",
        roleOwner: "المالك",
        roleAdmin: "مشرف",
        roleMember: "عضو",
        roleLabel: "الدور",
        statusInvited: "بانتظار الانضمام",
        you: "أنت",
        emailLabel: "البريد الإلكتروني",
        joinedLabel: "تاريخ الانضمام",
        changeRoleLabel: "تغيير الدور",
        removeBtn: "إزالة",
        confirmRemove: "هل تريد إزالة {name} من الفريق؟",
        memberRemoved: "تمت إزالة العضو.",
        roleUpdated: "تم تحديث الدور.",
        inviteTitle: "دعوة عضو جديد",
        inviteIntro: "أدخل البريد الإلكتروني للعضو واختر دوره. إن كان مسجلا في المنصة وصله تنبيه في جرس التنبيهات فورا، وينضم إلى الفريق عند فتحه التطبيق. وإن لم يكن مسجلا فأرسل له رابط تسجيل الدخول:",
        copyLinkBtn: "نسخ رابط تسجيل الدخول",
        linkCopied: "تم نسخ الرابط.",
        inviteEmailPlaceholder: "بريد العضو الإلكتروني",
        inviteBtn: "دعوة",
        lookupTitle: "أو من المسجلين في المنصة",
        inviteByEmailTitle: "بالبريد الإلكتروني",
        lookupBtn: "عرض المستخدمين",
        lookupPlaceholder: "بريد أو جوال أو رقم مستخدم",
        lookupNone: "لا يوجد مستخدم مطابق. تستطيع دعوته ببريده مباشرة.",
        inviteSending: "جاري الإضافة...",
        inviteCreated: "أضيفت الدعوة ل {email}، وسينضم تلقائيا عند تسجيل دخوله.",
        workloadTitle: "توزيع الأعمال",
        workloadIntro: "اسحب العمل إلى العضو.",
        rasiTitle: "مصفوفة RASI",
        rasiIntro: "لكل قضية أو مخالفة أو مهمة: من ينفذ (R)، من يعتمد ويساءل (A — واحد فقط)، من يساند (S)، ومن يبلغ (I). اضغط الخلية لتبديل الدور، ويصل صاحبه تنبيه فورا.",
        rasiLegendR: "المنفذ المسؤول",
        rasiLegendA: "المعتمد والمساءل",
        rasiLegendS: "المساند",
        rasiLegendI: "المبلغ",
        rasiSearch: "ابحث بالعنوان أو الرقم",
        rasiEmpty: "لا عناصر مفتوحة لعرضها.",
        rasiItemCol: "العنصر",
        rasiSaved: "حفظ الدور.",
        rasiNoMembers: "أضف أعضاء إلى الفريق أولا.",
        quickTitle: "توزيع سريع",
        quickHint: "اضغط اسم العضو على العنصر: ضغطة واحدة = هو المنفذ المسؤول (R) وأنت المعتمد (A) تلقائيا، ضغطة ثانية = مساند (S)، ثالثة = إزالة.",
        rasiShowMatrix: "عرض المصفوفة الكاملة",
        rasiHideMatrix: "إخفاء المصفوفة",
        quickAddTitle: "إدخال سريع",
        quickAddHint: "اكتب المهمة كما تقولها: «جلسة القضية 4521 لشركة الأبراج الأحد 10 صباحا لأحمد» — يفهم النوع والموعد والعميل ورقم الدعوى ومن ينفذ، ويسجل ويوزع بضغطة واحدة.",
        quickAddBtn: "إضافة",
        quickAddPh: "اكتب المهمة ومن ينفذها وموعدها…",
        quickAddNobody: "بلا منفذ (أنا لاحقا)",
        quickAddParsing: "جاري الفهم…",
        quickAddDone: "سجلت «{title}»{who}.",
        quickAddNoTitle: "لم أفهم مهمة من هذا النص — اكتب عنوانها على الأقل.",
        quickAddNeedsParent: "لأي قضية أو مخالفة تتبع هذه المهمة؟ — لا مهمة بلا أصل.",
        quickAddLink: "اربط وسجل",
        unassignedTitle: "أعمال غير مسندة",
        unassignedEmpty: "كل الأعمال مسندة.",
        wlOpen: "جارية",
        wlOverdue: "متأخرة",
        wlDone: "منتهية",
        assignTo: "أسند إلى",
        assignPick: "اختر عضوا",
        assignDone: "أسند العمل إلى {name}.",
        unassign: "غير مسندة",
        noDue: "بلا موعد",
        chatTitle: "تواصل الفريق",
        chatThreads: "المحادثات",
        chatTeam: "الفريق كله",
        chatTeamHint: "اكتب للكل",
        chatPrivate: "خاص",
        chatPlaceholder: "اكتب رسالتك... (Enter للإرسال، Shift+Enter لسطر جديد)",
        chatSend: "إرسال",
        chatSendFile: "إرسال الملف",
        chatCancel: "إلغاء",
        chatFiles: "📁 الملفات",
        chatFilesEmpty: "لا ملفات في هذه المحادثة بعد.",
        chatDownload: "تنزيل",
        chatFileNoLink: "بلا ربط بقضية",
        chatFileTooBig: "الملف أكبر من 25 ميغابايت.",
        chatUploading: "جاري رفع الملف…",
        chatEmpty: "لا رسائل بعد.",
        chatLoadError: "تعذر تحميل الرسائل.",
        chatDelete: "حذف",
        chatConfirmDelete: "حذف هذه الرسالة؟",
        chatUnread: "{n} جديدة",
        chatToday: "اليوم",
        chatLive: "متصل",
        chatOffline: "يعاد الاتصال...",
        invitationsTitle: "الدعوات المعلقة",
        invitationsEmpty: "لا توجد دعوات معلقة.",
        invitedOn: "أضيفت في {date}",
        cancelInviteBtn: "إلغاء",
        confirmCancelInvite: "هل تريد إلغاء دعوة {email}؟",
        inviteCancelled: "ألغيت الدعوة.",
        invalidEmail: "أدخل بريدا إلكترونيا صحيحا.",
        alreadyMember: "هذا البريد عضو في الفريق بالفعل.",
        alreadyInvited: "توجد دعوة معلقة لهذا البريد بالفعل.",
        notAllowed: "ليست لديك صلاحية لتنفيذ هذا الإجراء.",
        genericError: "حدث خطأ، حاول مرة أخرى.",
        planLimitMembers: "وصلت إلى الحد الأقصى لعدد الأعضاء في باقتك الحالية، رق باقتك لإضافة المزيد.",
        copyrightLine2: "جميع الحقوق محفوظة",
        aboutLink: "من نحن",
        termsLink: "شروط الاستخدام",
        pricingLink: "الباقات والأسعار",
        privacyLink: "سياسة الخصوصية",
        loginLink: "تسجيل الدخول",
        dashboardLink: "لوحة التحكم",
        contactLink: "تواصل معنا",
        language: "اللغة",
        appearance: "المظهر",
        light: "فاتح",
        dark: "داكن"
      },
      en: {
        exportXlsx: "Excel",
        colLikelihood: "Likelihood",
        colImpact: "Impact",
        colResLikelihood: "Residual likelihood",
        colResImpact: "Residual impact",
        fCase: "Case",
        title: "Risk management",
        regTitle: "Risk register",
        heatTitle: "Risk map",
        regIntro: "Legal risks across the firm's clients and cases: likelihood × impact, treatment, and actions tied to reminders.",
        newRisk: "＋ New risk",
        exportCsv: "CSV",
        exportBtn: "Export",
        inherent: "Before treatment",
        residual: "After treatment",
        clearCell: "Clear selection",
        likelihood: "Likelihood",
        impact: "Impact",
        colCode: "Code",
        colTitle: "Risk",
        colCategory: "Category",
        colClient: "Client",
        colCase: "Case",
        colOwner: "Owner",
        colInherent: "Before",
        colResidual: "After",
        colStrategy: "Strategy",
        colStatus: "Status",
        colReview: "Review",
        regEmpty: "No risks yet.",
        editorNew: "New risk",
        editorEdit: "Edit risk",
        fTitle: "Risk title",
        fCategory: "Category",
        fClient: "Client / company",
        fProcess: "Linked procedure",
        fOwner: "Owner",
        fIdentified: "Identified on",
        fReview: "Review date",
        fDescription: "Description",
        fRootCause: "Root cause",
        fConsequences: "Consequences",
        fControls: "Existing controls",
        assessTitle: "Assessment",
        fLikelihood: "Likelihood before treatment",
        fImpact: "Impact before treatment",
        fResLikelihood: "Likelihood after treatment",
        fResImpact: "Impact after treatment",
        fStrategy: "Strategy",
        fStatus: "Status",
        planTitle: "Treatment plan",
        addAction: "＋ Treatment action",
        planHint: "Every action with a due date is added to tracking and reminders when you save.",
        actionTitle: "Action",
        done: "Done",
        riskActionCategory: "Risk treatment",
        kpiTotal: "Total risks",
        kpiOpen: "Open",
        kpiCritical: "Critical",
        kpiReviewOverdue: "Review overdue",
        kpiActions: "Pending actions",
        notScored: "Not scored",
        choose: "Choose",
        none: "—",
        band_low: "Low",
        band_moderate: "Moderate",
        band_high: "High",
        band_critical: "Critical",
        L1: "Rare",
        L2: "Unlikely",
        L3: "Possible",
        L4: "Likely",
        L5: "Almost certain",
        I1: "Minor",
        I2: "Limited",
        I3: "Moderate",
        I4: "Major",
        I5: "Severe",
        cat_legal: "Legal",
        cat_procedural: "Procedural (deadlines)",
        cat_financial: "Financial (fines)",
        cat_compliance: "Compliance & licensing",
        cat_reputation: "Reputational",
        cat_operational: "Operational",
        strat_mitigate: "Mitigate",
        strat_accept: "Accept",
        strat_transfer: "Transfer",
        strat_avoid: "Avoid",
        rstatus_open: "Open",
        rstatus_in_progress: "In progress",
        rstatus_monitoring: "Monitoring",
        rstatus_closed: "Closed",
        allStatuses: "All statuses",
        edit: "Edit",
        save: "Save",
        cancel: "Cancel",
        saveFailed: "Could not save.",
        deleteConfirm: "Delete this risk permanently?",
        docAddTitle: "Add a document",
        docAddIntro: "Upload a commercial register, VAT certificate, licence, statement of claim or any document (PDF or image); the system reads it, extracts its type, number and expiry, and adds it to tracking and reminders.",
        docDropHint: "Drop the document here or choose a file",
        docChoose: "Choose file",
        docKind: "Document type",
        docTitleField: "Title",
        docNumber: "Document number",
        docIssuer: "Issuer",
        docParty: "Company / holder",
        docIssueDate: "Issue date",
        docExpiry: "Expiry / due date",
        docAmount: "Amount (<span class=\"sar-symbol\" aria-label=\"ريال سعودي\"></span>)",
        docCase: "Case number",
        docCourt: "Court",
        docSave: "Save and track",
        docListTitle: "Company documents",
        docLeft: "Remaining",
        docFiles: "Files",
        docsEmpty: "No documents yet.",
        docReading: "Reading the document...",
        docOcr: "Image document — reading it with AI...",
        docReady: "Document read — review the fields and save.",
        docFailed: "Could not read the document; try a clearer file.",
        docSaving: "Saving...",
        docSaved: "Saved and added to tracking and reminders.",
        docFileFailed: "Data saved, but the file could not be uploaded.",
        docStorageLimit: "Data saved, but your plan storage is full.",
        docExpired: "Expired",
        docDays: "days",
        docDeleteConfirm: "Delete this document and its files permanently?",
        allKinds: "All types",
        search: "Search",
        actions: "Actions",
        delete: "Delete",
        unavailable: "Service unavailable right now.",
        kind_commercial_register: "Commercial register",
        kind_vat_certificate: "VAT certificate",
        kind_license: "Licence",
        kind_contract: "Contract",
        kind_case_filing: "Statement of claim / filing",
        kind_court_ruling: "Court ruling",
        kind_hearing_notice: "Hearing notice",
        kind_violation: "Violation",
        kind_invoice: "Invoice",
        kind_power_of_attorney: "Power of attorney",
        kind_id_document: "ID document",
        kind_other: "Other document",
        intro: "Add your team members, set their roles, and follow up on pending invitations.",
        backBtn: "Back to Dashboard",
        serviceUnavailableTitle: "Service is being prepared",
        serviceUnavailableText: "We are setting up the service. Please try again later.",
        noOrg: "No company selected. Create your company first.",
        noOrgHint: "Go to the dashboard to create your company, then come back to this page.",
        loading: "Loading...",
        loadError: "Could not load the team data. Please try again.",
        membersTitle: "Team members",
        membersEmpty: "No members yet.",
        readOnlyNote: "Only the owner and admins can manage members and invitations.",
        capacityLimited: "Members: {used} of {limit}",
        capacityUnlimited: "Members: {used} (unlimited)",
        capacityPending: "Pending invitations: {n}",
        capacityFull: "You have reached the member limit of your current plan.",
        upgradeLink: "Upgrade plan",
        roleOwner: "Owner",
        roleAdmin: "Admin",
        roleMember: "Member",
        roleLabel: "Role",
        statusInvited: "Awaiting sign-in",
        you: "You",
        emailLabel: "Email",
        joinedLabel: "Joined on",
        changeRoleLabel: "Change role",
        removeBtn: "Remove",
        confirmRemove: "Remove {name} from the team?",
        memberRemoved: "Member removed.",
        roleUpdated: "Role updated.",
        inviteTitle: "Invite a new member",
        inviteIntro: "Enter the member's email and choose a role. If they are registered on the platform they get a notification in the bell right away, and they join the team the next time they open the app. Otherwise, send them the sign-in link:",
        copyLinkBtn: "Copy sign-in link",
        linkCopied: "Link copied.",
        inviteEmailPlaceholder: "Member's email address",
        inviteBtn: "Invite",
        lookupTitle: "Or from registered users",
        inviteByEmailTitle: "By email",
        lookupBtn: "Show users",
        lookupPlaceholder: "Email, mobile or user number",
        lookupNone: "No matching user. You can still invite them by email.",
        inviteSending: "Adding...",
        inviteCreated: "Invitation added for {email}. They will join automatically when they sign in.",
        workloadTitle: "Work distribution",
        workloadIntro: "Drag work onto a member.",
        rasiTitle: "RASI Matrix",
        rasiIntro: "For every case, violation or task: who does it (R), who approves and answers for it (A — exactly one), who supports (S), who is kept informed (I). Click a cell to cycle the role; the person is notified instantly.",
        rasiLegendR: "Responsible",
        rasiLegendA: "Approver / accountable",
        rasiLegendS: "Support",
        rasiLegendI: "Informed",
        rasiSearch: "Search by title or number",
        rasiEmpty: "No open items to show.",
        rasiItemCol: "Item",
        rasiSaved: "Role saved.",
        rasiNoMembers: "Add team members first.",
        quickTitle: "Quick distribution",
        quickHint: "Tap a member on an item: one tap = Responsible (R) with you as Approver (A) automatically, second tap = Support (S), third = remove.",
        rasiShowMatrix: "Show the full matrix",
        rasiHideMatrix: "Hide the matrix",
        quickAddTitle: "Quick entry",
        quickAddHint: "Type it the way you would say it: \"Hearing for case 4521, Al-Abraj, Sunday 10 AM, for Ahmad\" — kind, date, client, case number and who does it are understood, recorded and distributed in one tap.",
        quickAddBtn: "Add",
        quickAddPh: "Type the task, who does it and when…",
        quickAddNobody: "No responsible yet",
        quickAddParsing: "Understanding…",
        quickAddDone: "Recorded \"{title}\"{who}.",
        quickAddNoTitle: "I could not read a task from that — at least give it a title.",
        quickAddNeedsParent: "Which case or violation does this task belong to? — no task stands alone.",
        quickAddLink: "Link and record",
        unassignedTitle: "Unassigned work",
        unassignedEmpty: "All work is assigned.",
        wlOpen: "Open",
        wlOverdue: "Overdue",
        wlDone: "Done",
        assignTo: "Assign to",
        assignPick: "Pick a member",
        assignDone: "Assigned to {name}.",
        unassign: "Unassigned",
        noDue: "No due date",
        chatTitle: "Team chat",
        chatThreads: "Conversations",
        chatTeam: "Whole team",
        chatTeamHint: "Everyone",
        chatPrivate: "Private",
        chatPlaceholder: "Write a message... (Enter to send, Shift+Enter for a new line)",
        chatSend: "Send",
        chatSendFile: "Send file",
        chatCancel: "Cancel",
        chatFiles: "📁 Files",
        chatFilesEmpty: "No files in this conversation yet.",
        chatDownload: "Download",
        chatFileNoLink: "Not linked to a case",
        chatFileTooBig: "The file exceeds 25 MB.",
        chatUploading: "Uploading…",
        chatEmpty: "No messages yet.",
        chatLoadError: "Could not load messages.",
        chatDelete: "Delete",
        chatConfirmDelete: "Delete this message?",
        chatUnread: "{n} new",
        chatToday: "Today",
        chatLive: "Live",
        chatOffline: "Reconnecting...",
        invitationsTitle: "Pending invitations",
        invitationsEmpty: "No pending invitations.",
        invitedOn: "added on {date}",
        cancelInviteBtn: "Cancel",
        confirmCancelInvite: "Cancel the invitation for {email}?",
        inviteCancelled: "Invitation cancelled.",
        invalidEmail: "Enter a valid email address.",
        alreadyMember: "This email already belongs to a team member.",
        alreadyInvited: "There is already a pending invitation for this email.",
        notAllowed: "You do not have permission to perform this action.",
        genericError: "Something went wrong. Please try again.",
        planLimitMembers: "You have reached the member limit of your current plan. Upgrade to add more.",
        copyrightLine2: "All rights reserved",
        aboutLink: "About Us",
        termsLink: "Terms of Use",
        pricingLink: "Plans & Pricing",
        privacyLink: "Privacy Policy",
        loginLink: "Sign in",
        dashboardLink: "Dashboard",
        contactLink: "Contact Us",
        language: "Language",
        appearance: "Appearance",
        light: "Light",
        dark: "Dark"
      },
      fr: {
        exportXlsx: "Excel",
        colLikelihood: "Probabilité",
        colImpact: "Impact",
        colResLikelihood: "Probabilité résiduelle",
        colResImpact: "Impact résiduel",
        fCase: "Affaire",
        title: "Gestion des risques",
        regTitle: "Registre des risques",
        heatTitle: "Carte des risques",
        regIntro: "Risques juridiques des clients et dossiers : probabilité × impact, traitement et actions liées aux rappels.",
        newRisk: "＋ Nouveau risque",
        exportCsv: "CSV",
        exportBtn: "Exporter",
        inherent: "Avant traitement",
        residual: "Après traitement",
        clearCell: "Effacer la sélection",
        likelihood: "Probabilité",
        impact: "Impact",
        colCode: "Code",
        colTitle: "Risque",
        colCategory: "Catégorie",
        colClient: "Client",
        colCase: "Dossier",
        colOwner: "Responsable",
        colInherent: "Avant",
        colResidual: "Après",
        colStrategy: "Stratégie",
        colStatus: "Statut",
        colReview: "Revue",
        regEmpty: "Aucun risque.",
        editorNew: "Nouveau risque",
        editorEdit: "Modifier le risque",
        fTitle: "Titre",
        fCategory: "Catégorie",
        fClient: "Client / entreprise",
        fProcess: "Procédure liée",
        fOwner: "Responsable",
        fIdentified: "Identifié le",
        fReview: "Date de revue",
        fDescription: "Description",
        fRootCause: "Cause racine",
        fConsequences: "Conséquences",
        fControls: "Contrôles existants",
        assessTitle: "Évaluation",
        fLikelihood: "Probabilité avant traitement",
        fImpact: "Impact avant traitement",
        fResLikelihood: "Probabilité après traitement",
        fResImpact: "Impact après traitement",
        fStrategy: "Stratégie",
        fStatus: "Statut",
        planTitle: "Plan de traitement",
        addAction: "＋ Action",
        planHint: "Chaque action datée est ajoutée au suivi et aux rappels à l’enregistrement.",
        actionTitle: "Action",
        done: "Fait",
        riskActionCategory: "Traitement de risque",
        kpiTotal: "Risques",
        kpiOpen: "Ouverts",
        kpiCritical: "Critiques",
        kpiReviewOverdue: "Revue en retard",
        kpiActions: "Actions en attente",
        notScored: "Non évalué",
        choose: "Choisir",
        none: "—",
        band_low: "Faible",
        band_moderate: "Modéré",
        band_high: "Élevé",
        band_critical: "Critique",
        L1: "Rare",
        L2: "Improbable",
        L3: "Possible",
        L4: "Probable",
        L5: "Quasi certain",
        I1: "Mineur",
        I2: "Limité",
        I3: "Modéré",
        I4: "Majeur",
        I5: "Grave",
        cat_legal: "Juridique",
        cat_procedural: "Procédural (délais)",
        cat_financial: "Financier (amendes)",
        cat_compliance: "Conformité & licences",
        cat_reputation: "Réputation",
        cat_operational: "Opérationnel",
        strat_mitigate: "Atténuer",
        strat_accept: "Accepter",
        strat_transfer: "Transférer",
        strat_avoid: "Éviter",
        rstatus_open: "Ouvert",
        rstatus_in_progress: "En cours",
        rstatus_monitoring: "Sous surveillance",
        rstatus_closed: "Clos",
        allStatuses: "Tous les statuts",
        edit: "Modifier",
        save: "Enregistrer",
        cancel: "Annuler",
        saveFailed: "Enregistrement impossible.",
        deleteConfirm: "Supprimer ce risque ?",
        docAddTitle: "Ajouter un document",
        docAddIntro: "Téléversez un registre de commerce, une attestation TVA, une licence, une requête ou tout document (PDF ou image) ; le système le lit, en extrait le type, le numéro et l'échéance, et l'ajoute au suivi et aux rappels.",
        docDropHint: "Déposez le document ici ou choisissez un fichier",
        docChoose: "Choisir un fichier",
        docKind: "Type de document",
        docTitleField: "Titre",
        docNumber: "Numéro",
        docIssuer: "Émetteur",
        docParty: "Entreprise / titulaire",
        docIssueDate: "Date d'émission",
        docExpiry: "Expiration / échéance",
        docAmount: "Montant (<span class=\"sar-symbol\" aria-label=\"ريال سعودي\"></span>)",
        docCase: "Numéro de dossier",
        docCourt: "Tribunal",
        docSave: "Enregistrer et suivre",
        docListTitle: "Documents de l'entreprise",
        docLeft: "Restant",
        docFiles: "Fichiers",
        docsEmpty: "Aucun document.",
        docReading: "Lecture du document...",
        docOcr: "Document image — lecture par IA...",
        docReady: "Document lu — vérifiez les champs puis enregistrez.",
        docFailed: "Lecture impossible ; essayez un fichier plus net.",
        docSaving: "Enregistrement...",
        docSaved: "Enregistré et ajouté au suivi.",
        docFileFailed: "Données enregistrées, mais le fichier n’a pas pu être téléversé.",
        docStorageLimit: "Données enregistrées, mais le stockage de votre forfait est plein.",
        docExpired: "Expiré",
        docDays: "jours",
        docDeleteConfirm: "Supprimer ce document et ses fichiers ?",
        allKinds: "Tous les types",
        search: "Rechercher",
        actions: "Actions",
        delete: "Supprimer",
        unavailable: "Service indisponible.",
        kind_commercial_register: "Registre de commerce",
        kind_vat_certificate: "Attestation TVA",
        kind_license: "Licence",
        kind_contract: "Contrat",
        kind_case_filing: "Requête / dépôt",
        kind_court_ruling: "Jugement",
        kind_hearing_notice: "Avis d'audience",
        kind_violation: "Infraction",
        kind_invoice: "Facture",
        kind_power_of_attorney: "Procuration",
        kind_id_document: "Pièce d'identité",
        kind_other: "Autre document",
        intro: "Ajoutez les membres de votre équipe, définissez leurs rôles et suivez les invitations en attente.",
        backBtn: "Retour au tableau de bord",
        serviceUnavailableTitle: "Service en cours de préparation",
        serviceUnavailableText: "Nous préparons le service. Veuillez réessayer plus tard.",
        noOrg: "Aucune entreprise sélectionnée. Créez d'abord votre entreprise.",
        noOrgHint: "Rendez-vous sur le tableau de bord pour créer votre entreprise, puis revenez sur cette page.",
        loading: "Chargement...",
        loadError: "Impossible de charger les données de l'équipe. Veuillez réessayer.",
        membersTitle: "Membres de l'équipe",
        membersEmpty: "Aucun membre pour le moment.",
        readOnlyNote: "Seuls le propriétaire et les administrateurs peuvent gérer les membres et les invitations.",
        capacityLimited: "Membres : {used} sur {limit}",
        capacityUnlimited: "Membres : {used} (illimité)",
        capacityPending: "Invitations en attente : {n}",
        capacityFull: "Vous avez atteint la limite de membres de votre forfait actuel.",
        upgradeLink: "Changer de forfait",
        roleOwner: "Propriétaire",
        roleAdmin: "Administrateur",
        roleMember: "Membre",
        roleLabel: "Rôle",
        statusInvited: "En attente de connexion",
        you: "Vous",
        emailLabel: "E-mail",
        joinedLabel: "Membre depuis le",
        changeRoleLabel: "Changer le rôle",
        removeBtn: "Retirer",
        confirmRemove: "Retirer {name} de l'équipe ?",
        memberRemoved: "Membre retiré.",
        roleUpdated: "Rôle mis à jour.",
        inviteTitle: "Inviter un nouveau membre",
        inviteIntro: "Saisissez l'e-mail du membre et choisissez son rôle. S'il est inscrit sur la plateforme, il reçoit aussitôt une notification dans la cloche et rejoint l'équipe à sa prochaine ouverture de l'application. Sinon, envoyez-lui le lien de connexion :",
        copyLinkBtn: "Copier le lien de connexion",
        linkCopied: "Lien copié.",
        inviteEmailPlaceholder: "Adresse e-mail du membre",
        inviteBtn: "Inviter",
        lookupTitle: "Ou parmi les utilisateurs inscrits",
        inviteByEmailTitle: "Par e-mail",
        lookupBtn: "Afficher les utilisateurs",
        lookupPlaceholder: "E-mail, mobile ou numéro",
        lookupNone: "Aucun utilisateur trouvé. Vous pouvez l'inviter par e-mail.",
        inviteSending: "Ajout en cours...",
        inviteCreated: "Invitation ajoutée pour {email}. Cette personne rejoindra l'équipe automatiquement lors de sa connexion.",
        workloadTitle: "Répartition du travail",
        workloadIntro: "Glissez le travail sur un membre.",
        rasiTitle: "Matrice RASI",
        rasiIntro: "Pour chaque affaire, infraction ou tâche : qui exécute (R), qui approuve et répond (A — un seul), qui soutient (S), qui est informé (I). Cliquez une case pour changer le rôle ; la personne est notifiée aussitôt.",
        rasiLegendR: "Responsable",
        rasiLegendA: "Approbateur",
        rasiLegendS: "Soutien",
        rasiLegendI: "Informé",
        rasiSearch: "Rechercher par titre ou numéro",
        rasiEmpty: "Aucun élément ouvert à afficher.",
        rasiItemCol: "Élément",
        rasiSaved: "Rôle enregistré.",
        rasiNoMembers: "Ajoutez d’abord des membres.",
        quickTitle: "Répartition rapide",
        quickHint: "Touchez un membre sur un élément : un clic = Responsable (R) et vous Approbateur (A) automatiquement, deuxième clic = Soutien (S), troisième = retirer.",
        rasiShowMatrix: "Afficher la matrice complète",
        rasiHideMatrix: "Masquer la matrice",
        quickAddTitle: "Saisie rapide",
        quickAddHint: "Écrivez-la comme vous la diriez : « Audience affaire 4521, Al-Abraj, dimanche 10 h, pour Ahmad » — type, date, client, numéro d’affaire et responsable sont compris, enregistrés et répartis en un clic.",
        quickAddBtn: "Ajouter",
        quickAddPh: "Tapez la tâche, qui la fait et quand…",
        quickAddNobody: "Sans responsable",
        quickAddParsing: "Analyse…",
        quickAddDone: "« {title} » enregistrée{who}.",
        quickAddNoTitle: "Aucune tâche lisible dans ce texte — donnez au moins un titre.",
        quickAddNeedsParent: "À quelle affaire ou infraction cette tâche appartient-elle ? — aucune tâche isolée.",
        quickAddLink: "Lier et enregistrer",
        unassignedTitle: "Travail non attribué",
        unassignedEmpty: "Tout le travail est attribué.",
        wlOpen: "En cours",
        wlOverdue: "En retard",
        wlDone: "Terminé",
        assignTo: "Attribuer à",
        assignPick: "Choisir un membre",
        assignDone: "Attribué à {name}.",
        unassign: "Non attribué",
        noDue: "Sans échéance",
        chatTitle: "Discussion d'équipe",
        chatThreads: "Conversations",
        chatTeam: "Toute l'équipe",
        chatTeamHint: "À tous",
        chatPrivate: "Privé",
        chatPlaceholder: "Écrivez un message... (Entrée pour envoyer, Maj+Entrée pour une nouvelle ligne)",
        chatSend: "Envoyer",
        chatSendFile: "Envoyer le fichier",
        chatCancel: "Annuler",
        chatFiles: "📁 Fichiers",
        chatFilesEmpty: "Aucun fichier dans cette conversation.",
        chatDownload: "Télécharger",
        chatFileNoLink: "Sans lien avec une affaire",
        chatFileTooBig: "Le fichier dépasse 25 Mo.",
        chatUploading: "Envoi…",
        chatEmpty: "Aucun message.",
        chatLoadError: "Impossible de charger les messages.",
        chatDelete: "Supprimer",
        chatConfirmDelete: "Supprimer ce message ?",
        chatUnread: "{n} nouveau(x)",
        chatToday: "Aujourd'hui",
        chatLive: "En direct",
        chatOffline: "Reconnexion...",
        invitationsTitle: "Invitations en attente",
        invitationsEmpty: "Aucune invitation en attente.",
        invitedOn: "ajoutée le {date}",
        cancelInviteBtn: "Annuler",
        confirmCancelInvite: "Annuler l'invitation de {email} ?",
        inviteCancelled: "Invitation annulée.",
        invalidEmail: "Saisissez une adresse e-mail valide.",
        alreadyMember: "Cette adresse appartient déjà à un membre de l'équipe.",
        alreadyInvited: "Une invitation est déjà en attente pour cette adresse.",
        notAllowed: "Vous n'avez pas l'autorisation d'effectuer cette action.",
        genericError: "Une erreur est survenue. Veuillez réessayer.",
        planLimitMembers: "Vous avez atteint la limite de membres de votre forfait actuel. Passez à un forfait supérieur pour en ajouter.",
        copyrightLine2: "Tous droits réservés",
        aboutLink: "À propos",
        termsLink: "Conditions d'utilisation",
        pricingLink: "Forfaits et tarifs",
        privacyLink: "Politique de confidentialité",
        loginLink: "Connexion",
        dashboardLink: "Tableau de bord",
        contactLink: "Contactez-nous",
        language: "Langue",
        appearance: "Apparence",
        light: "Clair",
        dark: "Sombre"
      },
      ur: {
        exportXlsx: "ایکسل ایکسپورٹ",
        colLikelihood: "امکان",
        colImpact: "اثر",
        colResLikelihood: "بقایا امکان",
        colResImpact: "بقایا اثر",
        fCase: "مقدمہ",
        title: "خطرات کا انتظام",
        regTitle: "خطرات کا رجسٹر",
        heatTitle: "خطرات کا نقشہ",
        regIntro: "کلائنٹس اور مقدمات پر قانونی خطرات: امکان × اثر، علاج اور یاد دہانیوں سے جڑی کارروائیاں۔",
        newRisk: "＋ نیا خطرہ",
        exportCsv: "CSV",
        exportBtn: "برآمد",
        inherent: "علاج سے پہلے",
        residual: "علاج کے بعد",
        clearCell: "انتخاب ہٹائیں",
        likelihood: "امکان",
        impact: "اثر",
        colCode: "کوڈ",
        colTitle: "خطرہ",
        colCategory: "زمرہ",
        colClient: "کلائنٹ",
        colCase: "مقدمہ",
        colOwner: "ذمہ دار",
        colInherent: "پہلے",
        colResidual: "بعد",
        colStrategy: "حکمت عملی",
        colStatus: "حالت",
        colReview: "جائزہ",
        regEmpty: "ابھی کوئی خطرہ نہیں۔",
        editorNew: "نیا خطرہ",
        editorEdit: "ترمیم",
        fTitle: "عنوان",
