    const translations = {
      ar: {
        fCase: "القضية",
        title: "مكتبة الإجراءات",
        libTitle: "مكتبة الإجراءات",
        libIntro: "الإجراءات القانونية المعتمدة في المكتب خطوة خطوة: من يفعل ماذا (RACI)، وما الذي يبدأ الإجراء وما ينتج عنه.",
        newProcess: "＋ إجراء جديد",
        colCode: "الرمز",
        colName: "الإجراء",
        colArea: "المجال",
        colOwner: "المسؤول",
        colSteps: "الخطوات",
        colStatus: "الحالة",
        libEmpty: "لا إجراءات بعد — ابدأ بإجراء «رفع دعوى» أو «الاعتراض على مخالفة».",
        editorNew: "إجراء جديد",
        editorEdit: "تعديل الإجراء",
        fName: "اسم الإجراء",
        fArea: "المجال",
        fOwner: "المسؤول عن الإجراء",
        fFrequency: "التكرار",
        fTrigger: "ما الذي يبدأ الإجراء",
        fStatus: "الحالة",
        fInputs: "المدخلات",
        fOutputs: "المخرجات",
        fDescription: "الوصف",
        stepsTitle: "الخطوات",
        addStep: "＋ خطوة",
        noMembersYet: "ادع فريقك أولا من صفحة الفريق",
        stepType: "النوع",
        typeTask: "مهمة",
        typeDecision: "قرار (نعم/لا)",
        stepTitle: "الخطوة",
        stepNote: "ملاحظة",
        raci_R: "منفذ",
        raci_A: "مسؤول",
        raci_C: "يستشار",
        raci_I: "يبلغ",
        yesTo: "إن نعم → الخطوة",
        noTo: "إن لا → الخطوة",
        moveUp: "لأعلى",
        moveDown: "لأسفل",
        raciTitle: "مصفوفة RACI",
        flowTitle: "المخطط الانسيابي",
        yes: "نعم",
        no: "لا",
        noSteps: "لا خطوات.",
        edit: "تعديل",
        back: "رجوع",
        save: "حفظ",
        cancel: "إلغاء",
        none: "—",
        allAreas: "كل المجالات",
        saveFailed: "تعذر الحفظ.",
        deleteConfirm: "حذف هذا الإجراء نهائيا؟",
        area_lawsuits: "الدعاوى",
        area_violations: "المخالفات",
        area_contracts: "العقود",
        area_licenses: "التراخيص",
        area_documents: "المستندات",
        area_other: "أخرى",
        status_draft: "مسودة",
        status_review: "قيد المراجعة",
        status_published: "معتمد",
        status_archived: "مؤرشف",
        docAddTitle: "إضافة مستند",
        docAddIntro: "ارفع السجل التجاري أو الشهادة الضريبية أو الرخصة أو صحيفة الدعوى أو أي مستند (PDF أو صورة)، وسيقرأه النظام ويستخرج نوعه ورقمه وتاريخ انتهائه ويضيفه للمتابعة والتنبيه تلقائيا.",
        docDropHint: "اسحب المستند هنا أو اختر ملفا",
        docChoose: "اختيار ملف",
        docKind: "نوع المستند",
        docTitleField: "العنوان",
        docNumber: "رقم المستند",
        docIssuer: "الجهة المصدرة",
        docParty: "الشركة / صاحب المستند",
        docIssueDate: "تاريخ الإصدار",
        docExpiry: "تاريخ الانتهاء / الاستحقاق",
        docAmount: "المبلغ (<span class=\"sar-symbol\" aria-label=\"ريال سعودي\"></span>)",
        docCase: "رقم الدعوى",
        docCourt: "المحكمة",
        docSave: "حفظ وإضافة للمتابعة",
        docListTitle: "مستندات الشركة",
        docLeft: "المتبقي",
        docFiles: "الملفات",
        docsEmpty: "لا مستندات بعد.",
        docReading: "جاري قراءة المستند...",
        docOcr: "المستند صورة، جاري قراءته بالذكاء الاصطناعي...",
        docReady: "قرأت المستند — راجع الحقول ثم احفظ.",
        docFailed: "تعذر قراءة المستند، جرب ملفا أوضح.",
        docSaving: "جاري الحفظ...",
        docSaved: "حفظ المستند وأضيف للمتابعة والتنبيه.",
        docFileFailed: "حفظت البيانات لكن تعذر رفع الملف.",
        docStorageLimit: "حفظت البيانات لكن مساحة التخزين في باقتك ممتلئة.",
        docExpired: "منته",
        docDays: "يوما",
        docDeleteConfirm: "حذف المستند وملفاته نهائيا؟",
        allKinds: "كل الأنواع",
        search: "بحث",
        actions: "الإجراءات",
        delete: "حذف",
        unavailable: "الخدمة غير متاحة الآن.",
        kind_commercial_register: "سجل تجاري",
        kind_vat_certificate: "شهادة ضريبية",
        kind_license: "رخصة",
        kind_contract: "عقد",
        kind_case_filing: "صحيفة دعوى / مرفوعات",
        kind_court_ruling: "حكم قضائي",
        kind_hearing_notice: "إشعار جلسة",
        kind_violation: "مخالفة",
        kind_invoice: "فاتورة",
        kind_power_of_attorney: "وكالة",
        kind_id_document: "هوية / إقامة",
        kind_other: "مستند آخر",
        intro: "أضف أعضاء فريقك وحدد أدوارهم، وتابع الدعوات المعلقة.",
        backBtn: "العودة إلى لوحة التحكم",
        serviceUnavailableTitle: "الخدمة قيد التجهيز",
        serviceUnavailableText: "نعمل حاليا على تجهيز الخدمة، حاول مرة أخرى لاحقا.",
        noOrg: "لا توجد شركة محددة، أنشئ شركتك أولا.",
        noOrgHint: "انتقل إلى لوحة التحكم لإنشاء شركتك ثم عد إلى هذه الصفحة.",
        loading: "جاري التحميل...",
        loadError: "تعذر تحميل بيانات الفريق، حاول مرة أخرى.",
        membersTitle: "أعضاء الفريق",
        membersEmpty: "لا يوجد أعضاء بعد.",
        readOnlyNote: "يمكن للمالك والمشرفين فقط إدارة الأعضاء والدعوات.",
        capacityLimited: "الأعضاء: {used} من {limit}",
        capacityUnlimited: "الأعضاء: {used} (بلا حد)",
        capacityPending: "الدعوات المعلقة: {n}",
        capacityFull: "وصلت إلى الحد الأقصى لعدد الأعضاء في باقتك الحالية.",
        upgradeLink: "ترقية الباقة",
        roleOwner: "المالك",
        roleAdmin: "مشرف",
        roleMember: "عضو",
        roleLabel: "الدور",
        statusInvited: "بانتظار الانضمام",
        you: "أنت",
        emailLabel: "البريد الإلكتروني",
        joinedLabel: "تاريخ الانضمام",
        changeRoleLabel: "تغيير الدور",
        removeBtn: "إزالة",
        confirmRemove: "هل تريد إزالة {name} من الفريق؟",
        memberRemoved: "تمت إزالة العضو.",
        roleUpdated: "تم تحديث الدور.",
        inviteTitle: "دعوة عضو جديد",
        inviteIntro: "أدخل البريد الإلكتروني للعضو واختر دوره. إن كان مسجلا في المنصة وصله تنبيه في جرس التنبيهات فورا، وينضم إلى الفريق عند فتحه التطبيق. وإن لم يكن مسجلا فأرسل له رابط تسجيل الدخول:",
        copyLinkBtn: "نسخ رابط تسجيل الدخول",
        linkCopied: "تم نسخ الرابط.",
        inviteEmailPlaceholder: "بريد العضو الإلكتروني",
        inviteBtn: "دعوة",
        lookupTitle: "أو من المسجلين في المنصة",
        inviteByEmailTitle: "بالبريد الإلكتروني",
        lookupBtn: "عرض المستخدمين",
        lookupPlaceholder: "بريد أو جوال أو رقم مستخدم",
        lookupNone: "لا يوجد مستخدم مطابق. تستطيع دعوته ببريده مباشرة.",
        inviteSending: "جاري الإضافة...",
        inviteCreated: "أضيفت الدعوة ل {email}، وسينضم تلقائيا عند تسجيل دخوله.",
        workloadTitle: "توزيع الأعمال",
        workloadIntro: "اسحب العمل إلى العضو.",
        rasiTitle: "مصفوفة RASI",
        rasiIntro: "لكل قضية أو مخالفة أو مهمة: من ينفذ (R)، من يعتمد ويساءل (A — واحد فقط)، من يساند (S)، ومن يبلغ (I). اضغط الخلية لتبديل الدور، ويصل صاحبه تنبيه فورا.",
        rasiLegendR: "المنفذ المسؤول",
        rasiLegendA: "المعتمد والمساءل",
        rasiLegendS: "المساند",
        rasiLegendI: "المبلغ",
        rasiSearch: "ابحث بالعنوان أو الرقم",
        rasiEmpty: "لا عناصر مفتوحة لعرضها.",
        rasiItemCol: "العنصر",
        rasiSaved: "حفظ الدور.",
        rasiNoMembers: "أضف أعضاء إلى الفريق أولا.",
        quickTitle: "توزيع سريع",
        quickHint: "اضغط اسم العضو على العنصر: ضغطة واحدة = هو المنفذ المسؤول (R) وأنت المعتمد (A) تلقائيا، ضغطة ثانية = مساند (S)، ثالثة = إزالة.",
        rasiShowMatrix: "عرض المصفوفة الكاملة",
        rasiHideMatrix: "إخفاء المصفوفة",
        quickAddTitle: "إدخال سريع",
        quickAddHint: "اكتب المهمة كما تقولها: «جلسة القضية 4521 لشركة الأبراج الأحد 10 صباحا لأحمد» — يفهم النوع والموعد والعميل ورقم الدعوى ومن ينفذ، ويسجل ويوزع بضغطة واحدة.",
        quickAddBtn: "إضافة",
        quickAddPh: "اكتب المهمة ومن ينفذها وموعدها…",
        quickAddNobody: "بلا منفذ (أنا لاحقا)",
        quickAddParsing: "جاري الفهم…",
        quickAddDone: "سجلت «{title}»{who}.",
        quickAddNoTitle: "لم أفهم مهمة من هذا النص — اكتب عنوانها على الأقل.",
        quickAddNeedsParent: "لأي قضية أو مخالفة تتبع هذه المهمة؟ — لا مهمة بلا أصل.",
        quickAddLink: "اربط وسجل",
        unassignedTitle: "أعمال بلا صاحب",
        unassignedEmpty: "كل الأعمال مسندة.",
        wlOpen: "جارية",
        wlOverdue: "متأخرة",
        wlDone: "منتهية",
        assignTo: "أسند إلى",
        assignPick: "اختر عضوا",
        assignDone: "أسند العمل إلى {name}.",
        unassign: "بلا صاحب",
        noDue: "بلا موعد",
        chatTitle: "تواصل الفريق",
        chatThreads: "المحادثات",
        chatTeam: "الفريق كله",
        chatTeamHint: "اكتب للكل",
        chatPrivate: "خاص",
        chatPlaceholder: "اكتب رسالتك... (Enter للإرسال، Shift+Enter لسطر جديد)",
        chatSend: "إرسال",
        chatSendFile: "إرسال الملف",
        chatCancel: "إلغاء",
        chatFiles: "📁 الملفات",
        chatFilesEmpty: "لا ملفات في هذه المحادثة بعد.",
        chatDownload: "تنزيل",
        chatFileNoLink: "بلا ربط بقضية",
        chatFileTooBig: "الملف أكبر من 25 ميغابايت.",
        chatUploading: "جاري رفع الملف…",
        chatEmpty: "لا رسائل بعد.",
        chatLoadError: "تعذر تحميل الرسائل.",
        chatDelete: "حذف",
        chatConfirmDelete: "حذف هذه الرسالة؟",
        chatUnread: "{n} جديدة",
        chatToday: "اليوم",
        chatLive: "متصل",
        chatOffline: "يعاد الاتصال...",
        invitationsTitle: "الدعوات المعلقة",
        invitationsEmpty: "لا توجد دعوات معلقة.",
        invitedOn: "أضيفت في {date}",
        cancelInviteBtn: "إلغاء",
        confirmCancelInvite: "هل تريد إلغاء دعوة {email}؟",
        inviteCancelled: "ألغيت الدعوة.",
        invalidEmail: "أدخل بريدا إلكترونيا صحيحا.",
        alreadyMember: "هذا البريد عضو في الفريق بالفعل.",
        alreadyInvited: "توجد دعوة معلقة لهذا البريد بالفعل.",
        notAllowed: "ليست لديك صلاحية لتنفيذ هذا الإجراء.",
        genericError: "حدث خطأ، حاول مرة أخرى.",
        planLimitMembers: "وصلت إلى الحد الأقصى لعدد الأعضاء في باقتك الحالية، رق باقتك لإضافة المزيد.",
        copyrightLine2: "جميع الحقوق محفوظة",
        aboutLink: "من نحن",
        termsLink: "شروط الاستخدام",
        pricingLink: "الباقات والأسعار",
        privacyLink: "سياسة الخصوصية",
        loginLink: "تسجيل الدخول",
        dashboardLink: "لوحة التحكم",
        contactLink: "تواصل معنا",
        language: "اللغة",
        appearance: "المظهر",
        light: "فاتح",
        dark: "داكن"
      },
      en: {
        fCase: "Case",
        title: "Process library",
        libTitle: "Process library",
        libIntro: "The firm's approved legal procedures step by step: who does what (RACI), what triggers the procedure and what it produces.",
        newProcess: "＋ New procedure",
        colCode: "Code",
        colName: "Procedure",
        colArea: "Area",
        colOwner: "Owner",
        colSteps: "Steps",
        colStatus: "Status",
        libEmpty: "No procedures yet — start with “Filing a lawsuit” or “Objecting to a violation”.",
        editorNew: "New procedure",
        editorEdit: "Edit procedure",
        fName: "Procedure name",
        fArea: "Area",
        fOwner: "Process owner",
        fFrequency: "Frequency",
        fTrigger: "Trigger",
        fStatus: "Status",
        fInputs: "Inputs",
        fOutputs: "Outputs",
        fDescription: "Description",
        stepsTitle: "Steps",
        addStep: "＋ Step",
        noMembersYet: "Invite your team first from the Team page",
        stepType: "Type",
        typeTask: "Task",
        typeDecision: "Decision (yes/no)",
        stepTitle: "Step",
        stepNote: "Note",
        raci_R: "Responsible",
        raci_A: "Accountable",
        raci_C: "Consulted",
        raci_I: "Informed",
        yesTo: "If yes → step",
        noTo: "If no → step",
        moveUp: "Move up",
        moveDown: "Move down",
        raciTitle: "RACI matrix",
        flowTitle: "Flowchart",
        yes: "Yes",
        no: "No",
        noSteps: "No steps.",
        edit: "Edit",
        back: "Back",
        save: "Save",
        cancel: "Cancel",
        none: "—",
        allAreas: "All areas",
        saveFailed: "Could not save.",
        deleteConfirm: "Delete this procedure permanently?",
        area_lawsuits: "Lawsuits",
        area_violations: "Violations",
        area_contracts: "Contracts",
        area_licenses: "Licences",
        area_documents: "Documents",
        area_other: "Other",
        status_draft: "Draft",
        status_review: "In review",
        status_published: "Approved",
        status_archived: "Archived",
        docAddTitle: "Add a document",
        docAddIntro: "Upload a commercial register, VAT certificate, licence, statement of claim or any document (PDF or image); the system reads it, extracts its type, number and expiry, and adds it to tracking and reminders.",
        docDropHint: "Drop the document here or choose a file",
        docChoose: "Choose file",
        docKind: "Document type",
        docTitleField: "Title",
        docNumber: "Document number",
        docIssuer: "Issuer",
        docParty: "Company / holder",
        docIssueDate: "Issue date",
        docExpiry: "Expiry / due date",
        docAmount: "Amount (<span class=\"sar-symbol\" aria-label=\"ريال سعودي\"></span>)",
        docCase: "Case number",
        docCourt: "Court",
        docSave: "Save and track",
        docListTitle: "Company documents",
        docLeft: "Remaining",
        docFiles: "Files",
        docsEmpty: "No documents yet.",
        docReading: "Reading the document...",
        docOcr: "Image document — reading it with AI...",
        docReady: "Document read — review the fields and save.",
        docFailed: "Could not read the document; try a clearer file.",
        docSaving: "Saving...",
        docSaved: "Saved and added to tracking and reminders.",
        docFileFailed: "Data saved, but the file could not be uploaded.",
        docStorageLimit: "Data saved, but your plan storage is full.",
        docExpired: "Expired",
        docDays: "days",
        docDeleteConfirm: "Delete this document and its files permanently?",
        allKinds: "All types",
        search: "Search",
        actions: "Actions",
        delete: "Delete",
        unavailable: "Service unavailable right now.",
        kind_commercial_register: "Commercial register",
        kind_vat_certificate: "VAT certificate",
        kind_license: "Licence",
        kind_contract: "Contract",
        kind_case_filing: "Statement of claim / filing",
        kind_court_ruling: "Court ruling",
        kind_hearing_notice: "Hearing notice",
        kind_violation: "Violation",
        kind_invoice: "Invoice",
        kind_power_of_attorney: "Power of attorney",
        kind_id_document: "ID document",
        kind_other: "Other document",
        intro: "Add your team members, set their roles, and follow up on pending invitations.",
        backBtn: "Back to Dashboard",
        serviceUnavailableTitle: "Service is being prepared",
        serviceUnavailableText: "We are setting up the service. Please try again later.",
        noOrg: "No company selected. Create your company first.",
        noOrgHint: "Go to the dashboard to create your company, then come back to this page.",
        loading: "Loading...",
        loadError: "Could not load the team data. Please try again.",
        membersTitle: "Team members",
        membersEmpty: "No members yet.",
        readOnlyNote: "Only the owner and admins can manage members and invitations.",
        capacityLimited: "Members: {used} of {limit}",
        capacityUnlimited: "Members: {used} (unlimited)",
        capacityPending: "Pending invitations: {n}",
        capacityFull: "You have reached the member limit of your current plan.",
        upgradeLink: "Upgrade plan",
        roleOwner: "Owner",
        roleAdmin: "Admin",
        roleMember: "Member",
        roleLabel: "Role",
        statusInvited: "Awaiting sign-in",
        you: "You",
        emailLabel: "Email",
        joinedLabel: "Joined on",
        changeRoleLabel: "Change role",
        removeBtn: "Remove",
        confirmRemove: "Remove {name} from the team?",
        memberRemoved: "Member removed.",
        roleUpdated: "Role updated.",
        inviteTitle: "Invite a new member",
        inviteIntro: "Enter the member's email and choose a role. If they are registered on the platform they get a notification in the bell right away, and they join the team the next time they open the app. Otherwise, send them the sign-in link:",
        copyLinkBtn: "Copy sign-in link",
        linkCopied: "Link copied.",
        inviteEmailPlaceholder: "Member's email address",
        inviteBtn: "Invite",
        lookupTitle: "Or from registered users",
        inviteByEmailTitle: "By email",
        lookupBtn: "Show users",
        lookupPlaceholder: "Email, mobile or user number",
        lookupNone: "No matching user. You can still invite them by email.",
        inviteSending: "Adding...",
        inviteCreated: "Invitation added for {email}. They will join automatically when they sign in.",
        workloadTitle: "Work distribution",
        workloadIntro: "Drag work onto a member.",
        rasiTitle: "RASI Matrix",
        rasiIntro: "For every case, violation or task: who does it (R), who approves and answers for it (A — exactly one), who supports (S), who is kept informed (I). Click a cell to cycle the role; the person is notified instantly.",
        rasiLegendR: "Responsible",
        rasiLegendA: "Approver / accountable",
        rasiLegendS: "Support",
        rasiLegendI: "Informed",
        rasiSearch: "Search by title or number",
        rasiEmpty: "No open items to show.",
        rasiItemCol: "Item",
        rasiSaved: "Role saved.",
        rasiNoMembers: "Add team members first.",
        quickTitle: "Quick distribution",
        quickHint: "Tap a member on an item: one tap = Responsible (R) with you as Approver (A) automatically, second tap = Support (S), third = remove.",
        rasiShowMatrix: "Show the full matrix",
        rasiHideMatrix: "Hide the matrix",
        quickAddTitle: "Quick entry",
        quickAddHint: "Type it the way you would say it: \"Hearing for case 4521, Al-Abraj, Sunday 10 AM, for Ahmad\" — kind, date, client, case number and who does it are understood, recorded and distributed in one tap.",
        quickAddBtn: "Add",
        quickAddPh: "Type the task, who does it and when…",
        quickAddNobody: "No responsible yet",
        quickAddParsing: "Understanding…",
        quickAddDone: "Recorded \"{title}\"{who}.",
        quickAddNoTitle: "I could not read a task from that — at least give it a title.",
        quickAddNeedsParent: "Which case or violation does this task belong to? — no task stands alone.",
        quickAddLink: "Link and record",
        unassignedTitle: "Unassigned work",
        unassignedEmpty: "All work is assigned.",
        wlOpen: "Open",
        wlOverdue: "Overdue",
        wlDone: "Done",
        assignTo: "Assign to",
        assignPick: "Pick a member",
        assignDone: "Assigned to {name}.",
        unassign: "Unassigned",
        noDue: "No due date",
        chatTitle: "Team chat",
        chatThreads: "Conversations",
        chatTeam: "Whole team",
        chatTeamHint: "Everyone",
        chatPrivate: "Private",
        chatPlaceholder: "Write a message... (Enter to send, Shift+Enter for a new line)",
        chatSend: "Send",
        chatSendFile: "Send file",
        chatCancel: "Cancel",
        chatFiles: "📁 Files",
        chatFilesEmpty: "No files in this conversation yet.",
        chatDownload: "Download",
        chatFileNoLink: "Not linked to a case",
        chatFileTooBig: "The file exceeds 25 MB.",
        chatUploading: "Uploading…",
        chatEmpty: "No messages yet.",
        chatLoadError: "Could not load messages.",
        chatDelete: "Delete",
        chatConfirmDelete: "Delete this message?",
        chatUnread: "{n} new",
        chatToday: "Today",
        chatLive: "Live",
        chatOffline: "Reconnecting...",
        invitationsTitle: "Pending invitations",
        invitationsEmpty: "No pending invitations.",
        invitedOn: "added on {date}",
        cancelInviteBtn: "Cancel",
        confirmCancelInvite: "Cancel the invitation for {email}?",
        inviteCancelled: "Invitation cancelled.",
        invalidEmail: "Enter a valid email address.",
        alreadyMember: "This email already belongs to a team member.",
        alreadyInvited: "There is already a pending invitation for this email.",
        notAllowed: "You do not have permission to perform this action.",
        genericError: "Something went wrong. Please try again.",
        planLimitMembers: "You have reached the member limit of your current plan. Upgrade to add more.",
        copyrightLine2: "All rights reserved",
        aboutLink: "About Us",
        termsLink: "Terms of Use",
        pricingLink: "Plans & Pricing",
        privacyLink: "Privacy Policy",
        loginLink: "Sign in",
        dashboardLink: "Dashboard",
        contactLink: "Contact Us",
        language: "Language",
        appearance: "Appearance",
        light: "Light",
        dark: "Dark"
      },
      fr: {
        fCase: "Affaire",
        title: "Bibliothèque des procédures",
        libTitle: "Bibliothèque des procédures",
        libIntro: "Les procédures juridiques du cabinet étape par étape : qui fait quoi (RACI), le déclencheur et le résultat.",
        newProcess: "＋ Nouvelle procédure",
        colCode: "Code",
        colName: "Procédure",
        colArea: "Domaine",
        colOwner: "Responsable",
        colSteps: "Étapes",
        colStatus: "Statut",
        libEmpty: "Aucune procédure — commencez par « Dépôt de requête » ou « Contestation d’une infraction ».",
        editorNew: "Nouvelle procédure",
        editorEdit: "Modifier la procédure",
        fName: "Nom de la procédure",
        fArea: "Domaine",
        fOwner: "Responsable",
        fFrequency: "Fréquence",
        fTrigger: "Déclencheur",
        fStatus: "Statut",
        fInputs: "Entrées",
        fOutputs: "Sorties",
        fDescription: "Description",
        stepsTitle: "Étapes",
        addStep: "＋ Étape",
        noMembersYet: "Invitez d’abord votre équipe depuis la page Équipe",
        stepType: "Type",
        typeTask: "Tâche",
        typeDecision: "Décision (oui/non)",
        stepTitle: "Étape",
        stepNote: "Note",
        raci_R: "Réalise",
        raci_A: "Responsable",
        raci_C: "Consulté",
        raci_I: "Informé",
        yesTo: "Si oui → étape",
        noTo: "Si non → étape",
        moveUp: "Monter",
        moveDown: "Descendre",
        raciTitle: "Matrice RACI",
        flowTitle: "Organigramme",
        yes: "Oui",
        no: "Non",
        noSteps: "Aucune étape.",
        edit: "Modifier",
        back: "Retour",
        save: "Enregistrer",
        cancel: "Annuler",
        none: "—",
        allAreas: "Tous les domaines",
        saveFailed: "Enregistrement impossible.",
        deleteConfirm: "Supprimer cette procédure ?",
        area_lawsuits: "Affaires",
        area_violations: "Infractions",
        area_contracts: "Contrats",
        area_licenses: "Licences",
        area_documents: "Documents",
        area_other: "Autre",
        status_draft: "Brouillon",
        status_review: "En revue",
        status_published: "Approuvée",
        status_archived: "Archivée",
        docAddTitle: "Ajouter un document",
        docAddIntro: "Téléversez un registre de commerce, une attestation TVA, une licence, une requête ou tout document (PDF ou image) ; le système le lit, en extrait le type, le numéro et l'échéance, et l'ajoute au suivi et aux rappels.",
        docDropHint: "Déposez le document ici ou choisissez un fichier",
        docChoose: "Choisir un fichier",
        docKind: "Type de document",
        docTitleField: "Titre",
        docNumber: "Numéro",
        docIssuer: "Émetteur",
        docParty: "Entreprise / titulaire",
        docIssueDate: "Date d'émission",
        docExpiry: "Expiration / échéance",
        docAmount: "Montant (<span class=\"sar-symbol\" aria-label=\"ريال سعودي\"></span>)",
        docCase: "Numéro de dossier",
        docCourt: "Tribunal",
        docSave: "Enregistrer et suivre",
        docListTitle: "Documents de l'entreprise",
        docLeft: "Restant",
        docFiles: "Fichiers",
        docsEmpty: "Aucun document.",
        docReading: "Lecture du document...",
        docOcr: "Document image — lecture par IA...",
        docReady: "Document lu — vérifiez les champs puis enregistrez.",
        docFailed: "Lecture impossible ; essayez un fichier plus net.",
        docSaving: "Enregistrement...",
        docSaved: "Enregistré et ajouté au suivi.",
        docFileFailed: "Données enregistrées, mais le fichier n’a pas pu être téléversé.",
        docStorageLimit: "Données enregistrées, mais le stockage de votre forfait est plein.",
        docExpired: "Expiré",
        docDays: "jours",
        docDeleteConfirm: "Supprimer ce document et ses fichiers ?",
        allKinds: "Tous les types",
        search: "Rechercher",
        actions: "Actions",
        delete: "Supprimer",
        unavailable: "Service indisponible.",
        kind_commercial_register: "Registre de commerce",
        kind_vat_certificate: "Attestation TVA",
        kind_license: "Licence",
        kind_contract: "Contrat",
        kind_case_filing: "Requête / dépôt",
        kind_court_ruling: "Jugement",
        kind_hearing_notice: "Avis d'audience",
        kind_violation: "Infraction",
        kind_invoice: "Facture",
        kind_power_of_attorney: "Procuration",
        kind_id_document: "Pièce d'identité",
        kind_other: "Autre document",
        intro: "Ajoutez les membres de votre équipe, définissez leurs rôles et suivez les invitations en attente.",
        backBtn: "Retour au tableau de bord",
        serviceUnavailableTitle: "Service en cours de préparation",
        serviceUnavailableText: "Nous préparons le service. Veuillez réessayer plus tard.",
        noOrg: "Aucune entreprise sélectionnée. Créez d'abord votre entreprise.",
        noOrgHint: "Rendez-vous sur le tableau de bord pour créer votre entreprise, puis revenez sur cette page.",
        loading: "Chargement...",
        loadError: "Impossible de charger les données de l'équipe. Veuillez réessayer.",
        membersTitle: "Membres de l'équipe",
        membersEmpty: "Aucun membre pour le moment.",
        readOnlyNote: "Seuls le propriétaire et les administrateurs peuvent gérer les membres et les invitations.",
        capacityLimited: "Membres : {used} sur {limit}",
        capacityUnlimited: "Membres : {used} (illimité)",
        capacityPending: "Invitations en attente : {n}",
        capacityFull: "Vous avez atteint la limite de membres de votre forfait actuel.",
        upgradeLink: "Changer de forfait",
        roleOwner: "Propriétaire",
        roleAdmin: "Administrateur",
        roleMember: "Membre",
        roleLabel: "Rôle",
        statusInvited: "En attente de connexion",
        you: "Vous",
        emailLabel: "E-mail",
        joinedLabel: "Membre depuis le",
        changeRoleLabel: "Changer le rôle",
        removeBtn: "Retirer",
        confirmRemove: "Retirer {name} de l'équipe ?",
        memberRemoved: "Membre retiré.",
        roleUpdated: "Rôle mis à jour.",
        inviteTitle: "Inviter un nouveau membre",
        inviteIntro: "Saisissez l'e-mail du membre et choisissez son rôle. S'il est inscrit sur la plateforme, il reçoit aussitôt une notification dans la cloche et rejoint l'équipe à sa prochaine ouverture de l'application. Sinon, envoyez-lui le lien de connexion :",
        copyLinkBtn: "Copier le lien de connexion",
        linkCopied: "Lien copié.",
        inviteEmailPlaceholder: "Adresse e-mail du membre",
        inviteBtn: "Inviter",
        lookupTitle: "Ou parmi les utilisateurs inscrits",
        inviteByEmailTitle: "Par e-mail",
        lookupBtn: "Afficher les utilisateurs",
        lookupPlaceholder: "E-mail, mobile ou numéro",
        lookupNone: "Aucun utilisateur trouvé. Vous pouvez l'inviter par e-mail.",
        inviteSending: "Ajout en cours...",
        inviteCreated: "Invitation ajoutée pour {email}. Cette personne rejoindra l'équipe automatiquement lors de sa connexion.",
        workloadTitle: "Répartition du travail",
        workloadIntro: "Glissez le travail sur un membre.",
        rasiTitle: "Matrice RASI",
        rasiIntro: "Pour chaque affaire, infraction ou tâche : qui exécute (R), qui approuve et répond (A — un seul), qui soutient (S), qui est informé (I). Cliquez une case pour changer le rôle ; la personne est notifiée aussitôt.",
        rasiLegendR: "Responsable",
        rasiLegendA: "Approbateur",
        rasiLegendS: "Soutien",
        rasiLegendI: "Informé",
        rasiSearch: "Rechercher par titre ou numéro",
        rasiEmpty: "Aucun élément ouvert à afficher.",
        rasiItemCol: "Élément",
        rasiSaved: "Rôle enregistré.",
        rasiNoMembers: "Ajoutez d’abord des membres.",
        quickTitle: "Répartition rapide",
        quickHint: "Touchez un membre sur un élément : un clic = Responsable (R) et vous Approbateur (A) automatiquement, deuxième clic = Soutien (S), troisième = retirer.",
        rasiShowMatrix: "Afficher la matrice complète",
        rasiHideMatrix: "Masquer la matrice",
        quickAddTitle: "Saisie rapide",
        quickAddHint: "Écrivez-la comme vous la diriez : « Audience affaire 4521, Al-Abraj, dimanche 10 h, pour Ahmad » — type, date, client, numéro d’affaire et responsable sont compris, enregistrés et répartis en un clic.",
        quickAddBtn: "Ajouter",
        quickAddPh: "Tapez la tâche, qui la fait et quand…",
        quickAddNobody: "Sans responsable",
        quickAddParsing: "Analyse…",
        quickAddDone: "« {title} » enregistrée{who}.",
        quickAddNoTitle: "Aucune tâche lisible dans ce texte — donnez au moins un titre.",
        quickAddNeedsParent: "À quelle affaire ou infraction cette tâche appartient-elle ? — aucune tâche isolée.",
        quickAddLink: "Lier et enregistrer",
        unassignedTitle: "Travail non attribué",
        unassignedEmpty: "Tout le travail est attribué.",
        wlOpen: "En cours",
        wlOverdue: "En retard",
        wlDone: "Terminé",
        assignTo: "Attribuer à",
        assignPick: "Choisir un membre",
        assignDone: "Attribué à {name}.",
        unassign: "Non attribué",
        noDue: "Sans échéance",
        chatTitle: "Discussion d'équipe",
        chatThreads: "Conversations",
        chatTeam: "Toute l'équipe",
        chatTeamHint: "À tous",
        chatPrivate: "Privé",
        chatPlaceholder: "Écrivez un message... (Entrée pour envoyer, Maj+Entrée pour une nouvelle ligne)",
        chatSend: "Envoyer",
        chatSendFile: "Envoyer le fichier",
        chatCancel: "Annuler",
        chatFiles: "📁 Fichiers",
        chatFilesEmpty: "Aucun fichier dans cette conversation.",
        chatDownload: "Télécharger",
        chatFileNoLink: "Sans lien avec une affaire",
        chatFileTooBig: "Le fichier dépasse 25 Mo.",
        chatUploading: "Envoi…",
        chatEmpty: "Aucun message.",
        chatLoadError: "Impossible de charger les messages.",
        chatDelete: "Supprimer",
        chatConfirmDelete: "Supprimer ce message ?",
        chatUnread: "{n} nouveau(x)",
        chatToday: "Aujourd'hui",
        chatLive: "En direct",
        chatOffline: "Reconnexion...",
        invitationsTitle: "Invitations en attente",
        invitationsEmpty: "Aucune invitation en attente.",
        invitedOn: "ajoutée le {date}",
        cancelInviteBtn: "Annuler",
        confirmCancelInvite: "Annuler l'invitation de {email} ?",
        inviteCancelled: "Invitation annulée.",
        invalidEmail: "Saisissez une adresse e-mail valide.",
        alreadyMember: "Cette adresse appartient déjà à un membre de l'équipe.",
        alreadyInvited: "Une invitation est déjà en attente pour cette adresse.",
        notAllowed: "Vous n'avez pas l'autorisation d'effectuer cette action.",
        genericError: "Une erreur est survenue. Veuillez réessayer.",
        planLimitMembers: "Vous avez atteint la limite de membres de votre forfait actuel. Passez à un forfait supérieur pour en ajouter.",
        copyrightLine2: "Tous droits réservés",
        aboutLink: "À propos",
        termsLink: "Conditions d'utilisation",
        pricingLink: "Forfaits et tarifs",
        privacyLink: "Politique de confidentialité",
        loginLink: "Connexion",
        dashboardLink: "Tableau de bord",
        contactLink: "Contactez-nous",
        language: "Langue",
        appearance: "Apparence",
        light: "Clair",
        dark: "Sombre"
      },
      ur: {
        fCase: "مقدمہ",
        title: "طریقہ کار لائبریری",
        libTitle: "طریقہ کار لائبریری",
        libIntro: "دفتر کے منظور شدہ قانونی طریقہ کار مرحلہ وار: کون کیا کرتا ہے (RACI)، آغاز کیا ہے اور نتیجہ کیا۔",
        newProcess: "＋ نیا طریقہ کار",
        colCode: "کوڈ",
        colName: "طریقہ کار",
        colArea: "شعبہ",
        colOwner: "ذمہ دار",
        colSteps: "مراحل",
        colStatus: "حالت",
        libEmpty: "ابھی کوئی طریقہ کار نہیں۔",
        editorNew: "نیا طریقہ کار",
        editorEdit: "ترمیم",
        fName: "نام",
        fArea: "شعبہ",
        fOwner: "ذمہ دار",
        fFrequency: "تکرار",
        fTrigger: "محرک",
        fStatus: "حالت",
        fInputs: "ان پٹ",
        fOutputs: "آؤٹ پٹ",
        fDescription: "تفصیل",
        stepsTitle: "مراحل",
        addStep: "＋ مرحلہ",
        noMembersYet: "پہلے ٹیم کے صفحے سے اپنی ٹیم کو مدعو کریں",
        stepType: "قسم",
        typeTask: "کام",
        typeDecision: "فیصلہ (ہاں/نہیں)",
        stepTitle: "مرحلہ",
        stepNote: "نوٹ",
        raci_R: "انجام دہندہ",
        raci_A: "جواب دہ",
        raci_C: "مشاورت",
        raci_I: "اطلاع",
        yesTo: "ہاں → مرحلہ",
        noTo: "نہیں → مرحلہ",
        moveUp: "اوپر",
        moveDown: "نیچے",
        raciTitle: "RACI میٹرکس",
        flowTitle: "فلو چارٹ",
        yes: "ہاں",
        no: "نہیں",
        noSteps: "کوئی مرحلہ نہیں۔",
        edit: "ترمیم",
        back: "واپس",
        save: "محفوظ",
        cancel: "منسوخ",
        none: "—",
        allAreas: "تمام شعبے",
        saveFailed: "محفوظ نہیں ہو سکا۔",
        deleteConfirm: "مستقل حذف کریں؟",
        area_lawsuits: "مقدمات",
        area_violations: "خلاف ورزیاں",
        area_contracts: "معاہدے",
        area_licenses: "لائسنس",
        area_documents: "دستاویزات",
        area_other: "دیگر",
        status_draft: "مسودہ",
        status_review: "زیر جائزہ",
        status_published: "منظور",
        status_archived: "محفوظ شدہ",
        docAddTitle: "دستاویز شامل کریں",
        docAddIntro: "کمرشل رجسٹر، ٹیکس سرٹیفکیٹ، لائسنس، دعوی یا کوئی بھی دستاویز (PDF یا تصویر) اپ لوڈ کریں؛ نظام اسے پڑھ کر قسم، نمبر اور میعاد نکالتا ہے اور ٹریکنگ و یاد دہانی میں شامل کرتا ہے۔",
        docDropHint: "دستاویز یہاں ڈالیں یا فائل چنیں",
        docChoose: "فائل چنیں",
        docKind: "دستاویز کی قسم",
        docTitleField: "عنوان",
        docNumber: "دستاویز نمبر",
        docIssuer: "جاری کنندہ",
        docParty: "کمپنی / مالک",
        docIssueDate: "اجرا کی تاریخ",
        docExpiry: "میعاد / مقررہ تاریخ",
        docAmount: "رقم (<span class=\"sar-symbol\" aria-label=\"ريال سعودي\"></span>)",
        docCase: "مقدمہ نمبر",
        docCourt: "عدالت",
        docSave: "محفوظ کریں اور ٹریک کریں",
        docListTitle: "کمپنی کی دستاویزات",
        docLeft: "باقی",
        docFiles: "فائلیں",
        docsEmpty: "ابھی کوئی دستاویز نہیں۔",
        docReading: "دستاویز پڑھی جا رہی ہے...",
        docOcr: "تصویری دستاویز — AI سے پڑھی جا رہی ہے...",
        docReady: "پڑھ لی گئی — خانے جانچ کر محفوظ کریں۔",
        docFailed: "پڑھی نہیں جا سکی؛ واضح فائل آزمائیں۔",
        docSaving: "محفوظ ہو رہا ہے...",
        docSaved: "محفوظ ہو کر ٹریکنگ میں شامل ہو گئی۔",
        docFileFailed: "ڈیٹا محفوظ ہوا مگر فائل اپ لوڈ نہیں ہو سکی۔",
        docStorageLimit: "ڈیٹا محفوظ ہوا مگر پیکج کی اسٹوریج بھر گئی۔",
        docExpired: "ختم",
        docDays: "دن",
        docDeleteConfirm: "دستاویز اور فائلیں مستقل حذف کریں؟",
        allKinds: "تمام اقسام",
        search: "تلاش",
        actions: "کارروائیاں",
        delete: "حذف",
        unavailable: "خدمت دستیاب نہیں۔",
        kind_commercial_register: "کمرشل رجسٹر",
        kind_vat_certificate: "ٹیکس سرٹیفکیٹ",
        kind_license: "لائسنس",
        kind_contract: "معاہدہ",
        kind_case_filing: "دعوی / دستاویزات",
        kind_court_ruling: "عدالتی فیصلہ",
        kind_hearing_notice: "سماعت کا نوٹس",
        kind_violation: "خلاف ورزی",
        kind_invoice: "انوائس",
        kind_power_of_attorney: "مختار نامہ",
        kind_id_document: "شناختی دستاویز",
        kind_other: "دیگر دستاویز",
        intro: "اپنی ٹیم کے اراکین شامل کریں، ان کے کردار طے کریں اور زیر التوا دعوتوں پر نظر رکھیں۔",
        backBtn: "ڈیش بورڈ پر واپس جائیں",
        serviceUnavailableTitle: "سروس تیار کی جا رہی ہے",
        serviceUnavailableText: "ہم سروس تیار کر رہے ہیں، براہ کرم بعد میں دوبارہ کوشش کریں۔",
        noOrg: "کوئی کمپنی منتخب نہیں، پہلے اپنی کمپنی بنائیں۔",
        noOrgHint: "اپنی کمپنی بنانے کے لیے ڈیش بورڈ پر جائیں، پھر اس صفحے پر واپس آئیں۔",
        loading: "لوڈ ہو رہا ہے...",
        loadError: "ٹیم کا ڈیٹا لوڈ نہیں ہو سکا، براہ کرم دوبارہ کوشش کریں۔",
        membersTitle: "ٹیم کے اراکین",
        membersEmpty: "ابھی کوئی رکن نہیں ہے۔",
        readOnlyNote: "صرف مالک اور منتظمین اراکین اور دعوتوں کا انتظام کر سکتے ہیں۔",
        capacityLimited: "اراکین: {limit} میں سے {used}",
        capacityUnlimited: "اراکین: {used} (لامحدود)",
        capacityPending: "زیر التوا دعوتیں: {n}",
        capacityFull: "آپ اپنے موجودہ پلان میں اراکین کی حد تک پہنچ چکے ہیں۔",
        upgradeLink: "پلان اپ گریڈ کریں",
        roleOwner: "مالک",
        roleAdmin: "منتظم",
        roleMember: "رکن",
        roleLabel: "کردار",
        statusInvited: "سائن ان کا انتظار",
        you: "آپ",
        emailLabel: "ای میل",
        joinedLabel: "شمولیت کی تاریخ",
        changeRoleLabel: "کردار تبدیل کریں",
        removeBtn: "ہٹائیں",
        confirmRemove: "کیا آپ {name} کو ٹیم سے ہٹانا چاہتے ہیں؟",
        memberRemoved: "رکن ہٹا دیا گیا۔",
        roleUpdated: "کردار اپ ڈیٹ ہو گیا۔",
        inviteTitle: "نئے رکن کو دعوت دیں",
        inviteIntro: "رکن کا ای میل درج کریں اور اس کا کردار منتخب کریں۔ اگر وہ پلیٹ فارم پر رجسٹرڈ ہے تو اسے فورا بیل میں اطلاع ملے گی، اور ایپ کھولتے ہی ٹیم میں شامل ہو جائے گا۔ ورنہ اسے سائن ان لنک بھیجیں:",
        copyLinkBtn: "سائن ان لنک کاپی کریں",
        linkCopied: "لنک کاپی ہو گیا۔",
        inviteEmailPlaceholder: "رکن کا ای میل ایڈریس",
        inviteBtn: "دعوت دیں",
        lookupTitle: "یا رجسٹرڈ صارفین میں سے",
        inviteByEmailTitle: "ای میل سے",
        lookupBtn: "صارفین دکھائیں",
        lookupPlaceholder: "ای میل، موبائل یا صارف نمبر",
        lookupNone: "کوئی صارف نہیں ملا۔ آپ ای میل سے دعوت دے سکتے ہیں۔",
        inviteSending: "شامل کیا جا رہا ہے...",
        inviteCreated: "{email} کے لیے دعوت شامل کر دی گئی، سائن ان کرتے ہی وہ خود بخود شامل ہو جائے گا۔",
        workloadTitle: "کام کی تقسیم",
        workloadIntro: "کام کو رکن پر گھسیٹیں۔",
        rasiTitle: "RASI میٹرکس",
        rasiIntro: "ہر مقدمے، خلاف ورزی یا کام کے لیے: کون کرتا ہے (R)، کون منظور اور جواب دہ ہے (A — صرف ایک)، کون معاونت کرتا ہے (S)، کسے مطلع رکھا جائے (I)۔ کردار بدلنے کے لیے خانہ دبائیں؛ متعلقہ شخص کو فورا اطلاع ملتی ہے۔",
        rasiLegendR: "ذمہ دار",
        rasiLegendA: "منظور کنندہ",
        rasiLegendS: "معاون",
        rasiLegendI: "مطلع",
        rasiSearch: "عنوان یا نمبر سے تلاش",
        rasiEmpty: "دکھانے کے لیے کوئی کھلا آئٹم نہیں۔",
        rasiItemCol: "آئٹم",
        rasiSaved: "کردار محفوظ ہو گیا۔",
        rasiNoMembers: "پہلے ٹیم میں ارکان شامل کریں۔",
        quickTitle: "فوری تقسیم",
        quickHint: "آئٹم پر رکن کا نام دبائیں: ایک بار = ذمہ دار (R) اور آپ خود بخود منظور کنندہ (A)، دوسری بار = معاون (S)، تیسری بار = ہٹائیں۔",
        rasiShowMatrix: "مکمل میٹرکس دکھائیں",
        rasiHideMatrix: "میٹرکس چھپائیں",
        quickAddTitle: "فوری اندراج",
        quickAddHint: "جیسے آپ کہتے ہیں ویسے لکھیں: «مقدمہ 4521 کی سماعت، الابراج، اتوار 10 بجے، احمد کے لیے» — قسم، تاریخ، کلائنٹ، مقدمہ نمبر اور ذمہ دار سمجھ کر ایک ہی بار میں درج اور تقسیم ہو جاتا ہے۔",
        quickAddBtn: "شامل کریں",
        quickAddPh: "کام، ذمہ دار اور وقت لکھیں…",
        quickAddNobody: "ابھی کوئی ذمہ دار نہیں",
        quickAddParsing: "سمجھ رہا ہوں…",
        quickAddDone: "«{title}» درج ہو گیا{who}۔",
        quickAddNoTitle: "اس متن سے کوئی کام سمجھ نہیں آیا — کم از کم عنوان لکھیں۔",
        quickAddNeedsParent: "یہ کام کس مقدمے یا خلاف ورزی سے متعلق ہے؟ — کوئی کام الگ نہیں۔",
        quickAddLink: "منسلک کریں اور درج کریں",
        unassignedTitle: "بغیر ذمہ دار کام",
        unassignedEmpty: "تمام کام تفویض ہو چکے ہیں۔",
        wlOpen: "جاری",
        wlOverdue: "تاخیر شدہ",
        wlDone: "مکمل",
        assignTo: "تفویض کریں",
        assignPick: "رکن منتخب کریں",
        assignDone: "{name} کے سپرد کر دیا گیا۔",
        unassign: "بغیر ذمہ دار",
        noDue: "کوئی تاریخ نہیں",
        chatTitle: "ٹیم رابطہ",
        chatThreads: "گفتگوئیں",
        chatTeam: "پوری ٹیم",
        chatTeamHint: "سب کو",
        chatPrivate: "نجی",
        chatPlaceholder: "پیغام لکھیں... (Enter بھیجنے کے لیے، Shift+Enter نئی سطر)",
        chatSend: "بھیجیں",
        chatSendFile: "فائل بھیجیں",
        chatCancel: "منسوخ",
        chatFiles: "📁 فائلیں",
        chatFilesEmpty: "اس گفتگو میں ابھی کوئی فائل نہیں۔",
        chatDownload: "ڈاؤن لوڈ",
        chatFileNoLink: "کسی مقدمے سے منسلک نہیں",
        chatFileTooBig: "فائل 25 MB سے بڑی ہے۔",
        chatUploading: "اپ لوڈ ہو رہی ہے…",
        chatEmpty: "ابھی کوئی پیغام نہیں۔",
        chatLoadError: "پیغامات لوڈ نہیں ہو سکے۔",
        chatDelete: "حذف کریں",
        chatConfirmDelete: "یہ پیغام حذف کریں؟",
        chatUnread: "{n} نئے",
        chatToday: "آج",
        chatLive: "لائیو",
        chatOffline: "دوبارہ جوڑا جا رہا ہے...",
        invitationsTitle: "زیر التوا دعوتیں",
        invitationsEmpty: "کوئی زیر التوا دعوت نہیں۔",
        invitedOn: "شامل کی گئی: {date}",
        cancelInviteBtn: "منسوخ کریں",
        confirmCancelInvite: "کیا آپ {email} کی دعوت منسوخ کرنا چاہتے ہیں؟",
        inviteCancelled: "دعوت منسوخ کر دی گئی۔",
        invalidEmail: "درست ای میل ایڈریس درج کریں۔",
        alreadyMember: "یہ ای میل پہلے ہی ٹیم کے ایک رکن کا ہے۔",
        alreadyInvited: "اس ای میل کے لیے پہلے ہی ایک دعوت زیر التوا ہے۔",
        notAllowed: "آپ کو یہ کارروائی کرنے کی اجازت نہیں ہے۔",
        genericError: "کچھ غلط ہو گیا، براہ کرم دوبارہ کوشش کریں۔",
        planLimitMembers: "آپ اپنے موجودہ پلان میں اراکین کی حد تک پہنچ چکے ہیں، مزید شامل کرنے کے لیے پلان اپ گریڈ کریں۔",
        copyrightLine2: "جملہ حقوق محفوظ ہیں",
        aboutLink: "ہمارے بارے میں",
        termsLink: "استعمال کی شرائط",
        pricingLink: "پلانز اور قیمتیں",
        privacyLink: "رازداری کی پالیسی",
        loginLink: "سائن ان",
        dashboardLink: "ڈیش بورڈ",
        contactLink: "ہم سے رابطہ کریں",
        language: "زبان",
        appearance: "ظہور",
        light: "روشن",
        dark: "اندھیرا"
      }
    };

