    const translations = {
      ar: {
        apiCopy: "نسخ",
        apiTitle: "ربط المنصات (API)",
        apiIntro: "مفتاح لكل منصة. يظهر مرة واحدة عند إنشائه.",
        apiCreate: "إنشاء مفتاح",
        apiDocs: "طريقة الاستخدام",
        apiRevoke: "إلغاء",
        apiCreated: "أنشئ المفتاح، انسخه الآن.",
        apiRevoked: "ألغي المفتاح.",
        apiNone: "لا مفاتيح بعد.",
        apiLastUsed: "آخر استخدام",
        title: "الإعدادات",
        intro: "إدارة ملفك الشخصي وقنوات التنبيه وقواعد التذكير والتقويم والاشتراك.",
        loading: "جاري التحميل...",
        serviceUnavailableTitle: "الخدمة قيد التجهيز",
        serviceUnavailableText: "نعمل حاليا على تجهيز الخدمة، حاول مرة أخرى لاحقا.",
        noOrg: "لا توجد شركة محددة، أنشئ شركتك أولا من لوحة التحكم.",
        genericError: "حدث خطأ، حاول مرة أخرى.",
        saved: "تم الحفظ.",
        deleted: "تم الحذف.",
        planLimitItems: "وصلت إلى الحد الأقصى لعدد العناصر في باقتك الحالية، رق باقتك لإضافة المزيد.",
        planLimitMembers: "وصلت إلى الحد الأقصى لعدد الأعضاء في باقتك الحالية، رق باقتك لإضافة المزيد.",
        profileTitle: "الملف الشخصي",
        fullNameLabel: "الاسم الكامل",
        fullNamePlaceholder: "اسمك الكامل",
        fullNameEnLabel: "الاسم بالإنجليزية",
        fullNameEnPlaceholder: "Full name in English",
        phoneLabel: "رقم الجوال",
        phonePlaceholder: "+9665xxxxxxx",
        phoneInvalid: "أدخل رقم جوال صحيحا، مثل ‎+9665xxxxxxx‎.",
        emailLabel: "البريد الإلكتروني",
        langLabel: "لغة الواجهة",
        tzLabel: "المنطقة الزمنية",
        timeFormatLabel: "صيغة الوقت",
        timeFormat24: "24 ساعة",
        timeFormat12: "12 ساعة (ص/م)",
        saveBtn: "حفظ",
        saving: "جاري الحفظ...",
        profileSaved: "تم حفظ الملف الشخصي.",
        channelsTitle: "قنوات التنبيه",
        channelsIntro: "اربط القنوات التي تريد استقبال التذكيرات عبرها. البريد الإلكتروني مفعل دائما.",
        chEmail: "البريد الإلكتروني",
        chTelegram: "تيليجرام",
        chWhatsapp: "واتساب",
        chSms: "الرسائل النصية",
        statusLinked: "مرتبط",
        statusPending: "بانتظار التحقق",
        statusNotLinked: "غير مرتبط",
        statusUnavailable: "غير متاح حاليا",
        planChannelLocked: "هذه القناة غير متاحة في باقتك الحالية.",
        genCodeBtn: "توليد رمز",
        regenCodeBtn: "توليد رمز جديد",
        testBtn: "إرسال رسالة تجريبية",
        unlinkBtn: "إلغاء الربط",
        linkBtn: "ربط الرقم",
        refreshBtn: "تحديث الحالة",
        smsPhoneLabel: "رقم الجوال بالصيغة الدولية",
        smsPhonePlaceholder: "+9665xxxxxxx",
        yourCode: "رمز الربط",
        tgInstruction: "افتح {bot} في تيليجرام وأرسل الأمر {command}",
        waInstruction: "أرسل الرمز {code} إلى الرقم {number} على واتساب.",
        openTelegram: "فتح تيليجرام",
        tgQrHint: "أو امسح الرمز بكاميرا الجوال لربط تيليجرام مباشرة",
        openWhatsapp: "فتح واتساب",
        testSending: "جاري الإرسال...",
        testSent: "أرسلت الرسالة التجريبية.",
        testFailed: "تعذر إرسال الرسالة التجريبية، حاول لاحقا.",
        testNotLinked: "القناة غير مرتبطة بعد.",
        unlinked: "تم إلغاء ربط القناة.",
        invalidPhone: "أدخل رقم الجوال بالصيغة الدولية، مثل +9665xxxxxxx",
        phoneLinked: "تم ربط الرقم.",
        codeGenerated: "تم توليد الرمز، أكمل خطوات الربط.",
        refreshed: "تم تحديث الحالة.",
        tgLinked: "تم ربط تيليجرام بحسابك.",
        tgLinkFailed: "تعذر ربط تيليجرام، افتح البوت واضغط الزر مرة أخرى.",
        rulesTitle: "قواعد التذكير",
        rulesIntro: "حدد لكل سجل موعد التذكير والقنوات والمستلمين.",
        colTracker: "السجل",
        colOffset: "موعد التذكير",
        colChannels: "القنوات",
        colTarget: "المستلمون",
        colActions: "الإجراءات",
        off60: "قبل ساعة واحدة",
        off1440: "قبل يوم واحد",
        off4320: "قبل 3 أيام",
        off10080: "قبل 7 أيام",
        off43200: "قبل 30 يوما",
        offCustom: "قبل {n} دقيقة",
        targetAssignee: "المسؤول فقط",
        targetAll: "جميع الأعضاء",
        saveRuleBtn: "حفظ",
        deleteRuleBtn: "حذف",
        deleteRuleConfirm: "هل تريد حذف قاعدة التذكير لهذا السجل؟",
        ruleSaved: "تم حفظ قاعدة التذكير.",
        ruleDeleted: "تم حذف قاعدة التذكير.",
        noTrackers: "لا توجد سجلات بعد، أنشئ سجلا أولا.",
        ruleActive: "مفعلة",
        calendarTitle: "التقويم",
        calendarIntro: "أضف هذا الرابط إلى تقويم Google أو Apple أو Outlook لعرض مواعيدك تلقائيا.",
        copyUrlBtn: "نسخ الرابط",
        urlCopied: "تم نسخ الرابط.",
        copyFailed: "تعذر النسخ، انسخ الرابط يدويا.",
        regenerateBtn: "إعادة توليد الرابط",
        addToGoogle: "أضف إلى تقويم جوجل",
        addToApple: "أضف إلى تقويم آبل أو أوتلوك",
        regenerateConfirm: "سيتوقف الرابط القديم عن العمل. هل تريد المتابعة؟",
        calendarRegenerated: "تم توليد رابط جديد.",
        subscriptionTitle: "الاشتراك",
        storageTitle: "التخزين",
        storageUsage: "المستخدم من تخزين المنصة",
        storageDrive: "حفظ ملفاتي في Google Drive الخاص بي",
        storageDriveFolder: "المجلد في درايفك:",
        storageDriveHint: "عند التفعيل ينشئ TheTracker مجلدا باسم «TheTracker / اسم شركتك» داخل Google Drive الخاص بك، ويحفظ فيه كل ملف ترفعه (مرفقات القضايا والمخالفات، المستندات، ملفات الدردشة) كملف عادي تراه وتفتحه من درايفك، ويحتفظ الموقع برابطه فقط. يشارك المجلد للقراءة مع أعضاء شركتك، ولا يحتسب من حصة الباقة.",
        storageDriveOn: "فعال: ملفاتك الجديدة تحفظ في مجلد TheTracker داخل درايفك.",
        storageDriveOff: "غير فعال: الملفات تحفظ في تخزين المنصة.",
        storageDriveUnavailable: "Google Drive غير متاح على المنصة حاليا.",
        storageDriveDenied: "لم يمنح الإذن، فبقي التخزين على المنصة.",
        storageFull: "المساحة المجانية للأساسيات تكاد تكتمل: فعل Google Drive مجانا أو رق الباقة.",
        currentPlanLabel: "الباقة الحالية",
        expiresLabel: "تاريخ الانتهاء",
        noExpiry: "بلا تاريخ انتهاء",
        limitMembers: "الأعضاء",
        limitItems: "العناصر",
        limitChannels: "القنوات",
        limitImports: "عمليات الاستيراد شهريا",
        unlimited: "غير محدود",
        upgradeBtn: "طلب ترقية",
        save: "حفظ",
        orgProfileTitle: "بيانات المنشأة",
        orgProfileNote: "تظهر على الفواتير والتقارير، وتحدد أوراقك المطلوبة.",
        opEntityType: "نوع المنشأة",
        opTypeCompany: "شركة",
        opTypeEstablishment: "مؤسسة فردية",
        opTypeFreelance: "وثيقة عمل حر",
        opTypeIndividual: "شخص",
        opFullName: "الاسم الكامل",
        opTypeNonprofit: "جمعية أو منظمة غير ربحية",
        opTypeGovernment: "جهة حكومية",
        opLegalName: "الاسم النظامي",
        opCr: "رقم السجل التجاري",
        opVat: "الرقم الضريبي",
        opUnified: "الرقم الموحد",
        opLicense: "رقم الترخيص المهني",
        opPhone: "هاتف المنشأة",
        opEmail: "بريد المنشأة",
        opWebsite: "الموقع الإلكتروني",
        opShortAddress: "العنوان الوطني المختصر",
        opBadShortAddress: "العنوان المختصر 4 أحرف لاتينية ثم 4 أرقام، مثل RRRD2929.",
        opBank: "البنك",
        opIban: "الآيبان",
        opAccountName: "اسم صاحب الحساب",
        opSaved: "حفظت بيانات المنشأة.",
        opAdminOnly: "التعديل للمالك والمشرف فقط.",
        opBadIban: "الآيبان يبدأ بـ SA ويتكون من 24 خانة.",
        opBadVat: "الرقم الضريبي 15 رقما يبدأ وينتهي بالرقم 3.",
        orgCardTitle: "الشركة",
        orgSaved: "تم حفظ اسم الشركة.",
        deleteOrgBtn: "حذف الشركة",
        deleteOrgConfirm: "ستحذف الشركة «{name}» وكل عناصرها وسجلاتها نهائيا. هل تتابع؟",
        upgradeSent: "أرسلنا طلبك، سيصلك التفعيل بعد المراجعة.",
        reqStatus_pending: "قيد المراجعة",
        reqStatus_approved: "مفعل",
        reqStatus_rejected: "مرفوض",
        reqStatus_cancelled: "ملغى",
        upgradeSubject: "طلب ترقية الباقة",
        signOutTitle: "تسجيل الخروج",
        signOutText: "يمكنك تسجيل الدخول مرة أخرى في أي وقت.",
        signOutBtn: "تسجيل الخروج",
        signingOut: "جاري تسجيل الخروج...",
        backBtn: "العودة إلى لوحة التحكم",
        copyrightLine2: "جميع الحقوق محفوظة",
        aboutLink: "من نحن",
        termsLink: "شروط الاستخدام",
        pricingLink: "الباقات والأسعار",
        privacyLink: "سياسة الخصوصية",
        loginLink: "تسجيل الدخول",
        dashboardLink: "لوحة التحكم",
        contactLink: "تواصل معنا",
        language: "اللغة",
        appearance: "المظهر",
        light: "فاتح",
        dark: "داكن"
      },
      en: {
        apiCopy: "Copy",
        apiTitle: "Integrations (API)",
        apiIntro: "One key per platform. Shown once when created.",
        apiCreate: "Create key",
        apiDocs: "How to use",
        apiRevoke: "Revoke",
        apiCreated: "Key created — copy it now.",
        apiRevoked: "Key revoked.",
        apiNone: "No keys yet.",
        apiLastUsed: "Last used",
        title: "Settings",
        intro: "Manage your profile, notification channels, reminder rules, calendar and subscription.",
        loading: "Loading...",
        serviceUnavailableTitle: "Service is being prepared",
        serviceUnavailableText: "We are setting up the service. Please try again later.",
        noOrg: "No company selected. Create your company first from the dashboard.",
        genericError: "Something went wrong. Please try again.",
        saved: "Saved.",
        deleted: "Deleted.",
        planLimitItems: "You have reached the item limit of your current plan. Upgrade to add more.",
        planLimitMembers: "You have reached the member limit of your current plan. Upgrade to add more.",
        profileTitle: "Profile",
        fullNameLabel: "Full name",
        fullNamePlaceholder: "Your full name",
        fullNameEnLabel: "Name in English",
        fullNameEnPlaceholder: "Full name in English",
        phoneLabel: "Phone number",
        phonePlaceholder: "+9665xxxxxxx",
        phoneInvalid: "Enter a valid phone number, e.g. +9665xxxxxxx.",
        emailLabel: "Email address",
        langLabel: "Interface language",
        tzLabel: "Time zone",
        timeFormatLabel: "Time format",
        timeFormat24: "24-hour",
        timeFormat12: "12-hour (AM/PM)",
        saveBtn: "Save",
        saving: "Saving...",
        profileSaved: "Profile saved.",
        channelsTitle: "Notification channels",
        channelsIntro: "Link the channels you want to receive reminders on. Email is always enabled.",
        chEmail: "Email",
        chTelegram: "Telegram",
        chWhatsapp: "WhatsApp",
        chSms: "SMS",
        statusLinked: "Linked",
        statusPending: "Awaiting verification",
        statusNotLinked: "Not linked",
        statusUnavailable: "Not available right now",
        planChannelLocked: "This channel is not included in your current plan.",
        genCodeBtn: "Generate code",
        regenCodeBtn: "Generate a new code",
        testBtn: "Send a test message",
        unlinkBtn: "Unlink",
        linkBtn: "Link number",
        refreshBtn: "Refresh status",
        smsPhoneLabel: "Phone number in international format",
        smsPhonePlaceholder: "+9665xxxxxxx",
        yourCode: "Linking code",
        tgInstruction: "Open {bot} in Telegram and send the command {command}",
        waInstruction: "Send the code {code} to {number} on WhatsApp.",
        openTelegram: "Open Telegram",
        tgQrHint: "Or scan with your phone camera to link Telegram directly",
        openWhatsapp: "Open WhatsApp",
        testSending: "Sending...",
        testSent: "Test message sent.",
        testFailed: "The test message could not be sent. Please try again later.",
        testNotLinked: "This channel is not linked yet.",
        unlinked: "Channel unlinked.",
        invalidPhone: "Enter your phone number in international format, e.g. +9665xxxxxxx",
        phoneLinked: "Number linked.",
        codeGenerated: "Code generated. Complete the linking steps.",
        refreshed: "Status refreshed.",
        tgLinked: "Telegram is now linked to your account.",
        tgLinkFailed: "Telegram could not be linked — open the bot and tap the button again.",
        rulesTitle: "Reminder rules",
        rulesIntro: "Set the reminder time, channels and recipients for each tracker.",
        colTracker: "Tracker",
        colOffset: "Reminder time",
        colChannels: "Channels",
        colTarget: "Recipients",
        colActions: "Actions",
        off60: "1 hour before",
        off1440: "1 day before",
        off4320: "3 days before",
        off10080: "7 days before",
        off43200: "30 days before",
        offCustom: "{n} minutes before",
        targetAssignee: "Assignee only",
        targetAll: "All members",
        saveRuleBtn: "Save",
        deleteRuleBtn: "Delete",
        deleteRuleConfirm: "Delete the reminder rule for this tracker?",
        ruleSaved: "Reminder rule saved.",
        ruleDeleted: "Reminder rule deleted.",
        noTrackers: "No trackers yet. Create a tracker first.",
        ruleActive: "Active",
        calendarTitle: "Calendar",
        calendarIntro: "Add this link to Google, Apple or Outlook Calendar to see your due dates automatically.",
        copyUrlBtn: "Copy link",
        urlCopied: "Link copied.",
        copyFailed: "Could not copy. Please copy the link manually.",
        regenerateBtn: "Regenerate link",
        addToGoogle: "Add to Google Calendar",
        addToApple: "Add to Apple Calendar or Outlook",
        regenerateConfirm: "The old link will stop working. Continue?",
        calendarRegenerated: "A new link was generated.",
        subscriptionTitle: "Subscription",
        storageTitle: "Storage",
        storageUsage: "Platform storage used",
        storageDrive: "Save my files to my own Google Drive",
        storageDriveFolder: "Folder in your Drive:",
        storageDriveHint: "When enabled, TheTracker creates a folder named \"TheTracker / your company\" in your own Google Drive and saves every file you upload there (case and violation attachments, documents, chat files) as a normal file you can open from Drive; the platform keeps only its link. The folder is shared read-only with your team and is not counted against the plan quota.",
        storageDriveOn: "On: new files are saved in the TheTracker folder in your Drive.",
        storageDriveOff: "Off: files stay in platform storage.",
        storageDriveUnavailable: "Google Drive is not available on the platform yet.",
        storageDriveDenied: "Permission was not granted; storage stays on the platform.",
        storageFull: "The free space for essentials is almost full: enable Google Drive for free or upgrade the plan.",
        currentPlanLabel: "Current plan",
        expiresLabel: "Expires on",
        noExpiry: "No expiry date",
        limitMembers: "Members",
        limitItems: "Items",
        limitChannels: "Channels",
        limitImports: "Imports per month",
        unlimited: "Unlimited",
        upgradeBtn: "Request an upgrade",
        save: "Save",
        orgProfileTitle: "Organization details",
        orgProfileNote: "Shown on invoices and reports; sets the papers expected.",
        opEntityType: "Entity type",
        opTypeCompany: "Company",
        opTypeEstablishment: "Sole establishment",
        opTypeFreelance: "Freelance permit",
        opTypeIndividual: "Individual",
        opFullName: "Full name",
        opTypeNonprofit: "Non-profit",
        opTypeGovernment: "Government body",
        opLegalName: "Legal name",
        opCr: "Commercial register number",
        opVat: "VAT number",
        opUnified: "Unified number",
        opLicense: "Professional licence number",
        opPhone: "Organization phone",
        opEmail: "Organization email",
        opWebsite: "Website",
        opShortAddress: "Short national address",
        opBadShortAddress: "The short address is 4 letters then 4 digits, e.g. RRRD2929.",
        opBank: "Bank",
        opIban: "IBAN",
        opAccountName: "Account holder",
        opSaved: "Organization details saved.",
        opAdminOnly: "Only the owner and admins can edit.",
        opBadIban: "A Saudi IBAN starts with SA and is 24 characters.",
        opBadVat: "A VAT number is 15 digits starting and ending with 3.",
        orgCardTitle: "Company",
        orgSaved: "Company name saved.",
        deleteOrgBtn: "Delete company",
        deleteOrgConfirm: "«{name}» and all of its items will be permanently deleted. Continue?",
        upgradeSent: "Request sent. Your plan is activated once it is reviewed.",
        reqStatus_pending: "Under review",
        reqStatus_approved: "Activated",
        reqStatus_rejected: "Rejected",
        reqStatus_cancelled: "Cancelled",
        upgradeSubject: "Plan upgrade request",
        signOutTitle: "Sign out",
        signOutText: "You can sign in again at any time.",
        signOutBtn: "Sign out",
        signingOut: "Signing out...",
        backBtn: "Back to dashboard",
        copyrightLine2: "All rights reserved",
        aboutLink: "About Us",
        termsLink: "Terms of Use",
        pricingLink: "Plans & Pricing",
        privacyLink: "Privacy Policy",
        loginLink: "Sign in",
        dashboardLink: "Dashboard",
        contactLink: "Contact Us",
        language: "Language",
        appearance: "Appearance",
        light: "Light",
        dark: "Dark"
      },
      fr: {
        apiCopy: "Copier",
        apiTitle: "Intégrations (API)",
        apiIntro: "Une clé par plateforme. Affichée une seule fois.",
        apiCreate: "Créer une clé",
        apiDocs: "Mode d'emploi",
        apiRevoke: "Révoquer",
        apiCreated: "Clé créée — copiez-la maintenant.",
        apiRevoked: "Clé révoquée.",
        apiNone: "Aucune clé.",
        apiLastUsed: "Dernière utilisation",
        title: "Paramètres",
        intro: "Gérez votre profil, vos canaux de notification, vos règles de rappel, votre calendrier et votre abonnement.",
        loading: "Chargement...",
        serviceUnavailableTitle: "Service en cours de préparation",
        serviceUnavailableText: "Nous préparons le service. Veuillez réessayer plus tard.",
        noOrg: "Aucune entreprise sélectionnée. Créez d'abord votre entreprise depuis le tableau de bord.",
        genericError: "Une erreur est survenue. Veuillez réessayer.",
        saved: "Enregistré.",
        deleted: "Supprimé.",
        planLimitItems: "Vous avez atteint la limite d'éléments de votre forfait actuel. Passez à un forfait supérieur pour en ajouter.",
        planLimitMembers: "Vous avez atteint la limite de membres de votre forfait actuel. Passez à un forfait supérieur pour en ajouter.",
        profileTitle: "Profil",
        fullNameLabel: "Nom complet",
        fullNamePlaceholder: "Votre nom complet",
        fullNameEnLabel: "Nom en anglais",
        fullNameEnPlaceholder: "Nom complet en anglais",
        phoneLabel: "Numéro de téléphone",
        phonePlaceholder: "+9665xxxxxxx",
        phoneInvalid: "Entrez un numéro de téléphone valide, ex. +9665xxxxxxx.",
        emailLabel: "Adresse e-mail",
        langLabel: "Langue de l'interface",
        tzLabel: "Fuseau horaire",
        timeFormatLabel: "Format de l'heure",
        timeFormat24: "24 heures",
        timeFormat12: "12 heures (AM/PM)",
        saveBtn: "Enregistrer",
        saving: "Enregistrement...",
        profileSaved: "Profil enregistré.",
        channelsTitle: "Canaux de notification",
        channelsIntro: "Liez les canaux sur lesquels vous souhaitez recevoir les rappels. L'e-mail est toujours activé.",
        chEmail: "E-mail",
        chTelegram: "Telegram",
        chWhatsapp: "WhatsApp",
        chSms: "SMS",
        statusLinked: "Lié",
        statusPending: "En attente de vérification",
        statusNotLinked: "Non lié",
        statusUnavailable: "Indisponible pour le moment",
        planChannelLocked: "Ce canal n'est pas inclus dans votre forfait actuel.",
        genCodeBtn: "Générer un code",
        regenCodeBtn: "Générer un nouveau code",
        testBtn: "Envoyer un message test",
        unlinkBtn: "Dissocier",
        linkBtn: "Lier le numéro",
        refreshBtn: "Actualiser l'état",
        smsPhoneLabel: "Numéro de téléphone au format international",
        smsPhonePlaceholder: "+9665xxxxxxx",
        yourCode: "Code de liaison",
        tgInstruction: "Ouvrez {bot} dans Telegram et envoyez la commande {command}",
        waInstruction: "Envoyez le code {code} au numéro {number} sur WhatsApp.",
        openTelegram: "Ouvrir Telegram",
        tgQrHint: "Ou scannez avec l’appareil photo du téléphone pour lier Telegram directement",
        openWhatsapp: "Ouvrir WhatsApp",
        testSending: "Envoi en cours...",
        testSent: "Message test envoyé.",
        testFailed: "Le message test n'a pas pu être envoyé. Veuillez réessayer plus tard.",
        testNotLinked: "Ce canal n'est pas encore lié.",
        unlinked: "Canal dissocié.",
        invalidPhone: "Saisissez votre numéro au format international, par exemple +9665xxxxxxx",
        phoneLinked: "Numéro lié.",
        codeGenerated: "Code généré. Terminez les étapes de liaison.",
        refreshed: "Statut actualisé.",
        tgLinked: "Telegram est maintenant lié à votre compte.",
        tgLinkFailed: "Impossible de lier Telegram — ouvrez le bot et appuyez de nouveau sur le bouton.",
        rulesTitle: "Règles de rappel",
        rulesIntro: "Définissez pour chaque suivi le moment du rappel, les canaux et les destinataires.",
        colTracker: "Suivi",
        colOffset: "Moment du rappel",
        colChannels: "Canaux",
        colTarget: "Destinataires",
        colActions: "Actions",
        off60: "1 heure avant",
        off1440: "1 jour avant",
        off4320: "3 jours avant",
        off10080: "7 jours avant",
        off43200: "30 jours avant",
        offCustom: "{n} minutes avant",
        targetAssignee: "Responsable uniquement",
        targetAll: "Tous les membres",
        saveRuleBtn: "Enregistrer",
        deleteRuleBtn: "Supprimer",
        deleteRuleConfirm: "Supprimer la règle de rappel de ce suivi ?",
        ruleSaved: "Règle de rappel enregistrée.",
        ruleDeleted: "Règle de rappel supprimée.",
        noTrackers: "Aucun suivi pour le moment. Créez d'abord un suivi.",
        ruleActive: "Active",
        calendarTitle: "Calendrier",
        calendarIntro: "Ajoutez ce lien à Google Agenda, Apple Calendrier ou Outlook pour voir vos échéances automatiquement.",
        copyUrlBtn: "Copier le lien",
        urlCopied: "Lien copié.",
        copyFailed: "Copie impossible. Veuillez copier le lien manuellement.",
        regenerateBtn: "Régénérer le lien",
        addToGoogle: "Ajouter à Google Agenda",
        addToApple: "Ajouter à Apple Calendar ou Outlook",
        regenerateConfirm: "L'ancien lien cessera de fonctionner. Continuer ?",
        calendarRegenerated: "Un nouveau lien a été généré.",
        subscriptionTitle: "Abonnement",
        storageTitle: "Stockage",
        storageUsage: "Stockage plateforme utilisé",
        storageDrive: "Enregistrer mes fichiers dans mon Google Drive",
        storageDriveFolder: "Dossier dans votre Drive :",
        storageDriveHint: "Une fois activé, TheTracker crée un dossier « TheTracker / votre société » dans votre Google Drive et y enregistre chaque fichier téléversé (pièces des dossiers et infractions, documents, fichiers du chat) comme un fichier normal ; la plateforme n'en garde que le lien. Le dossier est partagé en lecture avec votre équipe et hors quota du forfait.",
        storageDriveOn: "Activé : les nouveaux fichiers vont dans le dossier TheTracker de votre Drive.",
        storageDriveOff: "Désactivé : les fichiers restent sur la plateforme.",
        storageDriveUnavailable: "Google Drive n'est pas encore disponible sur la plateforme.",
        storageDriveDenied: "Autorisation refusée ; le stockage reste sur la plateforme.",
        storageFull: "L'espace gratuit pour l'essentiel est presque plein : activez Google Drive gratuitement ou changez de forfait.",
        currentPlanLabel: "Forfait actuel",
        expiresLabel: "Date d'expiration",
        noExpiry: "Sans date d'expiration",
        limitMembers: "Membres",
        limitItems: "Éléments",
        limitChannels: "Canaux",
        limitImports: "Importations par mois",
        unlimited: "Illimité",
        upgradeBtn: "Demander une mise à niveau",
        save: "Enregistrer",
        orgProfileTitle: "Informations de l'entité",
        orgProfileNote: "Affichées sur factures et rapports ; définissent vos documents.",
        opEntityType: "Type d'entité",
        opTypeCompany: "Société",
        opTypeEstablishment: "Établissement individuel",
        opTypeFreelance: "Travail indépendant",
        opTypeIndividual: "Particulier",
        opFullName: "Nom complet",
        opTypeNonprofit: "Association",
        opTypeGovernment: "Organisme public",
        opLegalName: "Raison sociale",
        opCr: "Numéro de registre de commerce",
        opVat: "Numéro de TVA",
        opUnified: "Numéro unifié",
        opLicense: "Numéro de licence professionnelle",
        opPhone: "Téléphone",
        opEmail: "E-mail",
        opWebsite: "Site web",
        opShortAddress: "Adresse nationale courte",
        opBadShortAddress: "L'adresse courte : 4 lettres puis 4 chiffres, ex. RRRD2929.",
        opBank: "Banque",
        opIban: "IBAN",
        opAccountName: "Titulaire du compte",
        opSaved: "Informations enregistrées.",
        opAdminOnly: "Seuls le propriétaire et les administrateurs peuvent modifier.",
        opBadIban: "Un IBAN saoudien commence par SA et compte 24 caractères.",
        opBadVat: "Le numéro de TVA comporte 15 chiffres commençant et finissant par 3.",
        orgCardTitle: "Entreprise",
        orgSaved: "Nom de l'entreprise enregistré.",
        deleteOrgBtn: "Supprimer l'entreprise",
        deleteOrgConfirm: "«{name}» et tous ses éléments seront supprimés. Continuer ?",
        upgradeSent: "Demande envoyée. Votre forfait sera activé après examen.",
        reqStatus_pending: "En cours d'examen",
        reqStatus_approved: "Activé",
        reqStatus_rejected: "Refusé",
        reqStatus_cancelled: "Annulé",
        upgradeSubject: "Demande de mise à niveau du forfait",
        signOutTitle: "Déconnexion",
        signOutText: "Vous pouvez vous reconnecter à tout moment.",
        signOutBtn: "Se déconnecter",
        signingOut: "Déconnexion en cours...",
        backBtn: "Retour au tableau de bord",
        copyrightLine2: "Tous droits réservés",
        aboutLink: "À propos",
        termsLink: "Conditions d'utilisation",
        pricingLink: "Forfaits et tarifs",
        privacyLink: "Politique de confidentialité",
        loginLink: "Connexion",
        dashboardLink: "Tableau de bord",
        contactLink: "Contactez-nous",
        language: "Langue",
        appearance: "Apparence",
        light: "Clair",
        dark: "Sombre"
      },
      ur: {
        apiCopy: "کاپی",
        apiTitle: "انضمام (API)",
        apiIntro: "ہر پلیٹ فارم کے لیے ایک کلید۔ صرف ایک بار دکھائی جاتی ہے۔",
        apiCreate: "کلید بنائیں",
        apiDocs: "استعمال کا طریقہ",
        apiRevoke: "منسوخ",
        apiCreated: "کلید بن گئی، ابھی کاپی کریں۔",
        apiRevoked: "کلید منسوخ۔",
        apiNone: "ابھی کوئی کلید نہیں۔",
        apiLastUsed: "آخری استعمال",
        title: "ترتیبات",
        intro: "اپنی پروفائل، اطلاعاتی چینلز، یاد دہانی کے اصول، کیلنڈر اور سبسکرپشن کا انتظام کریں۔",
        loading: "لوڈ ہو رہا ہے...",
        serviceUnavailableTitle: "سروس تیار کی جا رہی ہے",
        serviceUnavailableText: "ہم سروس تیار کر رہے ہیں، براہ کرم بعد میں دوبارہ کوشش کریں۔",
        noOrg: "کوئی کمپنی منتخب نہیں، پہلے ڈیش بورڈ سے اپنی کمپنی بنائیں۔",
        genericError: "کچھ غلط ہو گیا، براہ کرم دوبارہ کوشش کریں۔",
        saved: "محفوظ ہو گیا۔",
        deleted: "حذف ہو گیا۔",
        planLimitItems: "آپ اپنے موجودہ پلان میں آئٹمز کی حد تک پہنچ چکے ہیں، مزید شامل کرنے کے لیے پلان اپ گریڈ کریں۔",
        planLimitMembers: "آپ اپنے موجودہ پلان میں اراکین کی حد تک پہنچ چکے ہیں، مزید شامل کرنے کے لیے پلان اپ گریڈ کریں۔",
        profileTitle: "پروفائل",
        fullNameLabel: "پورا نام",
        fullNamePlaceholder: "آپ کا پورا نام",
        fullNameEnLabel: "انگریزی میں نام",
        fullNameEnPlaceholder: "انگریزی میں پورا نام",
        phoneLabel: "موبائل نمبر",
        phonePlaceholder: "+9665xxxxxxx",
        phoneInvalid: "درست موبائل نمبر درج کریں، مثلا +9665xxxxxxx۔",
        emailLabel: "ای میل ایڈریس",
        langLabel: "انٹرفیس کی زبان",
        tzLabel: "ٹائم زون",
        timeFormatLabel: "وقت کی صورت",
        timeFormat24: "24 گھنٹے",
        timeFormat12: "12 گھنٹے (AM/PM)",
        saveBtn: "محفوظ کریں",
        saving: "محفوظ کیا جا رہا ہے...",
        profileSaved: "پروفائل محفوظ ہو گئی۔",
        channelsTitle: "اطلاعاتی چینلز",
        channelsIntro: "وہ چینلز منسلک کریں جن پر آپ یاد دہانیاں وصول کرنا چاہتے ہیں۔ ای میل ہمیشہ فعال رہتا ہے۔",
        chEmail: "ای میل",
        chTelegram: "ٹیلیگرام",
        chWhatsapp: "واٹس ایپ",
        chSms: "ایس ایم ایس",
        statusLinked: "منسلک",
        statusPending: "تصدیق کا انتظار",
        statusNotLinked: "منسلک نہیں",
        statusUnavailable: "فی الحال دستیاب نہیں",
        planChannelLocked: "یہ چینل آپ کے موجودہ پلان میں شامل نہیں ہے۔",
        genCodeBtn: "کوڈ بنائیں",
        regenCodeBtn: "نیا کوڈ بنائیں",
        testBtn: "آزمائشی پیغام بھیجیں",
        unlinkBtn: "لنک ختم کریں",
        linkBtn: "نمبر منسلک کریں",
        refreshBtn: "حالت تازہ کریں",
        smsPhoneLabel: "بین الاقوامی فارمیٹ میں موبائل نمبر",
        smsPhonePlaceholder: "+9665xxxxxxx",
        yourCode: "لنکنگ کوڈ",
        tgInstruction: "ٹیلیگرام میں {bot} کھولیں اور یہ کمانڈ بھیجیں {command}",
        waInstruction: "کوڈ {code} واٹس ایپ پر نمبر {number} کو بھیجیں۔",
        openTelegram: "ٹیلیگرام کھولیں",
        tgQrHint: "یا ٹیلیگرام کو براہ راست منسلک کرنے کے لیے فون کے کیمرے سے اسکین کریں",
        openWhatsapp: "واٹس ایپ کھولیں",
        testSending: "بھیجا جا رہا ہے...",
        testSent: "آزمائشی پیغام بھیج دیا گیا۔",
        testFailed: "آزمائشی پیغام نہیں بھیجا جا سکا، براہ کرم بعد میں کوشش کریں۔",
        testNotLinked: "یہ چینل ابھی منسلک نہیں ہے۔",
        unlinked: "چینل کا لنک ختم کر دیا گیا۔",
        invalidPhone: "بین الاقوامی فارمیٹ میں موبائل نمبر درج کریں، مثلا +9665xxxxxxx",
        phoneLinked: "نمبر منسلک ہو گیا۔",
        codeGenerated: "کوڈ بن گیا، لنکنگ کے مراحل مکمل کریں۔",
        refreshed: "حالت تازہ ہو گئی۔",
        tgLinked: "ٹیلیگرام آپ کے اکاؤنٹ سے منسلک ہو گیا۔",
        tgLinkFailed: "ٹیلیگرام منسلک نہیں ہو سکا — بوٹ کھول کر بٹن دوبارہ دبائیں۔",
        rulesTitle: "یاد دہانی کے اصول",
        rulesIntro: "ہر ٹریکر کے لیے یاد دہانی کا وقت، چینلز اور وصول کنندگان مقرر کریں۔",
        colTracker: "ٹریکر",
        colOffset: "یاد دہانی کا وقت",
        colChannels: "چینلز",
        colTarget: "وصول کنندگان",
        colActions: "کارروائیاں",
        off60: "1 گھنٹہ پہلے",
        off1440: "1 دن پہلے",
        off4320: "3 دن پہلے",
        off10080: "7 دن پہلے",
        off43200: "30 دن پہلے",
        offCustom: "{n} منٹ پہلے",
        targetAssignee: "صرف ذمہ دار",
        targetAll: "تمام اراکین",
        saveRuleBtn: "محفوظ کریں",
        deleteRuleBtn: "حذف کریں",
        deleteRuleConfirm: "کیا آپ اس ٹریکر کی یاد دہانی کا اصول حذف کرنا چاہتے ہیں؟",
        ruleSaved: "یاد دہانی کا اصول محفوظ ہو گیا۔",
        ruleDeleted: "یاد دہانی کا اصول حذف ہو گیا۔",
        noTrackers: "ابھی کوئی ٹریکر نہیں، پہلے ایک ٹریکر بنائیں۔",
        ruleActive: "فعال",
        calendarTitle: "کیلنڈر",
        calendarIntro: "اپنی آخری تاریخیں خود بخود دیکھنے کے لیے یہ لنک Google، Apple یا Outlook کیلنڈر میں شامل کریں۔",
        copyUrlBtn: "لنک کاپی کریں",
        urlCopied: "لنک کاپی ہو گیا۔",
        copyFailed: "کاپی نہیں ہو سکا، براہ کرم لنک خود کاپی کریں۔",
        regenerateBtn: "نیا لنک بنائیں",
        addToGoogle: "گوگل کیلنڈر میں شامل کریں",
        addToApple: "ایپل کیلنڈر یا آؤٹ لک میں شامل کریں",
        regenerateConfirm: "پرانا لنک کام کرنا بند کر دے گا۔ کیا آپ جاری رکھنا چاہتے ہیں؟",
        calendarRegenerated: "نیا لنک بن گیا۔",
        subscriptionTitle: "سبسکرپشن",
        storageTitle: "اسٹوریج",
        storageUsage: "پلیٹ فارم اسٹوریج استعمال شدہ",
        storageDrive: "میری فائلیں میرے Google Drive میں محفوظ کریں",
        storageDriveFolder: "آپ کے Drive میں فولڈر:",
        storageDriveHint: "فعال کرنے پر TheTracker آپ کے Google Drive میں «TheTracker / آپ کی کمپنی» نام کا فولڈر بناتا ہے اور ہر اپلوڈ فائل (مقدمات اور خلاف ورزیوں کے منسلکات، دستاویزات، چیٹ فائلیں) وہاں عام فائل کی طرح محفوظ کرتا ہے؛ پلیٹ فارم صرف لنک رکھتا ہے۔ فولڈر ٹیم کے ساتھ صرف پڑھنے کے لیے شیئر ہوتا ہے اور پیکج کوٹے میں شمار نہیں۔",
        storageDriveOn: "فعال: نئی فائلیں آپ کے Drive کے TheTracker فولڈر میں محفوظ ہوتی ہیں۔",
        storageDriveOff: "غیر فعال: فائلیں پلیٹ فارم اسٹوریج میں رہتی ہیں۔",
        storageDriveUnavailable: "Google Drive ابھی پلیٹ فارم پر دستیاب نہیں۔",
        storageDriveDenied: "اجازت نہیں ملی، اسٹوریج پلیٹ فارم پر رہا۔",
        storageFull: "بنیادی دستاویزات کی مفت جگہ تقریبا بھر گئی: Google Drive مفت فعال کریں یا پیکج اپ گریڈ کریں۔",
        currentPlanLabel: "موجودہ پلان",
        expiresLabel: "ختم ہونے کی تاریخ",
        noExpiry: "ختم ہونے کی کوئی تاریخ نہیں",
        limitMembers: "اراکین",
        limitItems: "آئٹمز",
        limitChannels: "چینلز",
        limitImports: "ماہانہ امپورٹس",
        unlimited: "لامحدود",
        upgradeBtn: "اپ گریڈ کی درخواست",
        save: "محفوظ کریں",
        orgProfileTitle: "ادارے کی تفصیلات",
        orgProfileNote: "انوائسز اور رپورٹس پر؛ مطلوبہ کاغذات طے کرتی ہیں۔",
        opEntityType: "ادارے کی قسم",
        opTypeCompany: "کمپنی",
        opTypeEstablishment: "انفرادی ادارہ",
        opTypeFreelance: "فری لانس اجازت",
        opTypeIndividual: "انفرادی",
        opFullName: "پورا نام",
        opTypeNonprofit: "غیر منافع بخش ادارہ",
        opTypeGovernment: "سرکاری ادارہ",
        opLegalName: "قانونی نام",
        opCr: "تجارتی رجسٹر نمبر",
        opVat: "ٹیکس نمبر",
        opUnified: "متحدہ نمبر",
        opLicense: "پیشہ ورانہ لائسنس نمبر",
        opPhone: "ادارے کا فون",
        opEmail: "ادارے کا ای میل",
        opWebsite: "ویب سائٹ",
        opShortAddress: "مختصر قومی پتہ",
        opBadShortAddress: "مختصر پتہ 4 حروف پھر 4 ہندسے، مثلا RRRD2929۔",
        opBank: "بینک",
        opIban: "آئی بین",
        opAccountName: "اکاؤنٹ ہولڈر",
        opSaved: "ادارے کی تفصیلات محفوظ ہو گئیں۔",
        opAdminOnly: "صرف مالک اور منتظم ترمیم کر سکتے ہیں۔",
        opBadIban: "سعودی آئی بین SA سے شروع ہوتا ہے اور 24 حروف کا ہوتا ہے۔",
        opBadVat: "ٹیکس نمبر 15 ہندسوں کا ہے جو 3 سے شروع اور ختم ہوتا ہے۔",
        orgCardTitle: "کمپنی",
        orgSaved: "کمپنی کا نام محفوظ ہو گیا۔",
        deleteOrgBtn: "کمپنی حذف کریں",
        deleteOrgConfirm: "«{name}» اور اس کے تمام آئٹمز حذف ہو جائیں گے۔ جاری رکھیں؟",
        upgradeSent: "درخواست بھیج دی گئی۔ جائزے کے بعد پلان فعال ہو جائے گا۔",
        reqStatus_pending: "زیر جائزہ",
        reqStatus_approved: "فعال",
        reqStatus_rejected: "مسترد",
        reqStatus_cancelled: "منسوخ",
        upgradeSubject: "پلان اپ گریڈ کی درخواست",
        signOutTitle: "سائن آؤٹ",
        signOutText: "آپ کسی بھی وقت دوبارہ سائن ان کر سکتے ہیں۔",
        signOutBtn: "سائن آؤٹ",
        signingOut: "سائن آؤٹ ہو رہا ہے...",
        backBtn: "واپس ڈیش بورڈ",
        copyrightLine2: "جملہ حقوق محفوظ ہیں",
        aboutLink: "ہمارے بارے میں",
        termsLink: "استعمال کی شرائط",
        pricingLink: "پلانز اور قیمتیں",
        privacyLink: "رازداری کی پالیسی",
        loginLink: "سائن ان",
        dashboardLink: "ڈیش بورڈ",
        contactLink: "ہم سے رابطہ کریں",
        language: "زبان",
        appearance: "ظہور",
        light: "روشن",
        dark: "اندھیرا"
      }
    };

    const lang = () => localStorage.getItem("tracker_lang") || "ar";
    const theme = () => localStorage.getItem("tracker_theme") || "dark";
    const langNames = { ar: "العربية", en: "English", fr: "Français", ur: "اردو" };
    let l = lang();
    document.documentElement.lang = l;
    document.documentElement.dir = (l === "ar" || l === "ur") ? "rtl" : "ltr";

    const placeholderKeys = { fullName: "fullNamePlaceholder", fullNameEn: "fullNameEnPlaceholder", profilePhone: "phonePlaceholder", smsPhone: "smsPhonePlaceholder" };
    function applyPlaceholders(code) {
      const dict = translations[code] || translations.ar;
      Object.keys(placeholderKeys).forEach(id => {
        const el = document.getElementById(id);
        if (el && dict[placeholderKeys[id]]) el.placeholder = dict[placeholderKeys[id]];
      });
    }

    function setLang(code) {
      localStorage.setItem("tracker_lang", code);
      l = code;
      document.documentElement.lang = code;
      document.documentElement.dir = (code === "ar" || code === "ur") ? "rtl" : "ltr";
      document.getElementById("currentLangDisplay").textContent = langNames[code] || code;
      ["ar","en","fr","ur"].forEach(c => {
        const el = document.getElementById("check-" + c);
        if (el) el.style.display = c === code ? "inline" : "none";
      });
      const th = theme();
      document.getElementById("currentThemeDisplay").textContent = translations[code][th === "dark" ? "dark" : "light"];
      document.querySelectorAll("[data-i18n]").forEach(el => {
        const k = el.dataset.i18n;
        if (translations[code] && translations[code][k]) el.innerHTML = translations[code][k];
      });
      applyPlaceholders(code);
      document.title = (translations[code] && translations[code].title ? translations[code].title : "Settings") + " | TheTracker";
      if (typeof window.__trackerAuthRefresh === "function") window.__trackerAuthRefresh();
      if (typeof window.__settingsRerender === "function") window.__settingsRerender();
    }

    function setTheme(th) {
      localStorage.setItem("tracker_theme", th);
      document.documentElement.dataset.theme = th;
      const meta = document.getElementById("themeColorMeta");
      if (meta) meta.content = th === "dark" ? "#1a2933" : "#0068b8";
      const logo = document.getElementById("footerLogo");
      if (logo) logo.src = th === "dark" ? "/tracker-logo-full-dark.png?v=2" : "/tracker-logo-full-light.png?v=2";
      document.getElementById("themeIcon").textContent = th === "dark" ? "🌙" : "☀️";
      document.getElementById("currentThemeDisplay").textContent = translations[l][th === "dark" ? "dark" : "light"];
      document.getElementById("check-light").style.display = th === "light" ? "inline" : "none";
      document.getElementById("check-dark").style.display = th === "dark" ? "inline" : "none";
    }

    document.getElementById("langMenuBtn").addEventListener("click", e => {
      e.stopPropagation();
      document.getElementById("langDropdown").classList.toggle("show");
      document.getElementById("themeDropdown").classList.remove("show");
    });
    // زر المظهر يبدل الثيم مباشرة بضغطة واحدة بلا قائمة (طلب المهندس رعد)
    document.getElementById("themeMenuBtn").addEventListener("click", e => {
      e.stopPropagation();
      setTheme(document.documentElement.dataset.theme === "dark" ? "light" : "dark");
      document.getElementById("langDropdown").classList.remove("show");
    });
    document.addEventListener("click", () => {
      document.getElementById("langDropdown").classList.remove("show");
      document.getElementById("themeDropdown").classList.remove("show");
    });

    document.querySelectorAll("#langDropdown .menu-dropdown-item").forEach(item => {
      item.addEventListener("click", () => setLang(item.dataset.lang));
    });
    document.querySelectorAll("#themeDropdown .menu-dropdown-item").forEach(item => {
      item.addEventListener("click", () => {
        setTheme(item.dataset.theme);
        document.getElementById("themeDropdown").classList.remove("show");
      });
    });

    document.querySelectorAll("[data-i18n]").forEach(el => {
      const k = el.dataset.i18n;
      if (translations[l] && translations[l][k]) el.textContent = translations[l][k];
    });
    applyPlaceholders(l);
    document.getElementById("currentLangDisplay").textContent = langNames[l] || l;
    ["ar","en","fr","ur"].forEach(c => {
      const el = document.getElementById("check-" + c);
      if (el) el.style.display = l === c ? "inline" : "none";
    });
    document.title = (translations[l] && translations[l].title ? translations[l].title : "Settings") + " | TheTracker";

    (function() {
      const th = theme();
      document.documentElement.dataset.theme = th;
      const meta = document.getElementById("themeColorMeta");
      if (meta) meta.content = th === "dark" ? "#1a2933" : "#0068b8";
      const logo = document.getElementById("footerLogo");
      if (logo) logo.src = th === "dark" ? "/tracker-logo-full-dark.png?v=2" : "/tracker-logo-full-light.png?v=2";
      document.getElementById("themeIcon").textContent = th === "dark" ? "🌙" : "☀️";
      document.getElementById("currentThemeDisplay").textContent = translations[l][th === "dark" ? "dark" : "light"];
      document.getElementById("check-light").style.display = th === "light" ? "inline" : "none";
      document.getElementById("check-dark").style.display = th === "dark" ? "inline" : "none";
    })();
  