    const translations = {
      ar: {
        exportXlsx: "تصدير إكسل",
        exportBtn: "تصدير",
        colDate: "التاريخ",
        colFrom: "من",
        colTo: "إلى",
        colMessage: "الرسالة",
        exportCsv: "تصدير CSV",
        fCase: "القضية",
        title: "إدارة الفريق",
        intro: "أضف أعضاء فريقك وحدد أدوارهم، وتابع الدعوات المعلقة.",
        backBtn: "العودة إلى لوحة التحكم",
        serviceUnavailableTitle: "الخدمة قيد التجهيز",
        serviceUnavailableText: "نعمل حاليا على تجهيز الخدمة، حاول مرة أخرى لاحقا.",
        noOrg: "لا توجد شركة محددة، أنشئ شركتك أولا.",
        noOrgHint: "انتقل إلى لوحة التحكم لإنشاء شركتك ثم عد إلى هذه الصفحة.",
        loading: "جاري التحميل...",
        loadError: "تعذر تحميل بيانات الفريق، حاول مرة أخرى.",
        membersTitle: "أعضاء الفريق",
        membersEmpty: "لا يوجد أعضاء بعد.",
        readOnlyNote: "يمكن للمالك والمشرفين فقط إدارة الأعضاء والدعوات.",
        capacityLimited: "الأعضاء: {used} من {limit}",
        capacityUnlimited: "الأعضاء: {used} (بلا حد)",
        capacityPending: "الدعوات المعلقة: {n}",
        capacityFull: "وصلت إلى الحد الأقصى لعدد الأعضاء في باقتك الحالية.",
        upgradeLink: "ترقية الباقة",
        roleOwner: "المالك",
        roleAdmin: "مشرف",
        roleMember: "عضو",
        roleLabel: "الدور",
        statusInvited: "بانتظار الانضمام",
        you: "أنت",
        emailLabel: "البريد الإلكتروني",
        personKindLabel: "الصفة",
        jobTitleLabel: "المسمى الوظيفي",
        personUnset: "غير محددة",
        departmentLabel: "القسم",
        deptUnset: "بلا قسم (يرى الأساسيات فقط)",
        dept_management: "الإدارة",
        deptUpdated: "حفظ القسم؛ يرى العضو خدمات قسمه فقط.",
        personPartner: "شريك",
        personManager: "مدير",
        personEmployee: "موظف",
        personContractor: "متعاقد",
        joinedLabel: "تاريخ الانضمام",
        changeRoleLabel: "تغيير الدور",
        removeBtn: "إزالة",
        confirmRemove: "هل تريد إزالة {name} من الفريق؟",
        memberRemoved: "تمت إزالة العضو.",
        roleUpdated: "تم تحديث الدور.",
        inviteTitle: "دعوة عضو جديد",
        inviteIntro: "أدخل البريد الإلكتروني للعضو واختر دوره. إن كان مسجلا في المنصة وصله تنبيه في جرس التنبيهات فورا، وينضم إلى الفريق عند فتحه التطبيق. وإن لم يكن مسجلا فأرسل له رابط تسجيل الدخول:",
        copyLinkBtn: "نسخ رابط تسجيل الدخول",
        linkCopied: "تم نسخ الرابط.",
        inviteEmailPlaceholder: "بريد العضو الإلكتروني",
        inviteBtn: "دعوة",
        lookupTitle: "أو من المسجلين في المنصة",
        inviteByEmailTitle: "بالبريد الإلكتروني",
        lookupBtn: "عرض المستخدمين",
        lookupPlaceholder: "بريد أو جوال أو رقم مستخدم",
        lookupNone: "لا يوجد مستخدم مطابق. تستطيع دعوته ببريده مباشرة.",
        inviteSending: "جاري الإضافة...",
        inviteCreated: "أضيفت الدعوة ل {email}، وسينضم تلقائيا عند تسجيل دخوله.",
        workloadTitle: "توزيع الأعمال",
        workloadIntro: "اسحب العمل إلى العضو.",
        rasiTitle: "مصفوفة RASI",
        rasiIntro: "لكل قضية أو مخالفة أو مهمة: من ينفذها، ومن يعتمدها ويتحمل مسؤوليتها (واحد فقط)، ومن يساندها، ومن يبلغ بها. اختر الدور ثم انقر الخانة، ويصل صاحبه تنبيه فورا.",
        rasiDragHint: "انقر لتعيين الدور المختار",
        rasiPickFirst: "اختر الدور أولا ثم انقر الخانة",
        rasiClearRole: "إزالة الدور",
        rasiDropped: "حفظ الدور",
                rasiWordR: "مسؤول",
        rasiWordA: "معتمد",
        rasiWordS: "مساند",
        rasiWordI: "مطلع",
        rasiWordNone: "بلا دور",
        rasiLegendR: "المنفذ المسؤول",
        rasiLegendA: "المعتمد والمسؤول أمام الإدارة",
        rasiLegendS: "المساند",
        rasiLegendI: "المطلع",
        rasiSearch: "ابحث بالعنوان أو الرقم",
        rasiEmpty: "لا عناصر مفتوحة لعرضها.",
        rasiItemCol: "العنصر",
        rasiSaved: "حفظ الدور.",
        rasiNoMembers: "أضف أعضاء إلى الفريق أولا.",
        quickTitle: "توزيع سريع",
        quickHint: "انقر اسم العضو على العنصر: نقرة واحدة تجعله المسؤول وتجعلك المعتمد تلقائيا، ونقرة ثانية تجعله مساندا، وثالثة تزيل الدور.",
        rasiShowMatrix: "عرض المصفوفة الكاملة",
        rasiHideMatrix: "إخفاء المصفوفة",
        quickAddTitle: "إدخال سريع",
        quickAddHint: "اكتب المهمة بصيغة واحدة: «جلسة القضية 4521 لشركة الأبراج الأحد 10 صباحا لأحمد» — يستخرج النظام النوع والموعد والعميل ورقم الدعوى والمنفذ، ويسجل ويوزع بنقرة واحدة.",
        quickAddBtn: "إضافة",
        quickAddPh: "اكتب المهمة ومن ينفذها وموعدها…",
        quickAddNobody: "بلا منفذ (يحدد لاحقا)",
        quickAddParsing: "جاري التحليل…",
        quickAddDone: "سجلت «{title}»{who}.",
        quickAddNoTitle: "لم يتضح عنوان المهمة من هذا النص — اكتب عنوانها على الأقل.",
        quickAddNeedsParent: "حدد القضية أو المخالفة التي تتبعها هذه المهمة — لا تسجل مهمة بلا أصل.",
        quickAddLink: "اربط وسجل",
        unassignedTitle: "أعمال غير مسندة",
        unassignedEmpty: "كل الأعمال مسندة.",
        wlOpen: "جارية",
        wlOverdue: "متأخرة",
        wlDone: "منتهية",
        assignTo: "أسند إلى",
        assignPick: "اختر عضوا",
        assignDone: "أسند العمل إلى {name}.",
        unassign: "غير مسندة",
        noDue: "بلا موعد",
        chatTitle: "تواصل الفريق",
        chatTyping: "{name} يكتب الآن…",
        chatThreads: "المحادثات",
        chatTeam: "الفريق كله",
        chatTeamHint: "اكتب للكل",
        chatPrivate: "خاص",
        chatPlaceholder: "اكتب رسالتك... (Enter للإرسال، Shift+Enter لسطر جديد)",
        chatSend: "إرسال",
        chatSendFile: "إرسال الملف",
        chatCancel: "إلغاء",
        chatFiles: "📁 الملفات",
        chatFilesEmpty: "لا ملفات في هذه المحادثة بعد.",
        chatDownload: "تنزيل",
        chatFileNoLink: "بلا ربط بقضية",
        chatFileTooBig: "الملف أكبر من 25 ميغابايت.",
        chatUploading: "جاري رفع الملف…",
        chatEmpty: "لا رسائل بعد.",
        chatLoadError: "تعذر تحميل الرسائل.",
        chatDelete: "حذف",
        chatConfirmDelete: "حذف هذه الرسالة؟",
        chatUnread: "{n} جديدة",
        chatToday: "اليوم",
        chatLive: "متصل",
        chatOffline: "يعاد الاتصال...",
        invitationsTitle: "الدعوات المعلقة",
        invitationsEmpty: "لا توجد دعوات معلقة.",
        invitedOn: "أضيفت في {date}",
        cancelInviteBtn: "إلغاء",
        confirmCancelInvite: "هل تريد إلغاء دعوة {email}؟",
        inviteCancelled: "ألغيت الدعوة.",
        invalidEmail: "أدخل بريدا إلكترونيا صحيحا.",
        alreadyMember: "هذا البريد عضو في الفريق بالفعل.",
        alreadyInvited: "توجد دعوة معلقة لهذا البريد بالفعل.",
        notAllowed: "ليست لديك صلاحية لتنفيذ هذا الإجراء.",
        genericError: "حدث خطأ، حاول مرة أخرى.",
        planLimitMembers: "وصلت إلى الحد الأقصى لعدد الأعضاء في باقتك الحالية، رق باقتك لإضافة المزيد.",
        copyrightLine2: "جميع الحقوق محفوظة",
        aboutLink: "من نحن",
        termsLink: "شروط الاستخدام",
        pricingLink: "الباقات والأسعار",
        privacyLink: "سياسة الخصوصية",
        loginLink: "تسجيل الدخول",
        dashboardLink: "لوحة التحكم",
        contactLink: "تواصل معنا",
        language: "اللغة",
        appearance: "المظهر",
        light: "فاتح",
        dark: "داكن"
      },
      en: {
        exportXlsx: "Export Excel",
        exportBtn: "Export",
        colDate: "Date",
        colFrom: "From",
        colTo: "To",
        colMessage: "Message",
        exportCsv: "Export CSV",
        fCase: "Case",
        title: "Team management",
        intro: "Add your team members, set their roles, and follow up on pending invitations.",
        backBtn: "Back to Dashboard",
        serviceUnavailableTitle: "Service is being prepared",
        serviceUnavailableText: "We are setting up the service. Please try again later.",
        noOrg: "No company selected. Create your company first.",
        noOrgHint: "Go to the dashboard to create your company, then come back to this page.",
        loading: "Loading...",
        loadError: "Could not load the team data. Please try again.",
        membersTitle: "Team members",
        membersEmpty: "No members yet.",
        readOnlyNote: "Only the owner and admins can manage members and invitations.",
        capacityLimited: "Members: {used} of {limit}",
        capacityUnlimited: "Members: {used} (unlimited)",
        capacityPending: "Pending invitations: {n}",
        capacityFull: "You have reached the member limit of your current plan.",
        upgradeLink: "Upgrade plan",
        roleOwner: "Owner",
        roleAdmin: "Admin",
        roleMember: "Member",
        roleLabel: "Role",
        statusInvited: "Awaiting sign-in",
        you: "You",
        emailLabel: "Email",
        personKindLabel: "Relationship",
        jobTitleLabel: "Job title",
        personUnset: "Not set",
        departmentLabel: "Department",
        deptUnset: "No department (basics only)",
        dept_management: "Management",
        deptUpdated: "Department saved; the member sees their department's services only.",
        personPartner: "Partner",
        personManager: "Manager",
        personEmployee: "Employee",
        personContractor: "Contractor",
        joinedLabel: "Joined on",
        changeRoleLabel: "Change role",
        removeBtn: "Remove",
        confirmRemove: "Remove {name} from the team?",
        memberRemoved: "Member removed.",
        roleUpdated: "Role updated.",
        inviteTitle: "Invite a new member",
        inviteIntro: "Enter the member's email and choose a role. If they are registered on the platform they get a notification in the bell right away, and they join the team the next time they open the app. Otherwise, send them the sign-in link:",
        copyLinkBtn: "Copy sign-in link",
        linkCopied: "Link copied.",
        inviteEmailPlaceholder: "Member's email address",
        inviteBtn: "Invite",
        lookupTitle: "Or from registered users",
        inviteByEmailTitle: "By email",
        lookupBtn: "Show users",
        lookupPlaceholder: "Email, mobile or user number",
        lookupNone: "No matching user. You can still invite them by email.",
        inviteSending: "Adding...",
        inviteCreated: "Invitation added for {email}. They will join automatically when they sign in.",
        workloadTitle: "Work distribution",
        workloadIntro: "Drag work onto a member.",
        rasiTitle: "RASI Matrix",
        rasiIntro: "For each case, violation or task: who does it, who approves and answers for it (one only), who supports, who is informed. Pick a role, then tap a cell; its owner is notified at once.",
        rasiDragHint: "Tap to set the chosen role",
        rasiPickFirst: "Pick a role first, then tap a cell",
        rasiClearRole: "Remove role",
        rasiDropped: "Role saved",
                rasiWordR: "Responsible",
        rasiWordA: "Approver",
        rasiWordS: "Support",
        rasiWordI: "Informed",
        rasiWordNone: "No role",
        rasiLegendR: "Responsible",
        rasiLegendA: "Approver / accountable",
        rasiLegendS: "Support",
        rasiLegendI: "Informed",
        rasiSearch: "Search by title or number",
        rasiEmpty: "No open items to show.",
        rasiItemCol: "Item",
        rasiSaved: "Role saved.",
        rasiNoMembers: "Add team members first.",
        quickTitle: "Quick distribution",
        quickHint: "Tap a member on an item: one tap makes them Responsible and you the Approver, a second tap makes them Support, a third removes the role.",
        rasiShowMatrix: "Show the full matrix",
        rasiHideMatrix: "Hide the matrix",
        quickAddTitle: "Quick entry",
        quickAddHint: "Type it the way you would say it: \"Hearing for case 4521, Al-Abraj, Sunday 10 AM, for Ahmad\" — kind, date, client, case number and who does it are understood, recorded and distributed in one tap.",
        quickAddBtn: "Add",
        quickAddPh: "Type the task, who does it and when…",
        quickAddNobody: "No responsible yet",
        quickAddParsing: "Understanding…",
        quickAddDone: "Recorded \"{title}\"{who}.",
        quickAddNoTitle: "I could not read a task from that — at least give it a title.",
        quickAddNeedsParent: "Which case or violation does this task belong to? — no task stands alone.",
        quickAddLink: "Link and record",
        unassignedTitle: "Unassigned work",
        unassignedEmpty: "All work is assigned.",
        wlOpen: "Open",
        wlOverdue: "Overdue",
        wlDone: "Done",
        assignTo: "Assign to",
        assignPick: "Pick a member",
        assignDone: "Assigned to {name}.",
        unassign: "Unassigned",
        noDue: "No due date",
        chatTitle: "Team chat",
        chatTyping: "{name} is typing…",
        chatThreads: "Conversations",
        chatTeam: "Whole team",
        chatTeamHint: "Everyone",
        chatPrivate: "Private",
        chatPlaceholder: "Write a message... (Enter to send, Shift+Enter for a new line)",
        chatSend: "Send",
        chatSendFile: "Send file",
        chatCancel: "Cancel",
        chatFiles: "📁 Files",
        chatFilesEmpty: "No files in this conversation yet.",
        chatDownload: "Download",
        chatFileNoLink: "Not linked to a case",
        chatFileTooBig: "The file exceeds 25 MB.",
        chatUploading: "Uploading…",
        chatEmpty: "No messages yet.",
        chatLoadError: "Could not load messages.",
        chatDelete: "Delete",
        chatConfirmDelete: "Delete this message?",
        chatUnread: "{n} new",
        chatToday: "Today",
        chatLive: "Live",
        chatOffline: "Reconnecting...",
        invitationsTitle: "Pending invitations",
        invitationsEmpty: "No pending invitations.",
        invitedOn: "added on {date}",
        cancelInviteBtn: "Cancel",
        confirmCancelInvite: "Cancel the invitation for {email}?",
        inviteCancelled: "Invitation cancelled.",
        invalidEmail: "Enter a valid email address.",
        alreadyMember: "This email already belongs to a team member.",
        alreadyInvited: "There is already a pending invitation for this email.",
        notAllowed: "You do not have permission to perform this action.",
        genericError: "Something went wrong. Please try again.",
        planLimitMembers: "You have reached the member limit of your current plan. Upgrade to add more.",
        copyrightLine2: "All rights reserved",
        aboutLink: "About Us",
        termsLink: "Terms of Use",
        pricingLink: "Plans & Pricing",
        privacyLink: "Privacy Policy",
        loginLink: "Sign in",
        dashboardLink: "Dashboard",
        contactLink: "Contact Us",
        language: "Language",
        appearance: "Appearance",
        light: "Light",
        dark: "Dark"
      },
      fr: {
        exportXlsx: "Exporter Excel",
        exportBtn: "Exporter",
        colDate: "Date",
        colFrom: "De",
        colTo: "À",
        colMessage: "Message",
        exportCsv: "Exporter CSV",
        fCase: "Affaire",
        title: "Gestion de l'équipe",
        intro: "Ajoutez les membres de votre équipe, définissez leurs rôles et suivez les invitations en attente.",
        backBtn: "Retour au tableau de bord",
        serviceUnavailableTitle: "Service en cours de préparation",
        serviceUnavailableText: "Nous préparons le service. Veuillez réessayer plus tard.",
        noOrg: "Aucune entreprise sélectionnée. Créez d'abord votre entreprise.",
        noOrgHint: "Rendez-vous sur le tableau de bord pour créer votre entreprise, puis revenez sur cette page.",
        loading: "Chargement...",
        loadError: "Impossible de charger les données de l'équipe. Veuillez réessayer.",
        membersTitle: "Membres de l'équipe",
        membersEmpty: "Aucun membre pour le moment.",
        readOnlyNote: "Seuls le propriétaire et les administrateurs peuvent gérer les membres et les invitations.",
        capacityLimited: "Membres : {used} sur {limit}",
        capacityUnlimited: "Membres : {used} (illimité)",
        capacityPending: "Invitations en attente : {n}",
        capacityFull: "Vous avez atteint la limite de membres de votre forfait actuel.",
        upgradeLink: "Changer de forfait",
        roleOwner: "Propriétaire",
        roleAdmin: "Administrateur",
        roleMember: "Membre",
        roleLabel: "Rôle",
        statusInvited: "En attente de connexion",
        you: "Vous",
        emailLabel: "E-mail",
        personKindLabel: "Qualité",
        jobTitleLabel: "Intitulé du poste",
        personUnset: "Non défini",
        departmentLabel: "Service",
        deptUnset: "Sans service (bases seulement)",
        dept_management: "Direction",
        deptUpdated: "Service enregistré ; le membre ne voit que les services de son service.",
        personPartner: "Associé",
        personManager: "Directeur",
        personEmployee: "Employé",
        personContractor: "Prestataire",
        joinedLabel: "Membre depuis le",
        changeRoleLabel: "Changer le rôle",
        removeBtn: "Retirer",
        confirmRemove: "Retirer {name} de l'équipe ?",
        memberRemoved: "Membre retiré.",
        roleUpdated: "Rôle mis à jour.",
        inviteTitle: "Inviter un nouveau membre",
        inviteIntro: "Saisissez l'e-mail du membre et choisissez son rôle. S'il est inscrit sur la plateforme, il reçoit aussitôt une notification dans la cloche et rejoint l'équipe à sa prochaine ouverture de l'application. Sinon, envoyez-lui le lien de connexion :",
        copyLinkBtn: "Copier le lien de connexion",
        linkCopied: "Lien copié.",
        inviteEmailPlaceholder: "Adresse e-mail du membre",
        inviteBtn: "Inviter",
        lookupTitle: "Ou parmi les utilisateurs inscrits",
        inviteByEmailTitle: "Par e-mail",
        lookupBtn: "Afficher les utilisateurs",
        lookupPlaceholder: "E-mail, mobile ou numéro",
        lookupNone: "Aucun utilisateur trouvé. Vous pouvez l'inviter par e-mail.",
        inviteSending: "Ajout en cours...",
        inviteCreated: "Invitation ajoutée pour {email}. Cette personne rejoindra l'équipe automatiquement lors de sa connexion.",
        workloadTitle: "Répartition du travail",
        workloadIntro: "Glissez le travail sur un membre.",
        rasiTitle: "Matrice RASI",
        rasiIntro: "Pour chaque affaire, infraction ou tâche : qui exécute, qui approuve et en répond (un seul), qui soutient, qui est informé. Choisissez un rôle puis touchez une case ; son titulaire est notifié aussitôt.",
        rasiDragHint: "Touchez pour attribuer le rôle choisi",
        rasiPickFirst: "Choisissez d'abord un rôle, puis touchez une case",
        rasiClearRole: "Retirer le rôle",
        rasiDropped: "Rôle enregistré",
                rasiWordR: "Responsable",
        rasiWordA: "Approbateur",
        rasiWordS: "Soutien",
        rasiWordI: "Informé",
        rasiWordNone: "Aucun rôle",
        rasiLegendR: "Responsable",
        rasiLegendA: "Approbateur",
        rasiLegendS: "Soutien",
        rasiLegendI: "Informé",
        rasiSearch: "Rechercher par titre ou numéro",
        rasiEmpty: "Aucun élément ouvert à afficher.",
        rasiItemCol: "Élément",
        rasiSaved: "Rôle enregistré.",
        rasiNoMembers: "Ajoutez d’abord des membres.",
        quickTitle: "Répartition rapide",
        quickHint: "Touchez un membre sur un élément : un clic le rend Responsable et vous Approbateur, un deuxième le rend Soutien, un troisième retire le rôle.",
        rasiShowMatrix: "Afficher la matrice complète",
        rasiHideMatrix: "Masquer la matrice",
        quickAddTitle: "Saisie rapide",
        quickAddHint: "Écrivez-la comme vous la diriez : « Audience affaire 4521, Al-Abraj, dimanche 10 h, pour Ahmad » — type, date, client, numéro d’affaire et responsable sont compris, enregistrés et répartis en un clic.",
        quickAddBtn: "Ajouter",
        quickAddPh: "Tapez la tâche, qui la fait et quand…",
        quickAddNobody: "Sans responsable",
        quickAddParsing: "Analyse…",
        quickAddDone: "« {title} » enregistrée{who}.",
        quickAddNoTitle: "Aucune tâche lisible dans ce texte — donnez au moins un titre.",
        quickAddNeedsParent: "À quelle affaire ou infraction cette tâche appartient-elle ? — aucune tâche isolée.",
        quickAddLink: "Lier et enregistrer",
        unassignedTitle: "Travail non attribué",
        unassignedEmpty: "Tout le travail est attribué.",
        wlOpen: "En cours",
        wlOverdue: "En retard",
        wlDone: "Terminé",
        assignTo: "Attribuer à",
        assignPick: "Choisir un membre",
        assignDone: "Attribué à {name}.",
        unassign: "Non attribué",
        noDue: "Sans échéance",
        chatTitle: "Discussion d'équipe",
        chatTyping: "{name} écrit…",
        chatThreads: "Conversations",
        chatTeam: "Toute l'équipe",
        chatTeamHint: "À tous",
        chatPrivate: "Privé",
        chatPlaceholder: "Écrivez un message... (Entrée pour envoyer, Maj+Entrée pour une nouvelle ligne)",
        chatSend: "Envoyer",
        chatSendFile: "Envoyer le fichier",
        chatCancel: "Annuler",
        chatFiles: "📁 Fichiers",
        chatFilesEmpty: "Aucun fichier dans cette conversation.",
        chatDownload: "Télécharger",
        chatFileNoLink: "Sans lien avec une affaire",
        chatFileTooBig: "Le fichier dépasse 25 Mo.",
        chatUploading: "Envoi…",
        chatEmpty: "Aucun message.",
        chatLoadError: "Impossible de charger les messages.",
        chatDelete: "Supprimer",
        chatConfirmDelete: "Supprimer ce message ?",
        chatUnread: "{n} nouveau(x)",
        chatToday: "Aujourd'hui",
        chatLive: "En direct",
        chatOffline: "Reconnexion...",
        invitationsTitle: "Invitations en attente",
        invitationsEmpty: "Aucune invitation en attente.",
        invitedOn: "ajoutée le {date}",
        cancelInviteBtn: "Annuler",
        confirmCancelInvite: "Annuler l'invitation de {email} ?",
        inviteCancelled: "Invitation annulée.",
        invalidEmail: "Saisissez une adresse e-mail valide.",
        alreadyMember: "Cette adresse appartient déjà à un membre de l'équipe.",
        alreadyInvited: "Une invitation est déjà en attente pour cette adresse.",
        notAllowed: "Vous n'avez pas l'autorisation d'effectuer cette action.",
        genericError: "Une erreur est survenue. Veuillez réessayer.",
        planLimitMembers: "Vous avez atteint la limite de membres de votre forfait actuel. Passez à un forfait supérieur pour en ajouter.",
        copyrightLine2: "Tous droits réservés",
        aboutLink: "À propos",
        termsLink: "Conditions d'utilisation",
        pricingLink: "Forfaits et tarifs",
        privacyLink: "Politique de confidentialité",
        loginLink: "Connexion",
        dashboardLink: "Tableau de bord",
        contactLink: "Contactez-nous",
        language: "Langue",
        appearance: "Apparence",
        light: "Clair",
        dark: "Sombre"
      },
      ur: {
        exportXlsx: "ایکسل ایکسپورٹ",
        exportBtn: "ایکسپورٹ",
        colDate: "تاریخ",
        colFrom: "منجانب",
        colTo: "بنام",
        colMessage: "پیغام",
        exportCsv: "CSV برآمد",
        fCase: "مقدمہ",
        title: "ٹیم کا انتظام",
        intro: "اپنی ٹیم کے اراکین شامل کریں، ان کے کردار طے کریں اور زیر التوا دعوتوں پر نظر رکھیں۔",
        backBtn: "ڈیش بورڈ پر واپس جائیں",
        serviceUnavailableTitle: "سروس تیار کی جا رہی ہے",
        serviceUnavailableText: "ہم سروس تیار کر رہے ہیں، براہ کرم بعد میں دوبارہ کوشش کریں۔",
        noOrg: "کوئی کمپنی منتخب نہیں، پہلے اپنی کمپنی بنائیں۔",
        noOrgHint: "اپنی کمپنی بنانے کے لیے ڈیش بورڈ پر جائیں، پھر اس صفحے پر واپس آئیں۔",
        loading: "لوڈ ہو رہا ہے...",
        loadError: "ٹیم کا ڈیٹا لوڈ نہیں ہو سکا، براہ کرم دوبارہ کوشش کریں۔",
        membersTitle: "ٹیم کے اراکین",
        membersEmpty: "ابھی کوئی رکن نہیں ہے۔",
        readOnlyNote: "صرف مالک اور منتظمین اراکین اور دعوتوں کا انتظام کر سکتے ہیں۔",
        capacityLimited: "اراکین: {limit} میں سے {used}",
        capacityUnlimited: "اراکین: {used} (لامحدود)",
        capacityPending: "زیر التوا دعوتیں: {n}",
        capacityFull: "آپ اپنے موجودہ پلان میں اراکین کی حد تک پہنچ چکے ہیں۔",
        upgradeLink: "پلان اپ گریڈ کریں",
        roleOwner: "مالک",
        roleAdmin: "منتظم",
        roleMember: "رکن",
        roleLabel: "کردار",
        statusInvited: "سائن ان کا انتظار",
        you: "آپ",
        emailLabel: "ای میل",
        personKindLabel: "حیثیت",
        jobTitleLabel: "عہدہ",
        personUnset: "مقرر نہیں",
        departmentLabel: "شعبہ",
        deptUnset: "کوئی شعبہ نہیں (صرف بنیادی)",
        dept_management: "انتظامیہ",
        deptUpdated: "شعبہ محفوظ؛ رکن صرف اپنے شعبے کی خدمات دیکھتا ہے۔",
        personPartner: "شریک",
        personManager: "منتظم",
        personEmployee: "ملازم",
        personContractor: "ٹھیکیدار",
        joinedLabel: "شمولیت کی تاریخ",
        changeRoleLabel: "کردار تبدیل کریں",
        removeBtn: "ہٹائیں",
        confirmRemove: "کیا آپ {name} کو ٹیم سے ہٹانا چاہتے ہیں؟",
        memberRemoved: "رکن ہٹا دیا گیا۔",
        roleUpdated: "کردار اپ ڈیٹ ہو گیا۔",
        inviteTitle: "نئے رکن کو دعوت دیں",
        inviteIntro: "رکن کا ای میل درج کریں اور اس کا کردار منتخب کریں۔ اگر وہ پلیٹ فارم پر رجسٹرڈ ہے تو اسے فورا بیل میں اطلاع ملے گی، اور ایپ کھولتے ہی ٹیم میں شامل ہو جائے گا۔ ورنہ اسے سائن ان لنک بھیجیں:",
        copyLinkBtn: "سائن ان لنک کاپی کریں",
        linkCopied: "لنک کاپی ہو گیا۔",
        inviteEmailPlaceholder: "رکن کا ای میل ایڈریس",
        inviteBtn: "دعوت دیں",
        lookupTitle: "یا رجسٹرڈ صارفین میں سے",
        inviteByEmailTitle: "ای میل سے",
        lookupBtn: "صارفین دکھائیں",
        lookupPlaceholder: "ای میل، موبائل یا صارف نمبر",
        lookupNone: "کوئی صارف نہیں ملا۔ آپ ای میل سے دعوت دے سکتے ہیں۔",
        inviteSending: "شامل کیا جا رہا ہے...",
        inviteCreated: "{email} کے لیے دعوت شامل کر دی گئی، سائن ان کرتے ہی وہ خود بخود شامل ہو جائے گا۔",
        workloadTitle: "کام کی تقسیم",
        workloadIntro: "کام کو رکن پر گھسیٹیں۔",
        rasiTitle: "RASI میٹرکس",
        rasiIntro: "ہر مقدمے، خلاف ورزی یا کام کے لیے: کون کرتا ہے، کون منظوری دیتا ہے اور جوابدہ ہے (صرف ایک)، کون معاونت کرتا ہے، کسے مطلع کیا جائے۔ کردار منتخب کریں پھر خانہ دبائیں؛ متعلقہ فرد کو فورا اطلاع ملتی ہے۔",
        rasiDragHint: "منتخب کردار مقرر کرنے کے لیے دبائیں",
        rasiPickFirst: "پہلے کردار منتخب کریں پھر خانہ دبائیں",
        rasiClearRole: "کردار ہٹائیں",
        rasiDropped: "کردار محفوظ ہو گیا",
                rasiWordR: "ذمہ دار",
        rasiWordA: "منظور کنندہ",
        rasiWordS: "معاون",
        rasiWordI: "مطلع",
        rasiWordNone: "کوئی کردار نہیں",
        rasiLegendR: "ذمہ دار",
        rasiLegendA: "منظور کنندہ",
        rasiLegendS: "معاون",
        rasiLegendI: "مطلع",
        rasiSearch: "عنوان یا نمبر سے تلاش",
        rasiEmpty: "دکھانے کے لیے کوئی کھلا آئٹم نہیں۔",
        rasiItemCol: "آئٹم",
        rasiSaved: "کردار محفوظ ہو گیا۔",
        rasiNoMembers: "پہلے ٹیم میں ارکان شامل کریں۔",
        quickTitle: "فوری تقسیم",
        quickHint: "آئٹم پر رکن کا نام دبائیں: ایک بار دبانے سے وہ ذمہ دار اور آپ منظور کنندہ بن جاتے ہیں، دوسری بار معاون، تیسری بار کردار ہٹ جاتا ہے۔",
        rasiShowMatrix: "مکمل میٹرکس دکھائیں",
        rasiHideMatrix: "میٹرکس چھپائیں",
        quickAddTitle: "فوری اندراج",
        quickAddHint: "جیسے آپ کہتے ہیں ویسے لکھیں: «مقدمہ 4521 کی سماعت، الابراج، اتوار 10 بجے، احمد کے لیے» — قسم، تاریخ، کلائنٹ، مقدمہ نمبر اور ذمہ دار سمجھ کر ایک ہی بار میں درج اور تقسیم ہو جاتا ہے۔",
        quickAddBtn: "شامل کریں",
        quickAddPh: "کام، ذمہ دار اور وقت لکھیں…",
        quickAddNobody: "ابھی کوئی ذمہ دار نہیں",
        quickAddParsing: "سمجھ رہا ہوں…",
        quickAddDone: "«{title}» درج ہو گیا{who}۔",
        quickAddNoTitle: "اس متن سے کوئی کام سمجھ نہیں آیا — کم از کم عنوان لکھیں۔",
        quickAddNeedsParent: "یہ کام کس مقدمے یا خلاف ورزی سے متعلق ہے؟ — کوئی کام الگ نہیں۔",
        quickAddLink: "منسلک کریں اور درج کریں",
        unassignedTitle: "بغیر ذمہ دار کام",
        unassignedEmpty: "تمام کام تفویض ہو چکے ہیں۔",
        wlOpen: "جاری",
        wlOverdue: "تاخیر شدہ",
        wlDone: "مکمل",
        assignTo: "تفویض کریں",
        assignPick: "رکن منتخب کریں",
        assignDone: "{name} کے سپرد کر دیا گیا۔",
        unassign: "بغیر ذمہ دار",
        noDue: "کوئی تاریخ نہیں",
        chatTitle: "ٹیم رابطہ",
        chatTyping: "{name} لکھ رہا ہے…",
        chatThreads: "گفتگوئیں",
        chatTeam: "پوری ٹیم",
        chatTeamHint: "سب کو",
        chatPrivate: "نجی",
        chatPlaceholder: "پیغام لکھیں... (Enter بھیجنے کے لیے، Shift+Enter نئی سطر)",
        chatSend: "بھیجیں",
        chatSendFile: "فائل بھیجیں",
        chatCancel: "منسوخ",
        chatFiles: "📁 فائلیں",
        chatFilesEmpty: "اس گفتگو میں ابھی کوئی فائل نہیں۔",
        chatDownload: "ڈاؤن لوڈ",
        chatFileNoLink: "کسی مقدمے سے منسلک نہیں",
        chatFileTooBig: "فائل 25 MB سے بڑی ہے۔",
        chatUploading: "اپ لوڈ ہو رہی ہے…",
        chatEmpty: "ابھی کوئی پیغام نہیں۔",
        chatLoadError: "پیغامات لوڈ نہیں ہو سکے۔",
        chatDelete: "حذف کریں",
        chatConfirmDelete: "یہ پیغام حذف کریں؟",
        chatUnread: "{n} نئے",
        chatToday: "آج",
        chatLive: "لائیو",
        chatOffline: "دوبارہ جوڑا جا رہا ہے...",
        invitationsTitle: "زیر التوا دعوتیں",
        invitationsEmpty: "کوئی زیر التوا دعوت نہیں۔",
        invitedOn: "شامل کی گئی: {date}",
        cancelInviteBtn: "منسوخ کریں",
        confirmCancelInvite: "کیا آپ {email} کی دعوت منسوخ کرنا چاہتے ہیں؟",
        inviteCancelled: "دعوت منسوخ کر دی گئی۔",
        invalidEmail: "درست ای میل ایڈریس درج کریں۔",
        alreadyMember: "یہ ای میل پہلے ہی ٹیم کے ایک رکن کا ہے۔",
        alreadyInvited: "اس ای میل کے لیے پہلے ہی ایک دعوت زیر التوا ہے۔",
        notAllowed: "آپ کو یہ کارروائی کرنے کی اجازت نہیں ہے۔",
        genericError: "کچھ غلط ہو گیا، براہ کرم دوبارہ کوشش کریں۔",
        planLimitMembers: "آپ اپنے موجودہ پلان میں اراکین کی حد تک پہنچ چکے ہیں، مزید شامل کرنے کے لیے پلان اپ گریڈ کریں۔",
        copyrightLine2: "جملہ حقوق محفوظ ہیں",
        aboutLink: "ہمارے بارے میں",
        termsLink: "استعمال کی شرائط",
        pricingLink: "پلانز اور قیمتیں",
        privacyLink: "رازداری کی پالیسی",
        loginLink: "سائن ان",
        dashboardLink: "ڈیش بورڈ",
        contactLink: "ہم سے رابطہ کریں",
        language: "زبان",
        appearance: "ظہور",
        light: "روشن",
        dark: "اندھیرا"
      }
    };

    const lang = () => localStorage.getItem("tracker_lang") || "ar";
    const theme = () => localStorage.getItem("tracker_theme") || "dark";
    const langNames = { ar: "العربية", en: "English", fr: "Français", ur: "اردو" };
    let l = lang();
    document.documentElement.lang = l;
    document.documentElement.dir = (l === "ar" || l === "ur") ? "rtl" : "ltr";

    const placeholderKeys = { inviteEmail: "inviteEmailPlaceholder", chatInput: "chatPlaceholder" };
    const ariaKeys = { inviteRole: "roleLabel" };
    function applyPlaceholders(code) {
      const dict = translations[code] || translations.ar;
      Object.keys(placeholderKeys).forEach(id => {
        const el = document.getElementById(id);
        if (el && dict[placeholderKeys[id]]) el.placeholder = dict[placeholderKeys[id]];
      });
      Object.keys(ariaKeys).forEach(id => {
        const el = document.getElementById(id);
        if (el && dict[ariaKeys[id]]) el.setAttribute("aria-label", dict[ariaKeys[id]]);
      });
    }

    function setLang(code) {
      localStorage.setItem("tracker_lang", code);
      l = code;
      document.documentElement.lang = code;
      document.documentElement.dir = (code === "ar" || code === "ur") ? "rtl" : "ltr";
      document.getElementById("currentLangDisplay").textContent = langNames[code] || code;
      ["ar","en","fr","ur"].forEach(c => {
        const el = document.getElementById("check-" + c);
        if (el) el.style.display = c === code ? "inline" : "none";
      });
      const th = theme();
      document.getElementById("currentThemeDisplay").textContent = translations[code][th === "dark" ? "dark" : "light"];
      document.querySelectorAll("[data-i18n]").forEach(el => {
        const k = el.dataset.i18n;
        if (translations[code] && translations[code][k]) el.innerHTML = translations[code][k];
      });
      applyPlaceholders(code);
      document.title = (translations[code] && translations[code].title ? translations[code].title : "Team") + " | TheTracker";
      if (typeof window.__trackerAuthRefresh === "function") window.__trackerAuthRefresh();
      if (typeof window.__teamRender === "function") window.__teamRender();
      if (typeof window.__chatRender === "function") window.__chatRender();
    }

    function setTheme(th) {
      localStorage.setItem("tracker_theme", th);
      document.documentElement.dataset.theme = th;
      const meta = document.getElementById("themeColorMeta");
      if (meta) meta.content = th === "dark" ? "#1a2933" : "#0068b8";
      const logo = document.getElementById("footerLogo");
      if (logo) logo.src = th === "dark" ? "/tracker-logo-full-dark.png?v=2" : "/tracker-logo-full-light.png?v=2";
      document.getElementById("themeIcon").textContent = th === "dark" ? "🌙" : "☀️";
      document.getElementById("currentThemeDisplay").textContent = translations[l][th === "dark" ? "dark" : "light"];
      document.getElementById("check-light").style.display = th === "light" ? "inline" : "none";
      document.getElementById("check-dark").style.display = th === "dark" ? "inline" : "none";
    }

    document.getElementById("langMenuBtn").addEventListener("click", e => {
      e.stopPropagation();
      document.getElementById("langDropdown").classList.toggle("show");
      document.getElementById("themeDropdown").classList.remove("show");
    });
    // زر المظهر يبدل الثيم مباشرة بضغطة واحدة بلا قائمة (طلب المهندس رعد)
    document.getElementById("themeMenuBtn").addEventListener("click", e => {
      e.stopPropagation();
      setTheme(document.documentElement.dataset.theme === "dark" ? "light" : "dark");
      document.getElementById("langDropdown").classList.remove("show");
    });
    document.addEventListener("click", () => {
      document.getElementById("langDropdown").classList.remove("show");
      document.getElementById("themeDropdown").classList.remove("show");
    });

    document.querySelectorAll("#langDropdown .menu-dropdown-item").forEach(item => {
      item.addEventListener("click", () => setLang(item.dataset.lang));
    });
    document.querySelectorAll("#themeDropdown .menu-dropdown-item").forEach(item => {
      item.addEventListener("click", () => {
        setTheme(item.dataset.theme);
        document.getElementById("themeDropdown").classList.remove("show");
      });
    });

    document.querySelectorAll("[data-i18n]").forEach(el => {
      const k = el.dataset.i18n;
      if (translations[l] && translations[l][k]) el.textContent = translations[l][k];
    });
    applyPlaceholders(l);
    document.getElementById("currentLangDisplay").textContent = langNames[l] || l;
    ["ar","en","fr","ur"].forEach(c => {
      const el = document.getElementById("check-" + c);
      if (el) el.style.display = l === c ? "inline" : "none";
    });
    document.title = (translations[l] && translations[l].title ? translations[l].title : "Team") + " | TheTracker";

    (function() {
      const th = theme();
      document.documentElement.dataset.theme = th;
      const meta = document.getElementById("themeColorMeta");
      if (meta) meta.content = th === "dark" ? "#1a2933" : "#0068b8";
      const logo = document.getElementById("footerLogo");
      if (logo) logo.src = th === "dark" ? "/tracker-logo-full-dark.png?v=2" : "/tracker-logo-full-light.png?v=2";
      document.getElementById("themeIcon").textContent = th === "dark" ? "🌙" : "☀️";
      document.getElementById("currentThemeDisplay").textContent = translations[l][th === "dark" ? "dark" : "light"];
      document.getElementById("check-light").style.display = th === "light" ? "inline" : "none";
      document.getElementById("check-dark").style.display = th === "dark" ? "inline" : "none";
    })();
  