    const translations = {
      ar: {
        orgCreatedFromDoc: "أنشئت «{name}» من السجل.",
        orgProfileFilled: "حدثت بيانات المنشأة من المستند.",
        exportXlsx: "تصدير إكسل",
        templateBtn: "تنزيل القالب",
        importTitle: "استيراد من Excel",
        subtitle: "ارفع ملف Excel أو CSV، ثم اربط أعمدته بحقول السجل، وسنتولى الباقي.",
        backHome: "العودة للرئيسية",
        noOrgTitle: "لا توجد شركة محددة",
        noOrgText: "أنشئ شركتك أولا من لوحة التحكم ثم عد إلى هذه الصفحة.",
        goDashboard: "الانتقال إلى لوحة التحكم",
        step1Title: "1. اختر الملف",
        dropTitle: "اسحب الملف إلى هنا أو انقر لاختياره",
        dropHint: "xlsx · xls · csv · tsv · json",
        chooseFile: "اختيار ملف",
        readingFile: "جاري قراءة الملف...",
        readError: "تعذرت قراءة الملف، تأكد من أنه ملف Excel أو CSV صالح.",
        libMissing: "تعذر تحميل مكتبة قراءة الملفات، أعد تحميل الصفحة وحاول مرة أخرى.",
        unsupportedType: "نوع الملف غير مدعوم، اختر ملفا بصيغة xlsx أو xls أو csv.",
        emptySheet: "لا تحتوي هذه الورقة على بيانات.",
        fileLoaded: "تمت قراءة الملف: {name} ({rows} صفا، {cols} عمودا).",
        rawPreviewToggle: "عرض الملف كما هو",
        sheetLabel: "الورقة",
        previewNote: "تعرض أول {shown} صفا من أصل {total}.",
        columnN: "عمود",
        step3Title: "ماذا تستورد",
        moreFieldsToggle: "تفاصيل إضافية",
        headerPickerMsg: "لم نجد صف العناوين بثقة — اختر الصف الصحيح.",
        headerRowOption: "الصف {n} — {preview}",
        previewMoreCols: "+{n} أعمدة أخرى",
        mapTitle: "العنوان",
        mapDue: "تاريخ الاستحقاق",
        mapCategory: "التصنيف",
        mapAssignee: "بريد المسؤول",
        mapStatus: "الحالة",
        sheetKind: "نوع الورقة",
        sheetKindGeneral: "عام (مواعيد وعقود)",
        sheetKindViolations: "مخالفات",
        graceDays: "مهلة السداد (أيام)",
        mapVNumber: "رقم المخالفة",
        mapCaseNumber: "رقم الدعوى",
        mapAmount: "مبلغ المخالفة",
        mapClient: "الشركة (العميل)",
        mapLocation: "الموقع",
        violationTitle: "مخالفة رقم {n}",
        required: "مطلوب",
        optional: "اختياري",
        notMapped: "— بدون —",
        mappingHint: "الأعمدة غير المربوطة تحفظ كبيانات إضافية مع كل عنصر.",
        statusHint: "في عمود الحالة تعتبر القيم done أو منجز أو completed منجزة، وما عداها يبقى مفتوحا.",
        validRows: "الصفوف الصالحة للاستيراد: {n}",
        skippedRows: "صفوف ستتجاهل لعدم وجود عنوان أو تاريخ صالح: {n}",
        unmatchedAssignees: "صفوف ببريد مسؤول غير موجود في الفريق: {n}",
        unmatchedHint: "لم يعثر على هذه العناوين بين أعضاء الفريق، وستستورد عناصرها بدون مسؤول: {list}",
        step4Title: "السجل",
        trackerLabel: "أضف العناصر إلى",
        newTracker: "سجل جديد",
        trackerNamePlaceholder: "اسم السجل الجديد",
        trackerNameRequired: "أدخل اسم السجل الجديد.",
        step5Title: "التحقق من الباقة والاستيراد",
        importsThisMonth: "عمليات الاستيراد هذا الشهر",
        itemsUsage: "العناصر المستخدمة",
        rowsToImport: "الصفوف التي ستستورد",
        unlimited: "غير محدود",
        ofLimit: "{used} من {limit}",
        checkingPlan: "جاري التحقق من الباقة...",
        planOk: "باقتك الحالية تسمح بهذا الاستيراد.",
        planImportsExceeded: "وصلت إلى الحد الأقصى لعمليات الاستيراد في هذا الشهر ({used} من {limit}). رق باقتك للمتابعة.",
        planItemsExceeded: "عدد الصفوف الصالحة ({rows}) يتجاوز العناصر المتبقية في باقتك ({remaining} متبقية من أصل {limit}). رق باقتك أو قلل عدد الصفوف.",
        upgradePlan: "ترقية الباقة",
        importBtn: "بدء الاستيراد",
        mappingRequired: "اختر عمود العنوان وعمود تاريخ الاستحقاق أولا.",
        mappingRequiredDue: "اختر عمود تاريخ الاستحقاق أولا.",
        noValidRows: "لا توجد صفوف صالحة للاستيراد، تحقق من ربط الأعمدة.",
        progressCreatingTracker: "جاري إنشاء السجل...",
        progressImport: "جاري تسجيل عملية الاستيراد...",
        progressInserting: "جاري إدراج العناصر: {done} من {total}",
        progressRule: "جاري إنشاء قاعدة التنبيه الافتراضية...",
        importFailed: "فشل الاستيراد: {error}",
        importPartial: "توقف الاستيراد بعد إدراج {done} عنصرا.",
        planLimitItems: "وصلت إلى الحد الأقصى لعدد العناصر في باقتك الحالية، رق باقتك لإضافة المزيد.",
        summaryTitle: "اكتمل الاستيراد",
        summaryInserted: "عناصر مدرجة",
        summarySkipped: "صفوف متجاهلة",
        summaryUnmatched: "صفوف بمسؤول غير مطابق",
        summaryTracker: "أضيفت العناصر إلى السجل: {name}",
        summaryRuleNote: "أنشئت قاعدة تنبيه افتراضية: تذكير عبر البريد الإلكتروني قبل الاستحقاق بيوم واحد.",
        summaryRuleFailed: "تعذر إنشاء قاعدة التنبيه الافتراضية، يمكنك إضافتها لاحقا من صفحة التنبيهات.",
        importAnother: "استيراد ملف آخر",
        importIntro: "ارفع كشف المخالفات أو الجلسات أو أي جدول، فتقرأ صفوفه وتحفظ عناصر لها مواعيد وتذكيرات.",
        kind_articles_of_association: "عقد تأسيس",
        kind_bylaws: "نظام أساسي",
        kind_chamber_certificate: "شهادة الغرفة التجارية",
        kind_gosi_certificate: "شهادة التأمينات الاجتماعية",
        kind_zakat_certificate: "شهادة الزكاة",
        kind_saudization_certificate: "شهادة السعودة",
        kind_lease_contract: "عقد إيجار",
        fCase: "القضية",
        title: "المستندات",
        docAddTitle: "إضافة مستند أو جدول",
        docAddIntro: "المستند يقرأه النظام، والجدول تستورد صفوفه.",
        docDropHint: "اسحب الملف أو اختره",
        docChoose: "اختيار ملف",
        docDrive: "اختيار من Google Drive",
        docDriveFailed: "تعذر جلب الملف من Google Drive.",
        docKind: "نوع المستند",
        docTitleField: "العنوان",
        docNumber: "رقم المستند",
        docIssuer: "الجهة المصدرة",
        docParty: "الشركة / صاحب المستند",
        docPartyEn: "الاسم بالإنجليزية",
        docIssueDate: "تاريخ الإصدار",
        docExpiry: "تاريخ الانتهاء / الاستحقاق",
        docAmount: "المبلغ (<span class=\"sar-symbol\" aria-label=\"ريال سعودي\"></span>)",
        docCase: "رقم الدعوى",
        docCourt: "المحكمة",
        docSave: "حفظ وإضافة للمتابعة",
        docListTitle: "مستندات الشركة",
        docLeft: "المتبقي",
        docFiles: "الملفات",
        docsEmpty: "لا مستندات بعد.",
        docReading: "جاري قراءة المستند...",
        docOcr: "المستند صورة، جاري قراءته بالذكاء الاصطناعي...",
        docReady: "قرأت المستند — راجع الحقول ثم احفظ.",
        docFailed: "تعذر قراءة المستند، جرب ملفا أوضح.",
        docSaving: "جاري الحفظ...",
        fieldRemind: "ذكرني قبل انتهائها",
        remindDefault: "حسب قاعدة السجل",
        remindDay: "بيوم",
        remind3Days: "بثلاثة أيام",
        remindWeek: "بأسبوع",
        remind2Weeks: "بأسبوعين",
        remindMonth: "بشهر",
        pEndsIn: "ينتهي خلال {n} يوما",
        pEndsToday: "ينتهي اليوم",
        pExpiredSince: "منتهية منذ {n} يوما",
        docDetailsTitle: "ما قرأه النظام من الورقة",
        docProfileTitle: "تحديث بيانات الشركة من هذه الورقة",
        docProfileApply: "حدّث بيانات الشركة",
        docProfileSkip: "اترك بياناتي كما هي",
        docProfileDone: "حُدّثت بيانات الشركة من الورقة.",
        docProfileNow: "القيمة الحالية",
        docProfileNew: "من الورقة",
        docDetailsOf: "بيانات المستند",
        docSaved: "حفظ المستند وأضيف للمتابعة والتنبيه.",
        docFileFailed: "حفظت البيانات لكن تعذر رفع الملف.",
        docStorageLimit: "حفظت البيانات لكن مساحة التخزين في باقتك ممتلئة.",
        papersTitle: "الأوراق الرسمية",
        papersNote: "الناقص والمنتهي يظهران هنا، والتذكير على تيليغرام.",
        papersState: "الحالة",
        pMissing: "ناقص",
        pValid: "ساري",
        pExpiring: "ينتهي قريبا",
        pExpired: "منته",
        pStored: "محفوظ بلا تاريخ",
        pRequired: "مطلوب",
        pOptional: "اختياري",
        pAdd: "أضف",
        pOpen: "عرض",
        pDownload: "تنزيل",
        docAttachFile: "إرفاق ملف",
        docAddAnother: "إضافة ملف",
        docFileAdded: "أضيف الملف.",
        pOpen: "افتح",
        pStatValid: "سارية",
        pStatExpiring: "تنتهي قريبا",
        pStatExpired: "منتهية",
        pStatMissing: "ناقصة",
        docReplace: "استبدل",
        docExpired: "منته",
        docDays: "يوما",
        docDeleteConfirm: "حذف المستند وملفاته نهائيا؟",
        allKinds: "كل الأنواع",
        search: "بحث",
        actions: "الإجراءات",
        delete: "حذف",
        unavailable: "الخدمة غير متاحة الآن.",
        kind_commercial_register: "سجل تجاري",
        kind_vat_certificate: "شهادة ضريبية",
        kind_license: "رخصة",
        kind_contract: "عقد",
        kind_case_filing: "صحيفة دعوى / مرفوعات",
        kind_court_ruling: "حكم قضائي",
        kind_hearing_notice: "إشعار جلسة",
        kind_violation: "مخالفة",
        kind_invoice: "فاتورة",
        kind_power_of_attorney: "وكالة",
        kind_id_document: "هوية / إقامة",
        kind_passport: "جواز سفر",
        kind_driving_license: "رخصة قيادة",
        kind_vehicle_registration: "استمارة مركبة",
        kind_insurance_policy: "وثيقة تأمين",
        kind_employment_contract: "عقد عمل",
        kind_other: "مستند آخر",
        intro: "أضف أعضاء فريقك وحدد أدوارهم، وتابع الدعوات المعلقة.",
        backBtn: "العودة إلى لوحة التحكم",
        serviceUnavailableTitle: "الخدمة قيد التجهيز",
        serviceUnavailableText: "نعمل حاليا على تجهيز الخدمة، حاول مرة أخرى لاحقا.",
        noOrg: "لا توجد شركة محددة، أنشئ شركتك أولا.",
        noOrgHint: "انتقل إلى لوحة التحكم لإنشاء شركتك ثم عد إلى هذه الصفحة.",
        loading: "جاري التحميل...",
        loadError: "تعذر تحميل بيانات الفريق، حاول مرة أخرى.",
        membersTitle: "أعضاء الفريق",
        membersEmpty: "لا يوجد أعضاء بعد.",
        readOnlyNote: "يمكن للمالك والمشرفين فقط إدارة الأعضاء والدعوات.",
        capacityLimited: "الأعضاء: {used} من {limit}",
        capacityUnlimited: "الأعضاء: {used} (بلا حد)",
        capacityPending: "الدعوات المعلقة: {n}",
        capacityFull: "وصلت إلى الحد الأقصى لعدد الأعضاء في باقتك الحالية.",
        upgradeLink: "ترقية الباقة",
        roleOwner: "المالك",
        roleAdmin: "مشرف",
        roleMember: "عضو",
        roleLabel: "الدور",
        statusInvited: "بانتظار الانضمام",
        you: "أنت",
        emailLabel: "البريد الإلكتروني",
        joinedLabel: "تاريخ الانضمام",
        changeRoleLabel: "تغيير الدور",
        removeBtn: "إزالة",
        confirmRemove: "هل تريد إزالة {name} من الفريق؟",
        memberRemoved: "تمت إزالة العضو.",
        roleUpdated: "تم تحديث الدور.",
        inviteTitle: "دعوة عضو جديد",
        inviteIntro: "أدخل البريد الإلكتروني للعضو واختر دوره. إن كان مسجلا في المنصة وصله تنبيه في جرس التنبيهات فورا، وينضم إلى الفريق عند فتحه التطبيق. وإن لم يكن مسجلا فأرسل له رابط تسجيل الدخول:",
        copyLinkBtn: "نسخ رابط تسجيل الدخول",
        linkCopied: "تم نسخ الرابط.",
        inviteEmailPlaceholder: "بريد العضو الإلكتروني",
        inviteBtn: "دعوة",
        lookupTitle: "أو من المسجلين في المنصة",
        inviteByEmailTitle: "بالبريد الإلكتروني",
        lookupBtn: "عرض المستخدمين",
        lookupPlaceholder: "بريد أو جوال أو رقم مستخدم",
        lookupNone: "لا يوجد مستخدم مطابق. تستطيع دعوته ببريده مباشرة.",
        inviteSending: "جاري الإضافة...",
        inviteCreated: "أضيفت الدعوة ل {email}، وسينضم تلقائيا عند تسجيل دخوله.",
        workloadTitle: "توزيع الأعمال",
        workloadIntro: "اسحب العمل إلى العضو.",
        rasiTitle: "مصفوفة RASI",
        rasiIntro: "لكل قضية أو مخالفة أو مهمة: من ينفذ (R)، من يعتمد ويساءل (A — واحد فقط)، من يساند (S)، ومن يبلغ (I). اضغط الخلية لتبديل الدور، ويصل صاحبه تنبيه فورا.",
        rasiLegendR: "المنفذ المسؤول",
        rasiLegendA: "المعتمد والمساءل",
        rasiLegendS: "المساند",
        rasiLegendI: "المبلغ",
        rasiSearch: "ابحث بالعنوان أو الرقم",
        rasiEmpty: "لا عناصر مفتوحة لعرضها.",
        rasiItemCol: "العنصر",
        rasiSaved: "حفظ الدور.",
        rasiNoMembers: "أضف أعضاء إلى الفريق أولا.",
        quickTitle: "توزيع سريع",
        quickHint: "اضغط اسم العضو على العنصر: ضغطة واحدة = هو المنفذ المسؤول (R) وأنت المعتمد (A) تلقائيا، ضغطة ثانية = مساند (S)، ثالثة = إزالة.",
        rasiShowMatrix: "عرض المصفوفة الكاملة",
        rasiHideMatrix: "إخفاء المصفوفة",
        quickAddTitle: "إدخال سريع",
        quickAddHint: "اكتب المهمة كما تقولها: «جلسة القضية 4521 لشركة الأبراج الأحد 10 صباحا لأحمد» — يفهم النوع والموعد والعميل ورقم الدعوى ومن ينفذ، ويسجل ويوزع بضغطة واحدة.",
        quickAddBtn: "إضافة",
        quickAddPh: "اكتب المهمة ومن ينفذها وموعدها…",
        quickAddNobody: "بلا منفذ (أنا لاحقا)",
        quickAddParsing: "جاري الفهم…",
        quickAddDone: "سجلت «{title}»{who}.",
        quickAddNoTitle: "لم أفهم مهمة من هذا النص — اكتب عنوانها على الأقل.",
        quickAddNeedsParent: "لأي قضية أو مخالفة تتبع هذه المهمة؟ — لا مهمة بلا أصل.",
        quickAddLink: "اربط وسجل",
        unassignedTitle: "أعمال بلا صاحب",
        unassignedEmpty: "كل الأعمال مسندة.",
        wlOpen: "جارية",
        wlOverdue: "متأخرة",
        wlDone: "منتهية",
        assignTo: "أسند إلى",
        assignPick: "اختر عضوا",
        assignDone: "أسند العمل إلى {name}.",
        unassign: "بلا صاحب",
        noDue: "بلا موعد",
        chatTitle: "تواصل الفريق",
        chatThreads: "المحادثات",
        chatTeam: "الفريق كله",
        chatTeamHint: "اكتب للكل",
        chatPrivate: "خاص",
        chatPlaceholder: "اكتب رسالتك... (Enter للإرسال، Shift+Enter لسطر جديد)",
        chatSend: "إرسال",
        chatSendFile: "إرسال الملف",
        chatCancel: "إلغاء",
        chatFiles: "📁 الملفات",
        chatFilesEmpty: "لا ملفات في هذه المحادثة بعد.",
        chatDownload: "تنزيل",
        chatFileNoLink: "بلا ربط بقضية",
        chatFileTooBig: "الملف أكبر من 25 ميغابايت.",
        chatUploading: "جاري رفع الملف…",
        chatEmpty: "لا رسائل بعد.",
        chatLoadError: "تعذر تحميل الرسائل.",
        chatDelete: "حذف",
        chatConfirmDelete: "حذف هذه الرسالة؟",
        chatUnread: "{n} جديدة",
        chatToday: "اليوم",
        chatLive: "متصل",
        chatOffline: "يعاد الاتصال...",
        invitationsTitle: "الدعوات المعلقة",
        invitationsEmpty: "لا توجد دعوات معلقة.",
        invitedOn: "أضيفت في {date}",
        cancelInviteBtn: "إلغاء",
        confirmCancelInvite: "هل تريد إلغاء دعوة {email}؟",
        inviteCancelled: "ألغيت الدعوة.",
        invalidEmail: "أدخل بريدا إلكترونيا صحيحا.",
        alreadyMember: "هذا البريد عضو في الفريق بالفعل.",
        alreadyInvited: "توجد دعوة معلقة لهذا البريد بالفعل.",
        notAllowed: "ليست لديك صلاحية لتنفيذ هذا الإجراء.",
        genericError: "حدث خطأ، حاول مرة أخرى.",
        planLimitMembers: "وصلت إلى الحد الأقصى لعدد الأعضاء في باقتك الحالية، رق باقتك لإضافة المزيد.",
        copyrightLine2: "جميع الحقوق محفوظة",
        aboutLink: "من نحن",
        termsLink: "شروط الاستخدام",
        pricingLink: "الباقات والأسعار",
        privacyLink: "سياسة الخصوصية",
        loginLink: "تسجيل الدخول",
        dashboardLink: "لوحة التحكم",
        contactLink: "تواصل معنا",
        language: "اللغة",
        appearance: "المظهر",
        light: "فاتح",
        dark: "داكن"
      },
      en: {
        orgCreatedFromDoc: "“{name}” created from the register.",
        orgProfileFilled: "Organization details filled from the document.",
        exportXlsx: "Export Excel",
        templateBtn: "Download template",
        importTitle: "Import from Excel",
        subtitle: "Upload an Excel or CSV file, map its columns to the tracker fields, and we will handle the rest.",
        backHome: "Back to Home",
        noOrgTitle: "No company selected",
        noOrgText: "Create your company from the dashboard first, then come back to this page.",
        goDashboard: "Go to the dashboard",
        step1Title: "1. Choose the file",
        dropTitle: "Drag the file here or click to choose it",
        dropHint: "xlsx · xls · csv · tsv · json",
        chooseFile: "Choose a file",
        readingFile: "Reading the file...",
        readError: "The file could not be read. Make sure it is a valid Excel or CSV file.",
        libMissing: "The file reader library could not be loaded. Reload the page and try again.",
        unsupportedType: "Unsupported file type. Choose an xlsx, xls or csv file.",
        emptySheet: "This sheet contains no data.",
        fileLoaded: "File read: {name} ({rows} rows, {cols} columns).",
        rawPreviewToggle: "Show the raw file",
        sheetLabel: "Sheet",
        previewNote: "Showing the first {shown} of {total} rows.",
        columnN: "Column",
        step3Title: "What are you importing",
        moreFieldsToggle: "Additional details",
        headerPickerMsg: "We could not confidently find the header row — pick the right one.",
        headerRowOption: "Row {n} — {preview}",
        previewMoreCols: "+{n} more columns",
        mapTitle: "Title",
        mapDue: "Due date",
        mapCategory: "Category",
        mapAssignee: "Assignee email",
        mapStatus: "Status",
        sheetKind: "Sheet type",
        sheetKindGeneral: "General (dates and contracts)",
        sheetKindViolations: "Violations",
        graceDays: "Payment window (days)",
        mapVNumber: "Violation number",
        mapCaseNumber: "Case number",
        mapAmount: "Fine amount",
        mapClient: "Client company",
        mapLocation: "Location",
        violationTitle: "Violation no. {n}",
        required: "required",
        optional: "optional",
        notMapped: "— none —",
        mappingHint: "Unmapped columns are stored as extra data on each item.",
        statusHint: "In the status column, the values done, منجز or completed count as done; anything else stays open.",
        validRows: "Rows ready to import: {n}",
        skippedRows: "Rows that will be skipped (missing title or valid date): {n}",
        unmatchedAssignees: "Rows whose assignee email is not a team member: {n}",
        unmatchedHint: "These addresses were not found among the team members; their items will be imported without an assignee: {list}",
        step4Title: "Tracker",
        trackerLabel: "Add the items to",
        newTracker: "New tracker",
        trackerNamePlaceholder: "Name of the new tracker",
        trackerNameRequired: "Enter a name for the new tracker.",
        step5Title: "Plan check and import",
        importsThisMonth: "Imports this month",
        itemsUsage: "Items in use",
        rowsToImport: "Rows to import",
        unlimited: "Unlimited",
        ofLimit: "{used} of {limit}",
        checkingPlan: "Checking your plan...",
        planOk: "Your current plan allows this import.",
        planImportsExceeded: "You have reached the import limit for this month ({used} of {limit}). Upgrade your plan to continue.",
        planItemsExceeded: "The number of valid rows ({rows}) exceeds the items remaining in your plan ({remaining} remaining of {limit}). Upgrade your plan or reduce the rows.",
        upgradePlan: "Upgrade plan",
        importBtn: "Start import",
        mappingRequired: "Choose the title column and the due date column first.",
        mappingRequiredDue: "Choose the due date column first.",
        noValidRows: "There are no valid rows to import. Check the column mapping.",
        progressCreatingTracker: "Creating the tracker...",
        progressImport: "Registering the import...",
        progressInserting: "Inserting items: {done} of {total}",
        progressRule: "Creating the default reminder rule...",
        importFailed: "Import failed: {error}",
        importPartial: "The import stopped after inserting {done} items.",
        planLimitItems: "You have reached the item limit of your current plan. Upgrade to add more.",
        summaryTitle: "Import complete",
        summaryInserted: "Items inserted",
        summarySkipped: "Rows skipped",
        summaryUnmatched: "Rows with unmatched assignee",
        summaryTracker: "The items were added to the tracker: {name}",
        summaryRuleNote: "A default reminder rule was created: an email reminder one day before the due date.",
        summaryRuleFailed: "The default reminder rule could not be created; you can add it later from the reminders page.",
        importAnother: "Import another file",
        importIntro: "Upload a violations sheet, a hearings schedule or any table; its rows become items with dates and reminders.",
        kind_articles_of_association: "Articles of association",
        kind_bylaws: "Bylaws",
        kind_chamber_certificate: "Chamber of commerce certificate",
        kind_gosi_certificate: "GOSI certificate",
        kind_zakat_certificate: "Zakat certificate",
        kind_saudization_certificate: "Saudization certificate",
        kind_lease_contract: "Lease contract",
        fCase: "Case",
        title: "Documents",
        docAddTitle: "Add a document or spreadsheet",
        docAddIntro: "A document is read, a spreadsheet is imported.",
        docDropHint: "Drop a file or choose one",
        docChoose: "Choose file",
        docDrive: "Pick from Google Drive",
        docDriveFailed: "Could not fetch the file from Google Drive.",
        docKind: "Document type",
        docTitleField: "Title",
        docNumber: "Document number",
        docIssuer: "Issuer",
        docParty: "Company / holder",
        docPartyEn: "Name in English",
        docIssueDate: "Issue date",
        docExpiry: "Expiry / due date",
        docAmount: "Amount (<span class=\"sar-symbol\" aria-label=\"ريال سعودي\"></span>)",
        docCase: "Case number",
        docCourt: "Court",
        docSave: "Save and track",
        docListTitle: "Company documents",
        docLeft: "Remaining",
        docFiles: "Files",
        docsEmpty: "No documents yet.",
        docReading: "Reading the document...",
        docOcr: "Image document — reading it with AI...",
        docReady: "Document read — review the fields and save.",
        docFailed: "Could not read the document; try a clearer file.",
        docSaving: "Saving...",
        fieldRemind: "Remind me before it expires",
        remindDefault: "As the tracker's rule says",
        remindDay: "One day",
        remind3Days: "Three days",
        remindWeek: "One week",
        remind2Weeks: "Two weeks",
        remindMonth: "One month",
        pEndsIn: "Ends in {n} days",
        pEndsToday: "Ends today",
        pExpiredSince: "Expired {n} days ago",
        docDetailsTitle: "What the system read from this paper",
        docProfileTitle: "Update the company details from this paper",
        docProfileApply: "Update the company details",
        docProfileSkip: "Leave my details as they are",
        docProfileDone: "Company details updated from the paper.",
        docProfileNow: "Current value",
        docProfileNew: "From the paper",
        docDetailsOf: "Document details",
        docSaved: "Saved and added to tracking and reminders.",
        docFileFailed: "Data saved, but the file could not be uploaded.",
        docStorageLimit: "Data saved, but your plan storage is full.",
        papersTitle: "Official papers",
        papersNote: "Missing and expired show here; reminders go to Telegram.",
        papersState: "State",
        pMissing: "Missing",
        pValid: "Valid",
        pExpiring: "Expiring",
        pExpired: "Expired",
        pStored: "Stored, no date",
        pRequired: "Required",
        pOptional: "Optional",
        pAdd: "Add",
        pOpen: "View",
        pDownload: "Download",
        docAttachFile: "Attach file",
        docAddAnother: "Add file",
        docFileAdded: "File added.",
        pOpen: "Open",
        pStatValid: "Valid",
        pStatExpiring: "Expiring",
        pStatExpired: "Expired",
        pStatMissing: "Missing",
        docReplace: "Replace",
        docExpired: "Expired",
        docDays: "days",
        docDeleteConfirm: "Delete this document and its files permanently?",
        allKinds: "All types",
        search: "Search",
        actions: "Actions",
        delete: "Delete",
        unavailable: "Service unavailable right now.",
        kind_commercial_register: "Commercial register",
        kind_vat_certificate: "VAT certificate",
        kind_license: "Licence",
        kind_contract: "Contract",
        kind_case_filing: "Statement of claim / filing",
        kind_court_ruling: "Court ruling",
        kind_hearing_notice: "Hearing notice",
        kind_violation: "Violation",
        kind_invoice: "Invoice",
        kind_power_of_attorney: "Power of attorney",
        kind_id_document: "ID document",
        kind_passport: "Passport",
        kind_driving_license: "Driving licence",
        kind_vehicle_registration: "Vehicle registration",
        kind_insurance_policy: "Insurance policy",
        kind_employment_contract: "Employment contract",
        kind_other: "Other document",
        intro: "Add your team members, set their roles, and follow up on pending invitations.",
        backBtn: "Back to Dashboard",
        serviceUnavailableTitle: "Service is being prepared",
        serviceUnavailableText: "We are setting up the service. Please try again later.",
        noOrg: "No company selected. Create your company first.",
        noOrgHint: "Go to the dashboard to create your company, then come back to this page.",
        loading: "Loading...",
        loadError: "Could not load the team data. Please try again.",
        membersTitle: "Team members",
        membersEmpty: "No members yet.",
        readOnlyNote: "Only the owner and admins can manage members and invitations.",
        capacityLimited: "Members: {used} of {limit}",
        capacityUnlimited: "Members: {used} (unlimited)",
        capacityPending: "Pending invitations: {n}",
        capacityFull: "You have reached the member limit of your current plan.",
        upgradeLink: "Upgrade plan",
        roleOwner: "Owner",
        roleAdmin: "Admin",
        roleMember: "Member",
        roleLabel: "Role",
        statusInvited: "Awaiting sign-in",
        you: "You",
        emailLabel: "Email",
        joinedLabel: "Joined on",
        changeRoleLabel: "Change role",
        removeBtn: "Remove",
        confirmRemove: "Remove {name} from the team?",
        memberRemoved: "Member removed.",
        roleUpdated: "Role updated.",
        inviteTitle: "Invite a new member",
        inviteIntro: "Enter the member's email and choose a role. If they are registered on the platform they get a notification in the bell right away, and they join the team the next time they open the app. Otherwise, send them the sign-in link:",
        copyLinkBtn: "Copy sign-in link",
        linkCopied: "Link copied.",
        inviteEmailPlaceholder: "Member's email address",
        inviteBtn: "Invite",
        lookupTitle: "Or from registered users",
        inviteByEmailTitle: "By email",
        lookupBtn: "Show users",
        lookupPlaceholder: "Email, mobile or user number",
        lookupNone: "No matching user. You can still invite them by email.",
        inviteSending: "Adding...",
        inviteCreated: "Invitation added for {email}. They will join automatically when they sign in.",
        workloadTitle: "Work distribution",
        workloadIntro: "Drag work onto a member.",
        rasiTitle: "RASI Matrix",
        rasiIntro: "For every case, violation or task: who does it (R), who approves and answers for it (A — exactly one), who supports (S), who is kept informed (I). Click a cell to cycle the role; the person is notified instantly.",
        rasiLegendR: "Responsible",
        rasiLegendA: "Approver / accountable",
        rasiLegendS: "Support",
        rasiLegendI: "Informed",
        rasiSearch: "Search by title or number",
        rasiEmpty: "No open items to show.",
        rasiItemCol: "Item",
        rasiSaved: "Role saved.",
        rasiNoMembers: "Add team members first.",
        quickTitle: "Quick distribution",
        quickHint: "Tap a member on an item: one tap = Responsible (R) with you as Approver (A) automatically, second tap = Support (S), third = remove.",
        rasiShowMatrix: "Show the full matrix",
        rasiHideMatrix: "Hide the matrix",
        quickAddTitle: "Quick entry",
        quickAddHint: "Type it the way you would say it: \"Hearing for case 4521, Al-Abraj, Sunday 10 AM, for Ahmad\" — kind, date, client, case number and who does it are understood, recorded and distributed in one tap.",
        quickAddBtn: "Add",
        quickAddPh: "Type the task, who does it and when…",
        quickAddNobody: "No responsible yet",
        quickAddParsing: "Understanding…",
        quickAddDone: "Recorded \"{title}\"{who}.",
        quickAddNoTitle: "I could not read a task from that — at least give it a title.",
        quickAddNeedsParent: "Which case or violation does this task belong to? — no task stands alone.",
        quickAddLink: "Link and record",
        unassignedTitle: "Unassigned work",
        unassignedEmpty: "All work is assigned.",
        wlOpen: "Open",
        wlOverdue: "Overdue",
        wlDone: "Done",
        assignTo: "Assign to",
        assignPick: "Pick a member",
        assignDone: "Assigned to {name}.",
        unassign: "Unassigned",
        noDue: "No due date",
        chatTitle: "Team chat",
        chatThreads: "Conversations",
        chatTeam: "Whole team",
        chatTeamHint: "Everyone",
        chatPrivate: "Private",
        chatPlaceholder: "Write a message... (Enter to send, Shift+Enter for a new line)",
        chatSend: "Send",
        chatSendFile: "Send file",
        chatCancel: "Cancel",
        chatFiles: "📁 Files",
        chatFilesEmpty: "No files in this conversation yet.",
        chatDownload: "Download",
        chatFileNoLink: "Not linked to a case",
        chatFileTooBig: "The file exceeds 25 MB.",
        chatUploading: "Uploading…",
        chatEmpty: "No messages yet.",
        chatLoadError: "Could not load messages.",
        chatDelete: "Delete",
        chatConfirmDelete: "Delete this message?",
        chatUnread: "{n} new",
        chatToday: "Today",
        chatLive: "Live",
        chatOffline: "Reconnecting...",
        invitationsTitle: "Pending invitations",
        invitationsEmpty: "No pending invitations.",
        invitedOn: "added on {date}",
        cancelInviteBtn: "Cancel",
        confirmCancelInvite: "Cancel the invitation for {email}?",
        inviteCancelled: "Invitation cancelled.",
        invalidEmail: "Enter a valid email address.",
        alreadyMember: "This email already belongs to a team member.",
        alreadyInvited: "There is already a pending invitation for this email.",
        notAllowed: "You do not have permission to perform this action.",
        genericError: "Something went wrong. Please try again.",
        planLimitMembers: "You have reached the member limit of your current plan. Upgrade to add more.",
        copyrightLine2: "All rights reserved",
        aboutLink: "About Us",
        termsLink: "Terms of Use",
        pricingLink: "Plans & Pricing",
        privacyLink: "Privacy Policy",
        loginLink: "Sign in",
        dashboardLink: "Dashboard",
        contactLink: "Contact Us",
        language: "Language",
        appearance: "Appearance",
        light: "Light",
        dark: "Dark"
      },
      fr: {
        orgCreatedFromDoc: "« {name} » créée depuis le registre.",
        orgProfileFilled: "Informations de l'entité remplies depuis le document.",
        exportXlsx: "Exporter Excel",
        templateBtn: "Télécharger le modèle",
        importTitle: "Importer depuis Excel",
        subtitle: "Téléversez un fichier Excel ou CSV, associez ses colonnes aux champs du suivi, et nous nous occupons du reste.",
        backHome: "Retour à l'accueil",
        noOrgTitle: "Aucune entreprise sélectionnée",
        noOrgText: "Créez d'abord votre entreprise depuis le tableau de bord, puis revenez sur cette page.",
        goDashboard: "Aller au tableau de bord",
        step1Title: "1. Choisir le fichier",
        dropTitle: "Glissez le fichier ici ou cliquez pour le choisir",
        dropHint: "xlsx · xls · csv · tsv · json",
        chooseFile: "Choisir un fichier",
        readingFile: "Lecture du fichier...",
        readError: "Impossible de lire le fichier. Vérifiez qu'il s'agit d'un fichier Excel ou CSV valide.",
        libMissing: "La bibliothèque de lecture des fichiers n'a pas pu être chargée. Rechargez la page et réessayez.",
        unsupportedType: "Type de fichier non pris en charge. Choisissez un fichier xlsx, xls ou csv.",
        emptySheet: "Cette feuille ne contient aucune donnée.",
        fileLoaded: "Fichier lu : {name} ({rows} lignes, {cols} colonnes).",
        rawPreviewToggle: "Afficher le fichier brut",
        sheetLabel: "Feuille",
        previewNote: "Affichage des {shown} premières lignes sur {total}.",
        columnN: "Colonne",
        step3Title: "Que voulez-vous importer",
        moreFieldsToggle: "Détails supplémentaires",
        headerPickerMsg: "Nous n'avons pas trouvé la ligne d'en-tête avec certitude — choisissez la bonne.",
        headerRowOption: "Ligne {n} — {preview}",
        previewMoreCols: "+{n} colonnes de plus",
        mapTitle: "Titre",
        mapDue: "Date d'échéance",
        mapCategory: "Catégorie",
        mapAssignee: "E-mail du responsable",
        mapStatus: "Statut",
        sheetKind: "Type de feuille",
        sheetKindGeneral: "Général (échéances et contrats)",
        sheetKindViolations: "Infractions",
        graceDays: "Délai de paiement (jours)",
        mapVNumber: "Numéro d'infraction",
        mapCaseNumber: "Numéro de dossier",
        mapAmount: "Montant de l'amende",
        mapClient: "Entreprise cliente",
        mapLocation: "Lieu",
        violationTitle: "Infraction n° {n}",
        required: "obligatoire",
        optional: "facultatif",
        notMapped: "— aucune —",
        mappingHint: "Les colonnes non associées sont enregistrées comme données supplémentaires sur chaque élément.",
        statusHint: "Dans la colonne statut, les valeurs done, منجز ou completed comptent comme terminées ; tout le reste reste ouvert.",
        validRows: "Lignes prêtes à importer : {n}",
        skippedRows: "Lignes ignorées (titre ou date valide manquant) : {n}",
        unmatchedAssignees: "Lignes dont l'e-mail du responsable n'appartient pas à l'équipe : {n}",
        unmatchedHint: "Ces adresses n'ont pas été trouvées parmi les membres de l'équipe ; leurs éléments seront importés sans responsable : {list}",
        step4Title: "Suivi",
        trackerLabel: "Ajouter les éléments à",
        newTracker: "Nouveau suivi",
        trackerNamePlaceholder: "Nom du nouveau suivi",
        trackerNameRequired: "Saisissez un nom pour le nouveau suivi.",
        step5Title: "Vérification du forfait et import",
        importsThisMonth: "Importations ce mois-ci",
        itemsUsage: "Éléments utilisés",
        rowsToImport: "Lignes à importer",
        unlimited: "Illimité",
        ofLimit: "{used} sur {limit}",
        checkingPlan: "Vérification de votre forfait...",
        planOk: "Votre forfait actuel autorise cette importation.",
        planImportsExceeded: "Vous avez atteint la limite d'importations de ce mois ({used} sur {limit}). Passez à un forfait supérieur pour continuer.",
        planItemsExceeded: "Le nombre de lignes valides ({rows}) dépasse les éléments restants de votre forfait ({remaining} restants sur {limit}). Passez à un forfait supérieur ou réduisez le nombre de lignes.",
        upgradePlan: "Changer de forfait",
        importBtn: "Lancer l'importation",
        mappingRequired: "Choisissez d'abord la colonne du titre et celle de la date d'échéance.",
        mappingRequiredDue: "Choisissez d'abord la colonne de la date d'échéance.",
        noValidRows: "Aucune ligne valide à importer. Vérifiez l'association des colonnes.",
        progressCreatingTracker: "Création du suivi...",
        progressImport: "Enregistrement de l'importation...",
        progressInserting: "Insertion des éléments : {done} sur {total}",
        progressRule: "Création de la règle de rappel par défaut...",
        importFailed: "Échec de l'importation : {error}",
        importPartial: "L'importation s'est arrêtée après l'insertion de {done} éléments.",
        planLimitItems: "Vous avez atteint la limite d'éléments de votre forfait actuel. Passez à un forfait supérieur pour en ajouter.",
        summaryTitle: "Importation terminée",
        summaryInserted: "Éléments insérés",
        summarySkipped: "Lignes ignorées",
        summaryUnmatched: "Lignes avec responsable non reconnu",
        summaryTracker: "Les éléments ont été ajoutés au suivi : {name}",
        summaryRuleNote: "Une règle de rappel par défaut a été créée : un rappel par e-mail un jour avant l'échéance.",
        summaryRuleFailed: "La règle de rappel par défaut n'a pas pu être créée ; vous pourrez l'ajouter plus tard depuis la page des rappels.",
        importAnother: "Importer un autre fichier",
        importIntro: "Importez un relevé d'infractions, un calendrier d'audiences ou tout tableau; ses lignes deviennent des éléments avec dates et rappels.",
        kind_articles_of_association: "Statuts constitutifs",
        kind_bylaws: "Règlement intérieur",
        kind_chamber_certificate: "Attestation chambre de commerce",
        kind_gosi_certificate: "Attestation GOSI",
        kind_zakat_certificate: "Attestation Zakat",
        kind_saudization_certificate: "Attestation de saoudisation",
        kind_lease_contract: "Contrat de bail",
        fCase: "Affaire",
        title: "Documents",
        docAddTitle: "Ajouter un document ou un tableur",
        docAddIntro: "Un document est lu, un tableur est importé.",
        docDropHint: "Déposez un fichier ou choisissez-en un",
        docChoose: "Choisir un fichier",
        docDrive: "Choisir depuis Google Drive",
        docDriveFailed: "Impossible de récupérer le fichier depuis Google Drive.",
        docKind: "Type de document",
        docTitleField: "Titre",
        docNumber: "Numéro",
        docIssuer: "Émetteur",
        docParty: "Entreprise / titulaire",
        docPartyEn: "Nom en anglais",
        docIssueDate: "Date d'émission",
        docExpiry: "Expiration / échéance",
        docAmount: "Montant (<span class=\"sar-symbol\" aria-label=\"ريال سعودي\"></span>)",
        docCase: "Numéro de dossier",
        docCourt: "Tribunal",
        docSave: "Enregistrer et suivre",
        docListTitle: "Documents de l'entreprise",
        docLeft: "Restant",
        docFiles: "Fichiers",
        docsEmpty: "Aucun document.",
        docReading: "Lecture du document...",
        docOcr: "Document image — lecture par IA...",
        docReady: "Document lu — vérifiez les champs puis enregistrez.",
        docFailed: "Lecture impossible ; essayez un fichier plus net.",
        docSaving: "Enregistrement...",
        fieldRemind: "Me rappeler avant l'expiration",
        remindDefault: "Selon la règle du registre",
        remindDay: "Un jour",
        remind3Days: "Trois jours",
        remindWeek: "Une semaine",
        remind2Weeks: "Deux semaines",
        remindMonth: "Un mois",
        pEndsIn: "Expire dans {n} jours",
        pEndsToday: "Expire aujourd'hui",
        pExpiredSince: "Expiré depuis {n} jours",
        docDetailsTitle: "Ce que le système a lu sur ce document",
        docProfileTitle: "Mettre à jour les données de l'entreprise",
        docProfileApply: "Mettre à jour les données",
        docProfileSkip: "Laisser mes données inchangées",
        docProfileDone: "Données de l'entreprise mises à jour.",
        docProfileNow: "Valeur actuelle",
        docProfileNew: "Sur le document",
        docDetailsOf: "Détails du document",
        docSaved: "Enregistré et ajouté au suivi.",
        docFileFailed: "Données enregistrées, mais le fichier n’a pas pu être téléversé.",
        docStorageLimit: "Données enregistrées, mais le stockage de votre forfait est plein.",
        papersTitle: "Documents officiels",
        papersNote: "Manquants et expirés apparaissent ici ; rappels sur Telegram.",
        papersState: "État",
        pMissing: "Manquant",
        pValid: "Valide",
        pExpiring: "Bientôt expiré",
        pExpired: "Expiré",
        pStored: "Enregistré, sans date",
        pRequired: "Obligatoire",
        pOptional: "Facultatif",
        pAdd: "Ajouter",
        pOpen: "Voir",
        pDownload: "Télécharger",
        docAttachFile: "Joindre un fichier",
        docAddAnother: "Ajouter un fichier",
        docFileAdded: "Fichier ajouté.",
        pOpen: "Ouvrir",
        pStatValid: "Valides",
        pStatExpiring: "Bientôt expirés",
        pStatExpired: "Expirés",
        pStatMissing: "Manquants",
        docReplace: "Remplacer",
        docExpired: "Expiré",
        docDays: "jours",
        docDeleteConfirm: "Supprimer ce document et ses fichiers ?",
        allKinds: "Tous les types",
        search: "Rechercher",
        actions: "Actions",
        delete: "Supprimer",
        unavailable: "Service indisponible.",
        kind_commercial_register: "Registre de commerce",
        kind_vat_certificate: "Attestation TVA",
        kind_license: "Licence",
        kind_contract: "Contrat",
        kind_case_filing: "Requête / dépôt",
        kind_court_ruling: "Jugement",
        kind_hearing_notice: "Avis d'audience",
        kind_violation: "Infraction",
        kind_invoice: "Facture",
        kind_power_of_attorney: "Procuration",
        kind_id_document: "Pièce d'identité",
        kind_passport: "Passeport",
        kind_driving_license: "Permis de conduire",
        kind_vehicle_registration: "Carte grise",
        kind_insurance_policy: "Police d'assurance",
        kind_employment_contract: "Contrat de travail",
        kind_other: "Autre document",
        intro: "Ajoutez les membres de votre équipe, définissez leurs rôles et suivez les invitations en attente.",
        backBtn: "Retour au tableau de bord",
        serviceUnavailableTitle: "Service en cours de préparation",
        serviceUnavailableText: "Nous préparons le service. Veuillez réessayer plus tard.",
        noOrg: "Aucune entreprise sélectionnée. Créez d'abord votre entreprise.",
        noOrgHint: "Rendez-vous sur le tableau de bord pour créer votre entreprise, puis revenez sur cette page.",
        loading: "Chargement...",
        loadError: "Impossible de charger les données de l'équipe. Veuillez réessayer.",
        membersTitle: "Membres de l'équipe",
        membersEmpty: "Aucun membre pour le moment.",
        readOnlyNote: "Seuls le propriétaire et les administrateurs peuvent gérer les membres et les invitations.",
        capacityLimited: "Membres : {used} sur {limit}",
        capacityUnlimited: "Membres : {used} (illimité)",
        capacityPending: "Invitations en attente : {n}",
        capacityFull: "Vous avez atteint la limite de membres de votre forfait actuel.",
        upgradeLink: "Changer de forfait",
        roleOwner: "Propriétaire",
        roleAdmin: "Administrateur",
        roleMember: "Membre",
        roleLabel: "Rôle",
        statusInvited: "En attente de connexion",
        you: "Vous",
        emailLabel: "E-mail",
        joinedLabel: "Membre depuis le",
        changeRoleLabel: "Changer le rôle",
        removeBtn: "Retirer",
        confirmRemove: "Retirer {name} de l'équipe ?",
        memberRemoved: "Membre retiré.",
        roleUpdated: "Rôle mis à jour.",
        inviteTitle: "Inviter un nouveau membre",
        inviteIntro: "Saisissez l'e-mail du membre et choisissez son rôle. S'il est inscrit sur la plateforme, il reçoit aussitôt une notification dans la cloche et rejoint l'équipe à sa prochaine ouverture de l'application. Sinon, envoyez-lui le lien de connexion :",
        copyLinkBtn: "Copier le lien de connexion",
        linkCopied: "Lien copié.",
        inviteEmailPlaceholder: "Adresse e-mail du membre",
        inviteBtn: "Inviter",
        lookupTitle: "Ou parmi les utilisateurs inscrits",
        inviteByEmailTitle: "Par e-mail",
        lookupBtn: "Afficher les utilisateurs",
        lookupPlaceholder: "E-mail, mobile ou numéro",
        lookupNone: "Aucun utilisateur trouvé. Vous pouvez l'inviter par e-mail.",
        inviteSending: "Ajout en cours...",
        inviteCreated: "Invitation ajoutée pour {email}. Cette personne rejoindra l'équipe automatiquement lors de sa connexion.",
        workloadTitle: "Répartition du travail",
        workloadIntro: "Glissez le travail sur un membre.",
        rasiTitle: "Matrice RASI",
        rasiIntro: "Pour chaque affaire, infraction ou tâche : qui exécute (R), qui approuve et répond (A — un seul), qui soutient (S), qui est informé (I). Cliquez une case pour changer le rôle ; la personne est notifiée aussitôt.",
        rasiLegendR: "Responsable",
        rasiLegendA: "Approbateur",
        rasiLegendS: "Soutien",
        rasiLegendI: "Informé",
        rasiSearch: "Rechercher par titre ou numéro",
        rasiEmpty: "Aucun élément ouvert à afficher.",
        rasiItemCol: "Élément",
        rasiSaved: "Rôle enregistré.",
        rasiNoMembers: "Ajoutez d’abord des membres.",
        quickTitle: "Répartition rapide",
        quickHint: "Touchez un membre sur un élément : un clic = Responsable (R) et vous Approbateur (A) automatiquement, deuxième clic = Soutien (S), troisième = retirer.",
        rasiShowMatrix: "Afficher la matrice complète",
        rasiHideMatrix: "Masquer la matrice",
        quickAddTitle: "Saisie rapide",
        quickAddHint: "Écrivez-la comme vous la diriez : « Audience affaire 4521, Al-Abraj, dimanche 10 h, pour Ahmad » — type, date, client, numéro d’affaire et responsable sont compris, enregistrés et répartis en un clic.",
        quickAddBtn: "Ajouter",
        quickAddPh: "Tapez la tâche, qui la fait et quand…",
        quickAddNobody: "Sans responsable",
        quickAddParsing: "Analyse…",
        quickAddDone: "« {title} » enregistrée{who}.",
        quickAddNoTitle: "Aucune tâche lisible dans ce texte — donnez au moins un titre.",
